{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Analytics"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/kksplayer\/analytics"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/kksplayer\/analytics"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/KKS.KKSPlayer\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/KKS.KKSPlayer\/objc(pl)NSObject","doc:\/\/KKS.KKSPlayer\/s7CVarArgP","doc:\/\/KKS.KKSPlayer\/s28CustomDebugStringConvertibleP","doc:\/\/KKS.KKSPlayer\/s23CustomStringConvertibleP","doc:\/\/KKS.KKSPlayer\/SQ","doc:\/\/KKS.KKSPlayer\/SH","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniLoggerListener"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/Analytics","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/Analytics\/init(config:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/Analytics\/UniLoggerListener-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Analytics"}],"title":"Analytics","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@KKSPlayer@objc(cs)Analytics","modules":[{"name":"KKSPlayer"}],"navigatorTitle":[{"kind":"identifier","text":"Analytics"}]},"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer"]]},"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniLoggerListener":{"role":"symbol","title":"UniLoggerListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniLoggerListener"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniLoggerListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UniLoggerListener"}],"url":"\/documentation\/kksplayer\/uniloggerlistener"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/Analytics":{"role":"symbol","title":"Analytics","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Analytics"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/Analytics","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Analytics"}],"url":"\/documentation\/kksplayer\/analytics"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/Analytics/UniLoggerListener-Implementations":{"role":"collectionGroup","title":"UniLoggerListener Implementations","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/Analytics\/UniLoggerListener-Implementations","kind":"article","type":"topic","url":"\/documentation\/kksplayer\/analytics\/uniloggerlistener-implementations"},"doc://KKS.KKSPlayer/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/KKS.KKSPlayer\/s7CVarArgP"},"doc://KKS.KKSPlayer/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/KKS.KKSPlayer\/SH"},"doc://KKS.KKSPlayer/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/KKS.KKSPlayer\/SQ"},"doc://KKS.KKSPlayer/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)NSObject"},"doc://KKS.KKSPlayer/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/KKS.KKSPlayer\/s23CustomStringConvertibleP"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/Analytics/init(config:)":{"role":"symbol","title":"init(config:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"config"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/Analytics\/init(config:)","kind":"symbol","type":"topic","url":"\/documentation\/kksplayer\/analytics\/init(config:)"},"doc://KKS.KKSPlayer/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/KKS.KKSPlayer\/s28CustomDebugStringConvertibleP"},"doc://KKS.KKSPlayer/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/KKS.KKSPlayer\/objc(cs)NSObject"},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"role":"collection","title":"KKSPlayer","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","kind":"symbol","type":"topic","url":"\/documentation\/kksplayer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"Analytics"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"Analytics"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"Analytics"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/KKS.KKSPlayer\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"Analytics"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1Analytics\/title","value":"Analytics"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1Analytics\/fragments","value":[{"kind":"identifier","text":"Analytics"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}