{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CastManager","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Singleton providing access to GoogleCast related features."},{"text":" ","type":"text"},{"text":"The CastManager needs to be initialized by calling CastManager#initializeCasting in the AppDelegate of the application which should support casting.","type":"text"}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/currentDevice","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/currentMediaMetadata","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/currentMediaStatus","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/isConnected","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/isConnecting"]},{"identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/add(listener:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/checkReceiverIsPlayingSameContent(_:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/loadMedia(_:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/remove(listener:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/unload()"],"title":"Instance Methods"},{"title":"Type Properties","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/shared"]},{"title":"Type Methods","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/initializeCasting()","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/initializeCasting(options:)"]},{"identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/GCKRemoteMediaClientListener-Implementations","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/GCKRequestDelegate-Implementations","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/GCKSessionManagerListener-Implementations"],"generated":true,"title":"Default Implementations"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer"]]},"metadata":{"title":"CastManager","symbolKind":"class","modules":[{"name":"BVPlayer"}],"roleHeading":"Class","navigatorTitle":[{"text":"CastManager","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CastManager","kind":"identifier"}],"role":"symbol","externalID":"c:@M@KKSPlayer@objc(cs)CastManager"},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/KKS.KKSPlayer\/objc(cs)NSObject"]},{"kind":"relationships","identifiers":["doc:\/\/KKS.KKSPlayer\/objc(pl)GCKRemoteMediaClientListener","doc:\/\/KKS.KKSPlayer\/objc(pl)GCKRequestDelegate","doc:\/\/KKS.KKSPlayer\/objc(pl)GCKSessionManagerListener","doc:\/\/KKS.KKSPlayer\/objc(pl)NSObject","doc:\/\/KKS.KKSPlayer\/s7CVarArgP","doc:\/\/KKS.KKSPlayer\/s28CustomDebugStringConvertibleP","doc:\/\/KKS.KKSPlayer\/s23CustomStringConvertibleP","doc:\/\/KKS.KKSPlayer\/SQ","doc:\/\/KKS.KKSPlayer\/SH"],"title":"Conforms To","type":"conformsTo"}],"sections":[],"variants":[{"paths":["\/documentation\/kksplayer\/castmanager"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/kksplayer\/castmanager"]}],"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/GCKRemoteMediaClientListener-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/GCKRemoteMediaClientListener-Implementations","kind":"article","title":"GCKRemoteMediaClientListener Implementations","type":"topic","abstract":[],"url":"\/documentation\/kksplayer\/castmanager\/gckremotemediaclientlistener-implementations"},"doc://KKS.KKSPlayer/objc(cs)NSObject":{"identifier":"doc:\/\/KKS.KKSPlayer\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/loadMedia(_:)":{"role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/loadMedia(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadMedia","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:9KKSPlayer15UniSourceConfigC","text":"UniSourceConfig","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"loadMedia(_:)","type":"topic","abstract":[{"text":"Loads media with the provided source configuration.","type":"text"}],"url":"\/documentation\/kksplayer\/castmanager\/loadmedia(_:)"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/unload()":{"role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/unload()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unload","kind":"identifier"},{"text":"()","kind":"text"}],"title":"unload()","type":"topic","abstract":[],"url":"\/documentation\/kksplayer\/castmanager\/unload()"},"doc://KKS.KKSPlayer/objc(pl)NSObject":{"identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/isConnected":{"role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/isConnected","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isConnected","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"isConnected","type":"topic","abstract":[],"url":"\/documentation\/kksplayer\/castmanager\/isconnected"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/initializeCasting(options:)":{"role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/initializeCasting(options:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initializeCasting","kind":"identifier"},{"text":"(","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CastManagerOptions","kind":"typeIdentifier","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)CastManagerOptions"},{"text":")","kind":"text"}],"title":"initializeCasting(options:)","type":"topic","abstract":[{"text":"Initialize CastManager based on the provided CastManagerOptions.","type":"text"}],"url":"\/documentation\/kksplayer\/castmanager\/initializecasting(options:)"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/currentDevice":{"role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/currentDevice","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentDevice","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GCKDevice","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKDevice"},{"text":"?","kind":"text"}],"title":"currentDevice","type":"topic","abstract":[],"url":"\/documentation\/kksplayer\/castmanager\/currentdevice"},"doc://KKS.KKSPlayer/objc(pl)GCKRequestDelegate":{"identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)GCKRequestDelegate","title":"GCKRequestDelegate","type":"unresolvable"},"doc://KKS.KKSPlayer/s7CVarArgP":{"identifier":"doc:\/\/KKS.KKSPlayer\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/GCKRequestDelegate-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/GCKRequestDelegate-Implementations","kind":"article","title":"GCKRequestDelegate Implementations","type":"topic","abstract":[],"url":"\/documentation\/kksplayer\/castmanager\/gckrequestdelegate-implementations"},"doc://KKS.KKSPlayer/objc(pl)GCKSessionManagerListener":{"identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)GCKSessionManagerListener","type":"unresolvable","title":"GCKSessionManagerListener"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/initializeCasting()":{"role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/initializeCasting()","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initializeCasting","kind":"identifier"},{"text":"()","kind":"text"}],"title":"initializeCasting()","type":"topic","abstract":[{"text":"Uses default BV1 receiver app","type":"text"}],"url":"\/documentation\/kksplayer\/castmanager\/initializecasting()"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/currentMediaStatus":{"role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/currentMediaStatus","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentMediaStatus","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GCKMediaStatus","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKMediaStatus"},{"text":"?","kind":"text"}],"title":"currentMediaStatus","type":"topic","abstract":[],"url":"\/documentation\/kksplayer\/castmanager\/currentmediastatus"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/shared":{"role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/shared","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CastManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)CastManager"}],"title":"shared","type":"topic","abstract":[],"url":"\/documentation\/kksplayer\/castmanager\/shared"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager":{"type":"topic","url":"\/documentation\/kksplayer\/castmanager","abstract":[{"text":"Singleton providing access to GoogleCast related features.","type":"text"},{"text":" ","type":"text"},{"text":"The CastManager needs to be initialized by calling CastManager#initializeCasting in the AppDelegate of the application which should support casting.","type":"text"}],"title":"CastManager","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CastManager","kind":"identifier"}],"navigatorTitle":[{"text":"CastManager","kind":"identifier"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager"},"doc://KKS.KKSPlayer/s23CustomStringConvertibleP":{"identifier":"doc:\/\/KKS.KKSPlayer\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/add(listener:)":{"role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/add(listener:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"add","kind":"identifier"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CastManagerListener","preciseIdentifier":"s:9KKSPlayer19CastManagerListenerP","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"add(listener:)","type":"topic","abstract":[],"url":"\/documentation\/kksplayer\/castmanager\/add(listener:)"},"doc://KKS.KKSPlayer/SQ":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/SQ","title":"Swift.Equatable"},"doc://KKS.KKSPlayer/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","abstract":[{"text":"BlendVision One iOS Player SDK","type":"text"}],"title":"BVPlayer","url":"\/documentation\/kksplayer","kind":"symbol","role":"collection"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/isConnecting":{"role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/isConnecting","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isConnecting","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"isConnecting","type":"topic","abstract":[],"url":"\/documentation\/kksplayer\/castmanager\/isconnecting"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/currentMediaMetadata":{"role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/currentMediaMetadata","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentMediaMetadata","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GCKMediaMetadata","text":"GCKMediaMetadata","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"currentMediaMetadata","type":"topic","abstract":[],"url":"\/documentation\/kksplayer\/castmanager\/currentmediametadata"},"doc://KKS.KKSPlayer/objc(pl)GCKRemoteMediaClientListener":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)GCKRemoteMediaClientListener","title":"GCKRemoteMediaClientListener"},"doc://KKS.KKSPlayer/SH":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/SH","title":"Swift.Hashable"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/GCKSessionManagerListener-Implementations":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/GCKSessionManagerListener-Implementations","type":"topic","abstract":[],"title":"GCKSessionManagerListener Implementations","role":"collectionGroup","kind":"article","url":"\/documentation\/kksplayer\/castmanager\/gcksessionmanagerlistener-implementations"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/checkReceiverIsPlayingSameContent(_:)":{"role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/checkReceiverIsPlayingSameContent(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkReceiverIsPlayingSameContent","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:9KKSPlayer15UniSourceConfigC","text":"UniSourceConfig","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"checkReceiverIsPlayingSameContent(_:)","type":"topic","abstract":[{"type":"text","text":"Checks if the receiver is currently playing the same content."}],"url":"\/documentation\/kksplayer\/castmanager\/checkreceiverisplayingsamecontent(_:)"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/remove(listener:)":{"role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/remove(listener:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remove","kind":"identifier"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CastManagerListener","preciseIdentifier":"s:9KKSPlayer19CastManagerListenerP","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"remove(listener:)","type":"topic","abstract":[],"url":"\/documentation\/kksplayer\/castmanager\/remove(listener:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"CastManager","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"CastManager","kind":"identifier"}],"op":"replace"},{"value":[{"text":"CastManager","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/GCKRemoteMediaClientListener-Implementations","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/GCKRequestDelegate-Implementations","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/GCKSessionManagerListener-Implementations"]}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/KKS.KKSPlayer\/objc(cs)NSObject"]},{"kind":"relationships","identifiers":["doc:\/\/KKS.KKSPlayer\/objc(pl)GCKRemoteMediaClientListener","doc:\/\/KKS.KKSPlayer\/objc(pl)GCKRequestDelegate","doc:\/\/KKS.KKSPlayer\/objc(pl)GCKSessionManagerListener"],"title":"Conforms To","type":"conformsTo"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"CastManager","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"}},{"value":"CastManager","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager\/fragments","value":[{"text":"CastManager","kind":"identifier"}]}]}]}