{"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniAudioTrack","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniAudioTrack"}],"navigatorTitle":[{"kind":"identifier","text":"UniAudioTrack"}],"role":"symbol","externalID":"c:@M@KKSPlayer@objc(cs)UniAudioTrack","title":"UniAudioTrack","symbolKind":"class","roleHeading":"Class","modules":[{"name":"BVPlayer"}]},"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrack"]},{"identifiers":["doc:\/\/KKS.KKSPlayer\/objc(pl)NSObject","doc:\/\/KKS.KKSPlayer\/s7CVarArgP","doc:\/\/KKS.KKSPlayer\/s28CustomDebugStringConvertibleP","doc:\/\/KKS.KKSPlayer\/s23CustomStringConvertibleP","doc:\/\/KKS.KKSPlayer\/SQ","doc:\/\/KKS.KKSPlayer\/SH","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrackProtocol"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UniAudioTrack","kind":"identifier"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kksplayer\/uniaudiotrack"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/kksplayer\/uniaudiotrack"]}],"references":{"doc://KKS.KKSPlayer/s23CustomStringConvertibleP":{"identifier":"doc:\/\/KKS.KKSPlayer\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://KKS.KKSPlayer/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)NSObject"},"doc://KKS.KKSPlayer/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/KKS.KKSPlayer\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniTrack":{"type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrack","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"UniTrack","kind":"identifier"}],"title":"UniTrack","url":"\/documentation\/kksplayer\/unitrack","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UniTrack","kind":"identifier"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniTrackProtocol":{"kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrackProtocol","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniTrackProtocol"}],"navigatorTitle":[{"text":"UniTrackProtocol","kind":"identifier"}],"url":"\/documentation\/kksplayer\/unitrackprotocol","type":"topic","title":"UniTrackProtocol","role":"symbol"},"doc://KKS.KKSPlayer/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/SQ"},"doc://KKS.KKSPlayer/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/KKS.KKSPlayer\/SH"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniAudioTrack":{"url":"\/documentation\/kksplayer\/uniaudiotrack","title":"UniAudioTrack","abstract":[],"role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniAudioTrack","navigatorTitle":[{"text":"UniAudioTrack","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UniAudioTrack","kind":"identifier"}],"kind":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","abstract":[{"text":"BlendVision One iOS Player SDK","type":"text"}],"title":"BVPlayer","url":"\/documentation\/kksplayer","kind":"symbol","role":"collection"},"doc://KKS.KKSPlayer/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/KKS.KKSPlayer\/s7CVarArgP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"UniAudioTrack","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"UniAudioTrack","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"UniAudioTrack","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrack"],"kind":"relationships","type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"UniAudioTrack","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniTrack","text":"UniTrack","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrack"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"UniTrack","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniTrack\/title"},{"op":"replace","value":[{"kind":"identifier","text":"UniTrack"}],"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniTrack\/fragments"},{"op":"replace","value":"UniAudioTrack","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniAudioTrack\/title"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniAudioTrack\/fragments","value":[{"kind":"identifier","text":"UniAudioTrack"}]}]}]}