{"metadata":{"modules":[{"name":"KKSPlayer"}],"navigatorTitle":[{"text":"UniControllerPlayerView","kind":"identifier"}],"title":"UniControllerPlayerView","role":"symbol","externalID":"c:@M@KKSPlayer@objc(cs)UniControllerPlayerView","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UniControllerPlayerView","kind":"identifier"}],"roleHeading":"Class"},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniControllerPlayerView","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniControllerPlayerView\/init(player:frame:)"]},{"title":"Instance Methods","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniControllerPlayerView\/player(_:didReceiveOnReadyEvent:)"]}],"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniControllerPlayerView"}],"languages":["swift"]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/kksplayer\/unicontrollerplayerview"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/kksplayer\/unicontrollerplayerview"]}],"sections":[],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView"],"kind":"relationships"},{"kind":"relationships","identifiers":["doc:\/\/KKS.KKSPlayer\/objc(pl)NSCoding","doc:\/\/KKS.KKSPlayer\/objc(pl)NSObject","doc:\/\/KKS.KKSPlayer\/objc(pl)CALayerDelegate","doc:\/\/KKS.KKSPlayer\/s7CVarArgP","doc:\/\/KKS.KKSPlayer\/s28CustomDebugStringConvertibleP","doc:\/\/KKS.KKSPlayer\/s23CustomStringConvertibleP","doc:\/\/KKS.KKSPlayer\/SQ","doc:\/\/KKS.KKSPlayer\/SH","doc:\/\/KKS.KKSPlayer\/s8SendableP","doc:\/\/KKS.KKSPlayer\/objc(pl)UIAccessibilityIdentification","doc:\/\/KKS.KKSPlayer\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/KKS.KKSPlayer\/objc(pl)UIAppearance","doc:\/\/KKS.KKSPlayer\/objc(pl)UIAppearanceContainer","doc:\/\/KKS.KKSPlayer\/objc(pl)UICoordinateSpace","doc:\/\/KKS.KKSPlayer\/objc(pl)UIDynamicItem","doc:\/\/KKS.KKSPlayer\/objc(pl)UIFocusEnvironment","doc:\/\/KKS.KKSPlayer\/objc(pl)UIFocusItem","doc:\/\/KKS.KKSPlayer\/objc(pl)UIFocusItemContainer","doc:\/\/KKS.KKSPlayer\/objc(pl)UILargeContentViewerItem","doc:\/\/KKS.KKSPlayer\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/KKS.KKSPlayer\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/KKS.KKSPlayer\/objc(pl)UIResponderStandardEditActions","doc:\/\/KKS.KKSPlayer\/5UIKit23UITraitChangeObservableP","doc:\/\/KKS.KKSPlayer\/objc(pl)UITraitEnvironment","doc:\/\/KKS.KKSPlayer\/objc(pl)UIUserActivityRestoring","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceListener"],"title":"Conforms To","type":"conformsTo"}],"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSourceListener":{"url":"\/documentation\/kksplayer\/unisourcelistener","abstract":[],"kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UniSourceListener","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UniSourceListener"}],"title":"UniSourceListener","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceListener"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniControllerPlayerView":{"url":"\/documentation\/kksplayer\/unicontrollerplayerview","abstract":[],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UniControllerPlayerView","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"UniControllerPlayerView","kind":"identifier"}],"title":"UniControllerPlayerView","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniControllerPlayerView"},"doc://KKS.KKSPlayer/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://KKS.KKSPlayer/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://KKS.KKSPlayer/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://KKS.KKSPlayer/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniPlayerView"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UniPlayerView"}],"url":"\/documentation\/kksplayer\/uniplayerview","type":"topic","abstract":[],"title":"UniPlayerView"},"doc://KKS.KKSPlayer/objc(pl)UIAppearance":{"title":"UIKit.UIAppearance","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIAppearance","type":"unresolvable"},"doc://KKS.KKSPlayer/objc(pl)NSCoding":{"title":"Foundation.NSCoding","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)NSCoding","type":"unresolvable"},"doc://KKS.KKSPlayer/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/KKS.KKSPlayer\/5UIKit23UITraitChangeObservableP","type":"unresolvable"},"doc://KKS.KKSPlayer/objc(pl)UIFocusItem":{"title":"UIKit.UIFocusItem","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIFocusItem","type":"unresolvable"},"doc://KKS.KKSPlayer/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)NSObject","type":"unresolvable"},"doc://KKS.KKSPlayer/objc(pl)CALayerDelegate":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate"},"doc://KKS.KKSPlayer/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://KKS.KKSPlayer/objc(pl)UIFocusItemContainer":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIFocusItemContainer","title":"UIKit.UIFocusItemContainer"},"doc://KKS.KKSPlayer/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/s8SendableP","title":"Swift.Sendable"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerListener":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"UniPlayerListener","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"UniPlayerListener"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener","type":"topic","url":"\/documentation\/kksplayer\/uniplayerlistener","title":"UniPlayerListener","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Defines listener methods for all events available for the Player"}]},"doc://KKS.KKSPlayer/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://KKS.KKSPlayer/SQ":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/SQ","title":"Swift.Equatable"},"doc://KKS.KKSPlayer/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://KKS.KKSPlayer/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIAccessibilityIdentification","title":"UIKit.UIAccessibilityIdentification"},"doc://KKS.KKSPlayer/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://KKS.KKSPlayer/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://KKS.KKSPlayer/objc(pl)UICoordinateSpace":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UICoordinateSpace","title":"UIKit.UICoordinateSpace"},"doc://KKS.KKSPlayer/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UILargeContentViewerItem","title":"UIKit.UILargeContentViewerItem"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniControllerPlayerView/init(player:frame:)":{"url":"\/documentation\/kksplayer\/unicontrollerplayerview\/init(player:frame:)","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniControllerPlayerView\/init(player:frame:)","kind":"symbol","abstract":[{"type":"text","text":"Creates a new instance of the PlayerView."}],"type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"player"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","text":"UniPlayer"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":")","kind":"text"}],"title":"init(player:frame:)"},"doc://KKS.KKSPlayer/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/SH"},"doc://KKS.KKSPlayer/objc(pl)UIDynamicItem":{"title":"UIKit.UIDynamicItem","type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIDynamicItem"},"doc://KKS.KKSPlayer/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/s7CVarArgP"},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","role":"collection","url":"\/documentation\/kksplayer","kind":"symbol","title":"KKSPlayer","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniControllerPlayerView/player(_:didReceiveOnReadyEvent:)":{"url":"\/documentation\/kksplayer\/unicontrollerplayerview\/player(_:didreceiveonreadyevent:)","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniControllerPlayerView\/player(_:didReceiveOnReadyEvent:)","kind":"symbol","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"player"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","text":"UniPlayer","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveOnReadyEvent"},{"kind":"text","text":": "},{"text":"UniEvent","kind":"typeIdentifier","preciseIdentifier":"s:9KKSPlayer8UniEventP"},{"kind":"text","text":")"}],"title":"player(_:didReceiveOnReadyEvent:)"},"doc://KKS.KKSPlayer/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","value":"UniControllerPlayerView","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"UniControllerPlayerView","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"UniControllerPlayerView"}]},{"op":"replace","value":null,"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView"],"title":"Inherits From"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"UniControllerPlayerView","kind":"identifier"},{"kind":"text","text":" : "},{"text":"UniPlayerView","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayerView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"UniControllerPlayerView","op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniControllerPlayerView\/title"},{"value":[{"text":"UniControllerPlayerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniControllerPlayerView\/fragments"},{"value":"UniPlayerView","op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerView\/title"},{"value":[{"kind":"identifier","text":"UniPlayerView"}],"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerView\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}