{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniPlayerControlView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/kksplayer\/uniplayercontrolview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/kksplayer\/uniplayercontrolview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/KKS.KKSPlayer\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/KKS.KKSPlayer\/objc(pl)NSCoding","doc:\/\/KKS.KKSPlayer\/objc(pl)NSObject","doc:\/\/KKS.KKSPlayer\/objc(pl)CALayerDelegate","doc:\/\/KKS.KKSPlayer\/s7CVarArgP","doc:\/\/KKS.KKSPlayer\/s28CustomDebugStringConvertibleP","doc:\/\/KKS.KKSPlayer\/s23CustomStringConvertibleP","doc:\/\/KKS.KKSPlayer\/SQ","doc:\/\/KKS.KKSPlayer\/SH","doc:\/\/KKS.KKSPlayer\/s8SendableP","doc:\/\/KKS.KKSPlayer\/objc(pl)UIAccessibilityIdentification","doc:\/\/KKS.KKSPlayer\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/KKS.KKSPlayer\/objc(pl)UIAppearance","doc:\/\/KKS.KKSPlayer\/objc(pl)UIAppearanceContainer","doc:\/\/KKS.KKSPlayer\/objc(pl)UICoordinateSpace","doc:\/\/KKS.KKSPlayer\/objc(pl)UIDynamicItem","doc:\/\/KKS.KKSPlayer\/objc(pl)UIFocusEnvironment","doc:\/\/KKS.KKSPlayer\/objc(pl)UIFocusItem","doc:\/\/KKS.KKSPlayer\/objc(pl)UIFocusItemContainer","doc:\/\/KKS.KKSPlayer\/objc(pl)UILargeContentViewerItem","doc:\/\/KKS.KKSPlayer\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/KKS.KKSPlayer\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/KKS.KKSPlayer\/objc(pl)UIResponderStandardEditActions","doc:\/\/KKS.KKSPlayer\/objc(pl)UITraitEnvironment","doc:\/\/KKS.KKSPlayer\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerControlView","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerControlView\/init(frame:config:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniPlayerControlView"}],"title":"UniPlayerControlView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@KKSPlayer@objc(cs)UniPlayerControlView","modules":[{"name":"KKSPlayer"}],"navigatorTitle":[{"kind":"identifier","text":"UniPlayerControlView"}]},"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer"]]},"references":{"doc://KKS.KKSPlayer/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIFocusItem"},"doc://KKS.KKSPlayer/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/KKS.KKSPlayer\/s8SendableP"},"doc://KKS.KKSPlayer/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UITraitEnvironment"},"doc://KKS.KKSPlayer/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/KKS.KKSPlayer\/s28CustomDebugStringConvertibleP"},"doc://KKS.KKSPlayer/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)CALayerDelegate"},"doc://KKS.KKSPlayer/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UILargeContentViewerItem"},"doc://KKS.KKSPlayer/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIFocusEnvironment"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerControlView/init(frame:config:)":{"role":"symbol","title":"init(frame:config:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UniControlViewConfig","preciseIdentifier":"s:9KKSPlayer20UniControlViewConfigV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerControlView\/init(frame:config:)","kind":"symbol","type":"topic","url":"\/documentation\/kksplayer\/uniplayercontrolview\/init(frame:config:)"},"doc://KKS.KKSPlayer/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/KKS.KKSPlayer\/s7CVarArgP"},"doc://KKS.KKSPlayer/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/KKS.KKSPlayer\/objc(cs)UIView"},"doc://KKS.KKSPlayer/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIAccessibilityIdentification"},"doc://KKS.KKSPlayer/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIAppearanceContainer"},"doc://KKS.KKSPlayer/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)NSCoding"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerControlView":{"role":"symbol","title":"UniPlayerControlView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniPlayerControlView"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerControlView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UniPlayerControlView"}],"url":"\/documentation\/kksplayer\/uniplayercontrolview"},"doc://KKS.KKSPlayer/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://KKS.KKSPlayer/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/KKS.KKSPlayer\/s23CustomStringConvertibleP"},"doc://KKS.KKSPlayer/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/KKS.KKSPlayer\/SH"},"doc://KKS.KKSPlayer/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIFocusItemContainer"},"doc://KKS.KKSPlayer/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://KKS.KKSPlayer/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/KKS.KKSPlayer\/SQ"},"doc://KKS.KKSPlayer/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIAppearance"},"doc://KKS.KKSPlayer/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIDynamicItem"},"doc://KKS.KKSPlayer/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIUserActivityRestoring"},"doc://KKS.KKSPlayer/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIPasteConfigurationSupporting"},"doc://KKS.KKSPlayer/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)NSObject"},"doc://KKS.KKSPlayer/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UICoordinateSpace"},"doc://KKS.KKSPlayer/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIResponderStandardEditActions"},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"role":"collection","title":"KKSPlayer","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","kind":"symbol","type":"topic","url":"\/documentation\/kksplayer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"UniPlayerControlView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"UniPlayerControlView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"UniPlayerControlView"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/KKS.KKSPlayer\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniPlayerControlView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerControlView\/title","value":"UniPlayerControlView"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerControlView\/fragments","value":[{"kind":"identifier","text":"UniPlayerControlView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}