{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"class","role":"symbol","modules":[{"name":"KKSPlayer"}],"roleHeading":"Class","title":"UniPlayerView","externalID":"c:@M@KKSPlayer@objc(cs)UniPlayerView","navigatorTitle":[{"kind":"identifier","text":"UniPlayerView"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniPlayerView"}]},"topicSections":[{"identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/init(player:frame:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/init(player:frame:playerViewConfig:)"],"title":"Initializers"},{"identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/fullscreenHandler","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/isPictureInPicture","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/isPictureInPictureAvailable","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/managesPlaybackControlsAutomatically","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/posterViewConfig","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/showsPlaybackControls","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/styleConfig"],"title":"Instance Properties"},{"identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/enterFullscreen()","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/exitFullscreen()","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/player(_:didReceiveOnReadyEvent:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/startPictureInPicture()","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/stopPictureInPicture()","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/touchesEnded(_:with:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/UniPlayerListener-Implementations","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/UniSourceListener-Implementations","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/UniUserInterfaceEventHandler-Implementations"],"title":"Default Implementations","generated":true}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/KKS.KKSPlayer\/objc(cs)UIView"],"title":"Inherits From","type":"inheritsFrom"},{"title":"Inherited By","type":"inheritedBy","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniControllerPlayerView"],"kind":"relationships"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/KKS.KKSPlayer\/objc(pl)NSCoding","doc:\/\/KKS.KKSPlayer\/objc(pl)NSObject","doc:\/\/KKS.KKSPlayer\/objc(pl)CALayerDelegate","doc:\/\/KKS.KKSPlayer\/s7CVarArgP","doc:\/\/KKS.KKSPlayer\/s28CustomDebugStringConvertibleP","doc:\/\/KKS.KKSPlayer\/s23CustomStringConvertibleP","doc:\/\/KKS.KKSPlayer\/SQ","doc:\/\/KKS.KKSPlayer\/SH","doc:\/\/KKS.KKSPlayer\/s8SendableP","doc:\/\/KKS.KKSPlayer\/objc(pl)UIAccessibilityIdentification","doc:\/\/KKS.KKSPlayer\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/KKS.KKSPlayer\/objc(pl)UIAppearance","doc:\/\/KKS.KKSPlayer\/objc(pl)UIAppearanceContainer","doc:\/\/KKS.KKSPlayer\/objc(pl)UICoordinateSpace","doc:\/\/KKS.KKSPlayer\/objc(pl)UIDynamicItem","doc:\/\/KKS.KKSPlayer\/objc(pl)UIFocusEnvironment","doc:\/\/KKS.KKSPlayer\/objc(pl)UIFocusItem","doc:\/\/KKS.KKSPlayer\/objc(pl)UIFocusItemContainer","doc:\/\/KKS.KKSPlayer\/objc(pl)UILargeContentViewerItem","doc:\/\/KKS.KKSPlayer\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/KKS.KKSPlayer\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/KKS.KKSPlayer\/objc(pl)UIResponderStandardEditActions","doc:\/\/KKS.KKSPlayer\/5UIKit23UITraitChangeObservableP","doc:\/\/KKS.KKSPlayer\/objc(pl)UITraitEnvironment","doc:\/\/KKS.KKSPlayer\/objc(pl)UIUserActivityRestoring","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceListener"]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kksplayer\/uniplayerview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/kksplayer\/uniplayerview"]}],"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UniPlayerView","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://KKS.KKSPlayer/objc(pl)UIFocusItemContainer":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIFocusItemContainer","title":"UIKit.UIFocusItemContainer"},"doc://KKS.KKSPlayer/SH":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/SH","title":"Swift.Hashable"},"doc://KKS.KKSPlayer/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://KKS.KKSPlayer/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UILargeContentViewerItem","title":"UIKit.UILargeContentViewerItem"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView/stopPictureInPicture()":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/stopPictureInPicture()","url":"\/documentation\/kksplayer\/uniplayerview\/stoppictureinpicture()","abstract":[{"type":"text","text":"Stops Picture in Picture, if active."}],"kind":"symbol","role":"symbol","title":"stopPictureInPicture()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"stopPictureInPicture","kind":"identifier"},{"kind":"text","text":"()"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView/posterViewConfig":{"kind":"symbol","role":"symbol","title":"posterViewConfig","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/posterViewConfig","url":"\/documentation\/kksplayer\/uniplayerview\/posterviewconfig","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"posterViewConfig","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:9KKSPlayer16PosterViewConfigV","text":"PosterViewConfig"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Provides info to configure poster view"}]},"doc://KKS.KKSPlayer/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/s7CVarArgP","title":"Swift.CVarArg"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView/isPictureInPictureAvailable":{"title":"isPictureInPictureAvailable","url":"\/documentation\/kksplayer\/uniplayerview\/ispictureinpictureavailable","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isPictureInPictureAvailable"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"text":"Returns if Picture-In-Picture is available.","type":"text"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/isPictureInPictureAvailable","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniPlayerView"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UniPlayerView"}],"url":"\/documentation\/kksplayer\/uniplayerview","type":"topic","abstract":[],"title":"UniPlayerView"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView/managesPlaybackControlsAutomatically":{"type":"topic","title":"managesPlaybackControlsAutomatically","url":"\/documentation\/kksplayer\/uniplayerview\/managesplaybackcontrolsautomatically","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"managesPlaybackControlsAutomatically"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/managesPlaybackControlsAutomatically","abstract":[]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView/styleConfig":{"kind":"symbol","role":"symbol","title":"styleConfig","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/styleConfig","url":"\/documentation\/kksplayer\/uniplayerview\/styleconfig","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"styleConfig"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9KKSPlayer14UniStyleConfigC","text":"UniStyleConfig","kind":"typeIdentifier"}],"type":"topic","abstract":[{"type":"text","text":"The property is used to present UI style"}]},"doc://KKS.KKSPlayer/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://KKS.KKSPlayer/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)NSCoding","title":"Foundation.NSCoding"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniControllerPlayerView":{"url":"\/documentation\/kksplayer\/unicontrollerplayerview","abstract":[],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UniControllerPlayerView","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"UniControllerPlayerView","kind":"identifier"}],"title":"UniControllerPlayerView","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniControllerPlayerView"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView/exitFullscreen()":{"title":"exitFullscreen()","role":"symbol","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/exitFullscreen()","url":"\/documentation\/kksplayer\/uniplayerview\/exitfullscreen()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"exitFullscreen","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView/init(player:frame:playerViewConfig:)":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/init(player:frame:playerViewConfig:)","title":"init(player:frame:playerViewConfig:)","role":"symbol","url":"\/documentation\/kksplayer\/uniplayerview\/init(player:frame:playerviewconfig:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"player"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","text":"UniPlayer"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"frame"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"playerViewConfig"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:9KKSPlayer16PlayerViewConfigV","text":"PlayerViewConfig"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[{"text":"Creates a new instance of the PlayerView.","type":"text"}],"type":"topic"},"doc://KKS.KKSPlayer/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://KKS.KKSPlayer/objc(cs)UIView":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(cs)UIView","title":"UIView"},"doc://KKS.KKSPlayer/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://KKS.KKSPlayer/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSourceListener":{"url":"\/documentation\/kksplayer\/unisourcelistener","abstract":[],"kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UniSourceListener","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UniSourceListener"}],"title":"UniSourceListener","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceListener"},"doc://KKS.KKSPlayer/objc(pl)UIAppearance":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIAppearance","title":"UIKit.UIAppearance"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView/enterFullscreen()":{"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/enterFullscreen()","title":"enterFullscreen()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enterFullscreen","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[],"url":"\/documentation\/kksplayer\/uniplayerview\/enterfullscreen()"},"doc://KKS.KKSPlayer/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView/showsPlaybackControls":{"kind":"symbol","role":"symbol","title":"showsPlaybackControls","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/showsPlaybackControls","url":"\/documentation\/kksplayer\/uniplayerview\/showsplaybackcontrols","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showsPlaybackControls","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","abstract":[]},"doc://KKS.KKSPlayer/objc(pl)UIDynamicItem":{"title":"UIKit.UIDynamicItem","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIDynamicItem","type":"unresolvable"},"doc://KKS.KKSPlayer/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable"},"doc://KKS.KKSPlayer/objc(pl)UICoordinateSpace":{"title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UICoordinateSpace","type":"unresolvable"},"doc://KKS.KKSPlayer/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/KKS.KKSPlayer\/5UIKit23UITraitChangeObservableP","type":"unresolvable"},"doc://KKS.KKSPlayer/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIAppearanceContainer","type":"unresolvable"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView/UniSourceListener-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/UniSourceListener-Implementations","type":"topic","kind":"article","abstract":[],"url":"\/documentation\/kksplayer\/uniplayerview\/unisourcelistener-implementations","title":"UniSourceListener Implementations"},"doc://KKS.KKSPlayer/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/s8SendableP","title":"Swift.Sendable"},"doc://KKS.KKSPlayer/objc(pl)CALayerDelegate":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView/touchesEnded(_:with:)":{"role":"symbol","title":"touchesEnded(_:with:)","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/touchesEnded(_:with:)","url":"\/documentation\/kksplayer\/uniplayerview\/touchesended(_:with:)","type":"topic","navigatorTitle":[{"text":"touchesEnded:withEvent:","kind":"identifier"}],"abstract":[],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"touchesEnded"},{"kind":"text","text":"("},{"text":"Set","preciseIdentifier":"s:Sh","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITouch","text":"UITouch","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://KKS.KKSPlayer/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIAccessibilityIdentification","title":"UIKit.UIAccessibilityIdentification"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerListener":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"UniPlayerListener","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"UniPlayerListener"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener","type":"topic","url":"\/documentation\/kksplayer\/uniplayerlistener","title":"UniPlayerListener","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Defines listener methods for all events available for the Player"}]},"doc://KKS.KKSPlayer/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://KKS.KKSPlayer/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","role":"collection","url":"\/documentation\/kksplayer","kind":"symbol","title":"KKSPlayer","type":"topic"},"doc://KKS.KKSPlayer/objc(pl)UIFocusItem":{"title":"UIKit.UIFocusItem","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIFocusItem","type":"unresolvable"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView/isPictureInPicture":{"kind":"symbol","role":"symbol","title":"isPictureInPicture","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/isPictureInPicture","url":"\/documentation\/kksplayer\/uniplayerview\/ispictureinpicture","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isPictureInPicture","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","abstract":[{"text":"Returns true if player is currently in Picture-in-Picture (PiP) mode.","type":"text"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView/UniPlayerListener-Implementations":{"kind":"article","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/UniPlayerListener-Implementations","type":"topic","role":"collectionGroup","abstract":[],"title":"UniPlayerListener Implementations","url":"\/documentation\/kksplayer\/uniplayerview\/uniplayerlistener-implementations"},"doc://KKS.KKSPlayer/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView/fullscreenHandler":{"abstract":[],"url":"\/documentation\/kksplayer\/uniplayerview\/fullscreenhandler","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/fullscreenHandler","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"fullscreenHandler","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9KKSPlayer20UniFullscreenHandlerP","kind":"typeIdentifier","text":"UniFullscreenHandler"},{"text":"?","kind":"text"}],"title":"fullscreenHandler","type":"topic","kind":"symbol","role":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView/UniUserInterfaceEventHandler-Implementations":{"kind":"article","role":"collectionGroup","type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/UniUserInterfaceEventHandler-Implementations","title":"UniUserInterfaceEventHandler Implementations","url":"\/documentation\/kksplayer\/uniplayerview\/uniuserinterfaceeventhandler-implementations","abstract":[]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView/init(player:frame:)":{"kind":"symbol","role":"symbol","title":"init(player:frame:)","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/init(player:frame:)","url":"\/documentation\/kksplayer\/uniplayerview\/init(player:frame:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"player","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UniPlayer","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer"},{"text":", ","kind":"text"},{"text":"frame","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"text":")","kind":"text"}],"type":"topic","abstract":[{"text":"Creates a new instance of the PlayerView.","type":"text"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView/startPictureInPicture()":{"kind":"symbol","role":"symbol","title":"startPictureInPicture()","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/startPictureInPicture()","url":"\/documentation\/kksplayer\/uniplayerview\/startpictureinpicture()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"startPictureInPicture"},{"text":"()","kind":"text"}],"type":"topic","abstract":[{"text":"Starts Picture in Picture, if possible.","type":"text"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView/player(_:didReceiveOnReadyEvent:)":{"title":"player(_:didReceiveOnReadyEvent:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"player","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UniPlayer","kind":"typeIdentifier","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer"},{"text":", ","kind":"text"},{"text":"didReceiveOnReadyEvent","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:9KKSPlayer8UniEventP","text":"UniEvent","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"text":"Called when the player receives an ","type":"text"},{"type":"codeVoice","code":"UniEvent"},{"type":"text","text":" on the ready event."}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/player(_:didReceiveOnReadyEvent:)","type":"topic","kind":"symbol","url":"\/documentation\/kksplayer\/uniplayerview\/player(_:didreceiveonreadyevent:)","role":"symbol"},"doc://KKS.KKSPlayer/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/KKS.KKSPlayer\/SQ","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"UniPlayerView"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"UniPlayerView","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"UniPlayerView","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/touchesEnded(_:with:)"],"title":"Instance Methods"}]},{"value":[{"kind":"relationships","identifiers":["doc:\/\/KKS.KKSPlayer\/objc(cs)UIView"],"title":"Inherits From","type":"inheritsFrom"},{"type":"inheritedBy","kind":"relationships","title":"Inherited By","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniControllerPlayerView"]}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniPlayerView"},{"kind":"text","text":" : "},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerView\/title","value":"UniPlayerView"},{"value":[{"kind":"identifier","text":"UniPlayerView"}],"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerView\/fragments","op":"replace"},{"value":"UniControllerPlayerView","op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniControllerPlayerView\/title"},{"op":"replace","value":[{"text":"UniControllerPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniControllerPlayerView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerView~1touchesEnded(_:with:)\/title","value":"touchesEnded:withEvent:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"touchesEnded:withEvent:","kind":"identifier"}],"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerView~1touchesEnded(_:with:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}