{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer"},"sections":[],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/KKS.KKSPlayer\/objc(cs)NSObject"],"title":"Inherits From"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/KKS.KKSPlayer\/objc(pl)AVAssetResourceLoaderDelegate","doc:\/\/KKS.KKSPlayer\/objc(pl)NSObject","doc:\/\/KKS.KKSPlayer\/s7CVarArgP","doc:\/\/KKS.KKSPlayer\/s28CustomDebugStringConvertibleP","doc:\/\/KKS.KKSPlayer\/s23CustomStringConvertibleP","doc:\/\/KKS.KKSPlayer\/SQ","doc:\/\/KKS.KKSPlayer\/SH","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceListener"]}],"topicSections":[{"identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/audio","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/availableAudio","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/availableSubtitles","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/availableVideoQualities","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/currentTime","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/duration","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/isLive","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/isLoopEnabled","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/isMuted","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/isPlaying","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/maxSelectableBitrate","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/maxTimeShift","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/playbackSpeed","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/playlist","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/pseEnabled","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/source","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/subtitle","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/timeShift","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/videoQuality","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/volume"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/add(listener:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/destroy()","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/forward(_:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/load(source:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/load(sourceConfig:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/pause()","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/play()","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/register(_:)-10xih","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/register(_:)-66ysq","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/remove(listener:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/rewind(_:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/seek(to:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/setAudio(track:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/setSubtitle(track:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/unload()","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/unregisterPlayerLayer(_:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/AVAssetResourceLoaderDelegate-Implementations","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/UniSourceListener-Implementations"],"generated":true}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"An object that provides the interface to control the player’s transport behavior.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kksplayer\/uniplayer"]},{"paths":["\/documentation\/kksplayer\/uniplayer"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@KKSPlayer@objc(cs)UniPlayer","role":"symbol","roleHeading":"Class","navigatorTitle":[{"text":"UniPlayer","kind":"identifier"}],"title":"UniPlayer","symbolKind":"class","modules":[{"name":"BVPlayer"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UniPlayer","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniPlayer"}]}]}],"kind":"symbol","references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/availableSubtitles":{"abstract":[{"type":"text","text":"Returns an array containing SubtitleTrack objects for all available subtitle tracks."}],"role":"symbol","type":"topic","title":"availableSubtitles","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/availableSubtitles","kind":"symbol","url":"\/documentation\/kksplayer\/uniplayer\/availablesubtitles","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"availableSubtitles"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniSubtitleTrack","text":"UniSubtitleTrack","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/isMuted":{"title":"isMuted","abstract":[{"text":"A Boolean value that indicates whether the audio output of the player is muted.","type":"text"}],"role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/isMuted","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isMuted","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/kksplayer\/uniplayer\/ismuted","type":"topic","kind":"symbol"},"doc://KKS.KKSPlayer/objc(pl)AVAssetResourceLoaderDelegate":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)AVAssetResourceLoaderDelegate","title":"AVAssetResourceLoaderDelegate"},"doc://KKS.KKSPlayer/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/UniSourceListener-Implementations":{"abstract":[],"role":"collectionGroup","type":"topic","title":"UniSourceListener Implementations","kind":"article","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/UniSourceListener-Implementations","url":"\/documentation\/kksplayer\/uniplayer\/unisourcelistener-implementations"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/playbackSpeed":{"kind":"symbol","url":"\/documentation\/kksplayer\/uniplayer\/playbackspeed","title":"playbackSpeed","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/playbackSpeed","abstract":[{"type":"text","text":"Get\/set the playback speed of the player."},{"text":" ","type":"text"},{"text":"Fast forward, slow motion and reverse playback are supported.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playbackSpeed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/timeShift":{"role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/timeShift","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"timeShift"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"}],"title":"timeShift","type":"topic","abstract":[{"type":"text","text":"When set, shifts the time to the given offset in seconds from the live edge."},{"type":"text","text":" "},{"text":"Has to be within #maxTimeShift (which is a negative value) and 0. Only works in live streams.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The offset can be positive and is then interpreted as a UNIX timestamp in seconds."},{"type":"text","text":" "},{"type":"text","text":"The value has to be within the timeShift window, as specified by Player#maxTimeShift."}],"url":"\/documentation\/kksplayer\/uniplayer\/timeshift"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/videoQuality":{"abstract":[{"text":"Returns the currently selected video quality.","type":"text"}],"role":"symbol","type":"topic","title":"videoQuality","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/videoQuality","kind":"symbol","url":"\/documentation\/kksplayer\/uniplayer\/videoquality","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:9KKSPlayer15UniVideoQualityV","text":"UniVideoQuality"},{"kind":"text","text":"?"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/pause()":{"abstract":[{"type":"text","text":"Pauses the video if it is playing. Has no effect if the player is already paused."},{"type":"text","text":" "},{"type":"text","text":"Calling this method is the same as setting the rate to 0.0."}],"role":"symbol","type":"topic","title":"pause()","kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/pause()","url":"\/documentation\/kksplayer\/uniplayer\/pause()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"pause","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/pseEnabled":{"abstract":[],"role":"symbol","type":"topic","title":"pseEnabled","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/pseEnabled","kind":"symbol","url":"\/documentation\/kksplayer\/uniplayer\/pseenabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pseEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/unload()":{"abstract":[{"type":"text","text":"Unloads all Sources in the player."}],"role":"symbol","type":"topic","title":"unload()","kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/unload()","url":"\/documentation\/kksplayer\/uniplayer\/unload()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"unload","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://KKS.KKSPlayer/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/remove(listener:)":{"title":"remove(listener:)","type":"topic","role":"symbol","abstract":[{"text":"Removes a UniPlayerEvent listener.","type":"text"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/remove(listener:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"remove"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:9KKSPlayer17UniPlayerListenerP","text":"UniPlayerListener","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/kksplayer\/uniplayer\/remove(listener:)"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSourceListener":{"role":"symbol","title":"UniSourceListener","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceListener","type":"topic","navigatorTitle":[{"text":"UniSourceListener","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/kksplayer\/unisourcelistener","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"UniSourceListener","kind":"identifier"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/forward(_:)":{"abstract":[{"text":"Forward to the given playback time specified by the parameter time in seconds.","type":"text"}],"role":"symbol","type":"topic","title":"forward(_:)","kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/forward(_:)","url":"\/documentation\/kksplayer\/uniplayer\/forward(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"forward"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":")"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/load(source:)":{"abstract":[{"type":"text","text":"Loads a new Source into the player."}],"role":"symbol","type":"topic","title":"load(source:)","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/load(source:)","kind":"symbol","url":"\/documentation\/kksplayer\/uniplayer\/load(source:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"load"},{"kind":"text","text":"("},{"text":"source","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UniSource","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniSource","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/register(_:)-66ysq":{"title":"register(_:)","kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/register(_:)-66ysq","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"register"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)AVPlayerLayer","kind":"typeIdentifier","text":"AVPlayerLayer"},{"kind":"text","text":")"}],"type":"topic","abstract":[{"text":"Registers the internal AVPlayer instance to an existing AVPlayerLayer.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Calling this method has no effect"},{"type":"text","text":" "},{"type":"text","text":"if the AVPlayer instance is already registered on the given playerLayer."}],"url":"\/documentation\/kksplayer\/uniplayer\/register(_:)-66ysq","role":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/availableVideoQualities":{"abstract":[{"type":"text","text":"Returns an array containing all available video qualities the player can adapt between."}],"role":"symbol","type":"topic","title":"availableVideoQualities","kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/availableVideoQualities","url":"\/documentation\/kksplayer\/uniplayer\/availablevideoqualities","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"availableVideoQualities","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:9KKSPlayer15UniVideoQualityV","kind":"typeIdentifier","text":"UniVideoQuality"},{"kind":"text","text":"]"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/load(sourceConfig:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"load"},{"text":"(","kind":"text"},{"text":"sourceConfig","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UniSourceConfig","preciseIdentifier":"s:9KKSPlayer15UniSourceConfigC","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","title":"load(sourceConfig:)","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/load(sourceConfig:)","abstract":[{"type":"text","text":"Loads a new Source based on the provided SourceConfig into the player."}],"role":"symbol","url":"\/documentation\/kksplayer\/uniplayer\/load(sourceconfig:)"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/rewind(_:)":{"abstract":[{"type":"text","text":"Rewind to the given playback time specified by the parameter time in seconds."}],"role":"symbol","type":"topic","title":"rewind(_:)","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/rewind(_:)","kind":"symbol","url":"\/documentation\/kksplayer\/uniplayer\/rewind(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"rewind","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/register(_:)-10xih":{"title":"register(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"register","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","url":"\/documentation\/kksplayer\/uniplayer\/register(_:)-10xih","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/register(_:)-10xih","role":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/currentTime":{"title":"currentTime","type":"topic","role":"symbol","abstract":[{"text":"Returns the current playback time in seconds.","type":"text"},{"type":"text","text":" "},{"text":"For VoD streams the returned time ranges between 0 and the duration of the asset.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"For live streams a Unix timestamp denoting the current playback position is returned."}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/currentTime","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"currentTime","kind":"identifier"},{"kind":"text","text":": "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"kind":"symbol","url":"\/documentation\/kksplayer\/uniplayer\/currenttime"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/setAudio(track:)":{"abstract":[{"type":"text","text":"Sets the audio track to the ID specified by audioTrackID. A"},{"text":" ","type":"text"},{"text":"list can be retrieved by calling availableAudio.","type":"text"}],"role":"symbol","type":"topic","title":"setAudio(track:)","kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/setAudio(track:)","url":"\/documentation\/kksplayer\/uniplayer\/setaudio(track:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAudio"},{"kind":"text","text":"("},{"kind":"externalParam","text":"track"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","abstract":[{"text":"BlendVision One iOS Player SDK","type":"text"}],"title":"BVPlayer","url":"\/documentation\/kksplayer","kind":"symbol","role":"collection"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer":{"url":"\/documentation\/kksplayer\/uniplayer","title":"UniPlayer","abstract":[{"text":"An object that provides the interface to control the player’s transport behavior.","type":"text"}],"role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer","navigatorTitle":[{"kind":"identifier","text":"UniPlayer"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UniPlayer","kind":"identifier"}],"kind":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/duration":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"}],"kind":"symbol","role":"symbol","type":"topic","title":"duration","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/duration","abstract":[{"type":"text","text":"Returns the total duration in seconds of the current video"},{"text":" ","type":"text"},{"type":"text","text":"or INFINITY if it’s a live stream."}],"url":"\/documentation\/kksplayer\/uniplayer\/duration"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/maxSelectableBitrate":{"abstract":[{"type":"text","text":"The upper bitrate boundary is in bits per second for network bandwidth consumption of the currently played source."},{"type":"text","text":" "},{"type":"text","text":"Can be set to 0 for auto profile change."},{"type":"text","text":" "},{"type":"text","text":"The value set here is only valid for the currently played source and will not be carried over to subsequently loaded sources."},{"text":" ","type":"text"},{"type":"text","text":"The default value is 0."}],"role":"symbol","type":"topic","title":"maxSelectableBitrate","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/maxSelectableBitrate","kind":"symbol","url":"\/documentation\/kksplayer\/uniplayer\/maxselectablebitrate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxSelectableBitrate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/setSubtitle(track:)":{"abstract":[{"text":"Sets the subtitle track to the ID specified by trackID","type":"text"},{"type":"text","text":" "},{"text":"Using nil as ID disables subtitles.","type":"text"}],"role":"symbol","type":"topic","title":"setSubtitle(track:)","kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/setSubtitle(track:)","url":"\/documentation\/kksplayer\/uniplayer\/setsubtitle(track:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setSubtitle"},{"kind":"text","text":"("},{"kind":"externalParam","text":"track"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?)","kind":"text"}]},"doc://KKS.KKSPlayer/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/KKS.KKSPlayer\/SH"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/playlist":{"abstract":[],"role":"symbol","type":"topic","title":"playlist","kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/playlist","url":"\/documentation\/kksplayer\/uniplayer\/playlist","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"playlist"},{"kind":"text","text":": "},{"preciseIdentifier":"s:9KKSPlayer11UniPlaylistC","kind":"typeIdentifier","text":"UniPlaylist"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/destroy()":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"destroy","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/destroy()","url":"\/documentation\/kksplayer\/uniplayer\/destroy()","abstract":[{"text":"Destroys the player and releases all allocated resources.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The player instance must not be used after calling this method."}],"type":"topic","title":"destroy()"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/maxTimeShift":{"abstract":[{"text":"Returns the limit in seconds for time shift. Is either negative or 0.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Is applicable for live streams only."}],"role":"symbol","type":"topic","title":"maxTimeShift","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/maxTimeShift","kind":"symbol","url":"\/documentation\/kksplayer\/uniplayer\/maxtimeshift","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maxTimeShift"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"}]},"doc://KKS.KKSPlayer/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(cs)NSObject","title":"NSObject"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/seek(to:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"seek","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"seek(to:)","abstract":[{"type":"text","text":"Seeks to the given playback time specified by the parameter time in seconds."},{"type":"text","text":" "},{"text":"Must not be greater than the total duration of the video.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Has no effect when watching a live stream as seeking is not possible."}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/seek(to:)","type":"topic","url":"\/documentation\/kksplayer\/uniplayer\/seek(to:)","kind":"symbol","role":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/subtitle":{"abstract":[{"type":"text","text":"Returns the currently used SubtitleTrack."}],"type":"topic","title":"subtitle","url":"\/documentation\/kksplayer\/uniplayer\/subtitle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"subtitle","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UniSubtitleTrack","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniSubtitleTrack"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/subtitle","role":"symbol","kind":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/isPlaying":{"type":"topic","abstract":[{"text":"Returns true if the player is currently playing, i.e. has started and is not paused.","type":"text"}],"url":"\/documentation\/kksplayer\/uniplayer\/isplaying","kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/isPlaying","title":"isPlaying","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPlaying"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/play()":{"abstract":[{"text":"Starts playback or resumes after being paused. Has no effect if the player is already playing.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Calling this method is the same as setting the rate to 1.0."}],"role":"symbol","type":"topic","title":"play()","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/play()","kind":"symbol","url":"\/documentation\/kksplayer\/uniplayer\/play()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"play"},{"kind":"text","text":"()"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/audio":{"abstract":[{"type":"text","text":"Returns the currently used audio track."},{"type":"text","text":" "},{"type":"text","text":"Before the Source finished loading this property will always return nil."}],"role":"symbol","type":"topic","title":"audio","kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/audio","url":"\/documentation\/kksplayer\/uniplayer\/audio","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"audio","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniAudioTrack","kind":"typeIdentifier","text":"UniAudioTrack"},{"text":"?","kind":"text"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/isLive":{"abstract":[{"text":"Returns true if the displayed video is a live stream.","type":"text"},{"text":" ","type":"text"},{"text":"The value of duration may remain indefinite for live streams.","type":"text"}],"role":"symbol","type":"topic","title":"isLive","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/isLive","kind":"symbol","url":"\/documentation\/kksplayer\/uniplayer\/islive","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isLive","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/volume":{"abstract":[{"type":"text","text":"The audio playback volume for the player."},{"type":"text","text":" "},{"type":"text","text":"A value of 0.0 indicates silence; a value of 1.0 (the default) indicates full audio volume for the player instance."}],"role":"symbol","type":"topic","title":"volume","kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/volume","url":"\/documentation\/kksplayer\/uniplayer\/volume","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"volume","kind":"identifier"},{"kind":"text","text":": "},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/AVAssetResourceLoaderDelegate-Implementations":{"abstract":[],"role":"collectionGroup","type":"topic","title":"AVAssetResourceLoaderDelegate Implementations","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/AVAssetResourceLoaderDelegate-Implementations","kind":"article","url":"\/documentation\/kksplayer\/uniplayer\/avassetresourceloaderdelegate-implementations"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/availableAudio":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/availableAudio","title":"availableAudio","role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/kksplayer\/uniplayer\/availableaudio","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"availableAudio","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniAudioTrack","text":"UniAudioTrack","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"abstract":[{"text":"Returns an array containing all available audio tracks.","type":"text"}]},"doc://KKS.KKSPlayer/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/add(listener:)":{"abstract":[{"text":"Adds a UniPlayerEvent listener.","type":"text"}],"role":"symbol","type":"topic","title":"add(listener:)","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/add(listener:)","kind":"symbol","url":"\/documentation\/kksplayer\/uniplayer\/add(listener:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"add","kind":"identifier"},{"kind":"text","text":"("},{"text":"listener","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:9KKSPlayer17UniPlayerListenerP","text":"UniPlayerListener"},{"kind":"text","text":")"}]},"doc://KKS.KKSPlayer/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/SQ"},"doc://KKS.KKSPlayer/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/s7CVarArgP"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/isLoopEnabled":{"abstract":[{"type":"text","text":"A Boolean value indicating whether video looping is enabled."}],"role":"symbol","type":"topic","title":"isLoopEnabled","kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/isLoopEnabled","url":"\/documentation\/kksplayer\/uniplayer\/isloopenabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isLoopEnabled","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/source":{"role":"symbol","title":"source","kind":"symbol","url":"\/documentation\/kksplayer\/uniplayer\/source","abstract":[{"text":"Returns the currently active source or null if no source is active.","type":"text"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/source","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"source","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UniSource","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniSource"},{"text":"?","kind":"text"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/unregisterPlayerLayer(_:)":{"abstract":[{"text":"Unregisters the internal AVPlayer instance from an existing AVPlayerLayer.","type":"text"}],"role":"symbol","type":"topic","title":"unregisterPlayerLayer(_:)","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/unregisterPlayerLayer(_:)","kind":"symbol","url":"\/documentation\/kksplayer\/uniplayer\/unregisterplayerlayer(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unregisterPlayerLayer"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)AVPlayerLayer","kind":"typeIdentifier","text":"AVPlayerLayer"},{"text":")","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"UniPlayer","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"UniPlayer"}]},{"op":"replace","value":[{"kind":"identifier","text":"UniPlayer"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Default Implementations","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/AVAssetResourceLoaderDelegate-Implementations"],"generated":true}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/KKS.KKSPlayer\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/KKS.KKSPlayer\/objc(pl)AVAssetResourceLoaderDelegate"],"title":"Conforms To"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniPlayer"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/title","value":"UniPlayer"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/fragments","op":"replace","value":[{"kind":"identifier","text":"UniPlayer"}]}]}]}