{"sections":[],"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer"]]},"abstract":[{"type":"text","text":"Defines listener methods for all events available for the Player"}],"metadata":{"title":"UniPlayerListener","navigatorTitle":[{"text":"UniPlayerListener","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniPlayerListener"}],"externalID":"s:9KKSPlayer17UniPlayerListenerP","modules":[{"name":"KKSPlayer"}],"role":"symbol","roleHeading":"Protocol","symbolKind":"protocol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kksplayer\/uniplayerlistener"]}],"kind":"symbol","topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveAudioVolumeChangedEvent:)-81qq9","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveErrorEvent:)-5p989","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveLoadedTimeChangedEvent:)-89ljk","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveLoopChangedEvent:)-5mma9","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveMutedEvent:)-16zvb","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveOnAudioChangedEvent:)-3i9de","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveOnEvent:)-2n59h","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveOnPausedEvent:)-55auq","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveOnPlaybackFinishedEvent:)-9pho8","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveOnPlayingEvent:)-3v4sh","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveOnReadyEvent:)-697ty","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveOnSeekEvent:)-7gb9j","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveOnSeekedEvent:)-13yfq","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveOnSourceLoadEvent:)-6hh9z","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveOnSourceLoadedEvent:)-hs20","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveOnStallEndedEvent:)-6tz7c","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveOnStallStartedEvent:)-8daer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveOnSubtitleChangedEvent:)-5wx8o","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveOnTimeChangedEvent:)-30206","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveOnVideoQualityChangedEvent:)-4p0pc","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceivePlaybackSpeedChangedEvent:)-4676i","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveSourceErrorEvent:)-1tc7k","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveSourceUnloadEvent:)-w11","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveSourceUnloadedEvent:)-7oit5","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveTimeShiftEvent:)-5a093","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveTimeShiftedEvent:)-decc","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveUnmutedEvent:)-4unf2"]}],"relationshipsSections":[{"identifiers":["doc:\/\/KKS.KKSPlayer\/objc(pl)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniControllerPlayerView","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView"],"title":"Conforming Types","type":"conformingTypes"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniPlayerListener"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener"},"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerListener/player(_:didReceiveMutedEvent:)-16zvb":{"role":"symbol","url":"\/documentation\/kksplayer\/uniplayerlistener\/player(_:didreceivemutedevent:)-16zvb","defaultImplementations":1,"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Called when the player receives an "},{"type":"codeVoice","code":"UniEvent"},{"text":" indicating the audio is muted.","type":"text"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveMutedEvent:)-16zvb","required":true,"title":"player(_:didReceiveMutedEvent:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"player"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","text":"UniPlayer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didReceiveMutedEvent","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:9KKSPlayer8UniEventP","text":"UniEvent"},{"text":")","kind":"text"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniPlayerView"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UniPlayerView"}],"url":"\/documentation\/kksplayer\/uniplayerview","type":"topic","abstract":[],"title":"UniPlayerView"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerListener/player(_:didReceiveOnStallStartedEvent:)-8daer":{"url":"\/documentation\/kksplayer\/uniplayerlistener\/player(_:didreceiveonstallstartedevent:)-8daer","abstract":[{"text":"Called when the player receives an ","type":"text"},{"code":"UniEvent","type":"codeVoice"},{"type":"text","text":" indicating a stall has started."}],"kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveOnStallStartedEvent:)-8daer","defaultImplementations":1,"role":"symbol","title":"player(_:didReceiveOnStallStartedEvent:)","type":"topic","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"player","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UniPlayer","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer"},{"text":", ","kind":"text"},{"text":"didReceiveOnStallStartedEvent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UniEvent","preciseIdentifier":"s:9KKSPlayer8UniEventP","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerListener/player(_:didReceiveOnReadyEvent:)-697ty":{"abstract":[{"text":"Called when the player receives an ","type":"text"},{"code":"UniEvent","type":"codeVoice"},{"text":" on the ready event.","type":"text"}],"url":"\/documentation\/kksplayer\/uniplayerlistener\/player(_:didreceiveonreadyevent:)-697ty","required":true,"title":"player(_:didReceiveOnReadyEvent:)","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"player","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","kind":"typeIdentifier","text":"UniPlayer"},{"text":", ","kind":"text"},{"text":"didReceiveOnReadyEvent","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UniEvent","preciseIdentifier":"s:9KKSPlayer8UniEventP"},{"kind":"text","text":")"}],"defaultImplementations":1,"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveOnReadyEvent:)-697ty"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerListener/player(_:didReceivePlaybackSpeedChangedEvent:)-4676i":{"role":"symbol","url":"\/documentation\/kksplayer\/uniplayerlistener\/player(_:didreceiveplaybackspeedchangedevent:)-4676i","defaultImplementations":1,"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Called when the player receives an "},{"type":"codeVoice","code":"UniPlaybackSpeedChangedEvent"},{"type":"text","text":" indicating the playback speed has changed."}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceivePlaybackSpeedChangedEvent:)-4676i","required":true,"title":"player(_:didReceivePlaybackSpeedChangedEvent:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"player"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","text":"UniPlayer"},{"text":", ","kind":"text"},{"text":"didReceivePlaybackSpeedChangedEvent","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:9KKSPlayer28UniPlaybackSpeedChangedEventC","text":"UniPlaybackSpeedChangedEvent"},{"text":")","kind":"text"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerListener/player(_:didReceiveOnSourceLoadEvent:)-6hh9z":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"player","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UniPlayer","kind":"typeIdentifier","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveOnSourceLoadEvent"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UniSourceLoadEvent","preciseIdentifier":"s:9KKSPlayer18UniSourceLoadEventC"},{"kind":"text","text":")"}],"defaultImplementations":1,"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveOnSourceLoadEvent:)-6hh9z","type":"topic","url":"\/documentation\/kksplayer\/uniplayerlistener\/player(_:didreceiveonsourceloadevent:)-6hh9z","required":true,"title":"player(_:didReceiveOnSourceLoadEvent:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Called when the player receives an "},{"code":"UniSourceLoadEvent","type":"codeVoice"},{"type":"text","text":" indicating a new media source is being loaded."}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerListener/player(_:didReceiveOnEvent:)-2n59h":{"kind":"symbol","type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveOnEvent:)-2n59h","abstract":[{"type":"text","text":"Called when the player receives an "},{"type":"codeVoice","code":"UniEvent"},{"type":"text","text":" on any event."}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"player","kind":"identifier"},{"kind":"text","text":"("},{"text":"UniPlayer","kind":"typeIdentifier","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer"},{"text":", ","kind":"text"},{"text":"didReceiveOnEvent","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:9KKSPlayer8UniEventP","text":"UniEvent"},{"kind":"text","text":")"}],"defaultImplementations":1,"required":true,"title":"player(_:didReceiveOnEvent:)","url":"\/documentation\/kksplayer\/uniplayerlistener\/player(_:didreceiveonevent:)-2n59h"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerListener/player(_:didReceiveOnAudioChangedEvent:)-3i9de":{"title":"player(_:didReceiveOnAudioChangedEvent:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"player","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","kind":"typeIdentifier","text":"UniPlayer"},{"kind":"text","text":", "},{"text":"didReceiveOnAudioChangedEvent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UniAudioChangedEvent","kind":"typeIdentifier","preciseIdentifier":"s:9KKSPlayer20UniAudioChangedEventC"},{"kind":"text","text":")"}],"defaultImplementations":1,"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveOnAudioChangedEvent:)-3i9de","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Called when the player receives an "},{"type":"codeVoice","code":"UniAudioChangedEvent"},{"type":"text","text":" indicating the audio track has changed."}],"url":"\/documentation\/kksplayer\/uniplayerlistener\/player(_:didreceiveonaudiochangedevent:)-3i9de","role":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerListener/player(_:didReceiveOnSubtitleChangedEvent:)-5wx8o":{"type":"topic","kind":"symbol","title":"player(_:didReceiveOnSubtitleChangedEvent:)","role":"symbol","defaultImplementations":1,"url":"\/documentation\/kksplayer\/uniplayerlistener\/player(_:didreceiveonsubtitlechangedevent:)-5wx8o","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveOnSubtitleChangedEvent:)-5wx8o","abstract":[{"type":"text","text":"Called when the player receives an "},{"code":"UniSubtitleChangedEvent","type":"codeVoice"},{"type":"text","text":" indicating the subtitle track has changed."}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"player","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","text":"UniPlayer"},{"text":", ","kind":"text"},{"text":"didReceiveOnSubtitleChangedEvent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UniSubtitleChangedEvent","kind":"typeIdentifier","preciseIdentifier":"s:9KKSPlayer23UniSubtitleChangedEventC"},{"kind":"text","text":")"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerListener":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"UniPlayerListener","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"UniPlayerListener"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener","type":"topic","url":"\/documentation\/kksplayer\/uniplayerlistener","title":"UniPlayerListener","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Defines listener methods for all events available for the Player"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerListener/player(_:didReceiveOnTimeChangedEvent:)-30206":{"defaultImplementations":1,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"player"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","text":"UniPlayer"},{"text":", ","kind":"text"},{"text":"didReceiveOnTimeChangedEvent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UniTimeChangedEvent","preciseIdentifier":"s:9KKSPlayer19UniTimeChangedEventC","kind":"typeIdentifier"},{"text":")","kind":"text"}],"required":true,"role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveOnTimeChangedEvent:)-30206","type":"topic","title":"player(_:didReceiveOnTimeChangedEvent:)","kind":"symbol","abstract":[{"type":"text","text":"Called when the player receives an "},{"type":"codeVoice","code":"UniTimeChangedEvent"},{"text":" indicating the time has changed.","type":"text"}],"url":"\/documentation\/kksplayer\/uniplayerlistener\/player(_:didreceiveontimechangedevent:)-30206"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerListener/player(_:didReceiveOnVideoQualityChangedEvent:)-4p0pc":{"title":"player(_:didReceiveOnVideoQualityChangedEvent:)","url":"\/documentation\/kksplayer\/uniplayerlistener\/player(_:didreceiveonvideoqualitychangedevent:)-4p0pc","abstract":[{"text":"Called when the player receives an ","type":"text"},{"type":"codeVoice","code":"UniVideoPlaybackQualityChangedEvent"},{"text":" indicating the video playback quality has changed.","type":"text"}],"role":"symbol","kind":"symbol","defaultImplementations":1,"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveOnVideoQualityChangedEvent:)-4p0pc","type":"topic","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"player"},{"kind":"text","text":"("},{"text":"UniPlayer","kind":"typeIdentifier","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceiveOnVideoQualityChangedEvent"},{"text":": ","kind":"text"},{"text":"UniVideoPlaybackQualityChangedEvent","preciseIdentifier":"s:9KKSPlayer35UniVideoPlaybackQualityChangedEventC","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniControllerPlayerView":{"url":"\/documentation\/kksplayer\/unicontrollerplayerview","abstract":[],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UniControllerPlayerView","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"UniControllerPlayerView","kind":"identifier"}],"title":"UniControllerPlayerView","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniControllerPlayerView"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerListener/player(_:didReceiveOnStallEndedEvent:)-6tz7c":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveOnStallEndedEvent:)-6tz7c","kind":"symbol","abstract":[{"text":"Called when the player receives an ","type":"text"},{"type":"codeVoice","code":"UniEvent"},{"text":" indicating a stall has ended.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"player","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UniPlayer","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didReceiveOnStallEndedEvent","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UniEvent","preciseIdentifier":"s:9KKSPlayer8UniEventP"},{"text":")","kind":"text"}],"type":"topic","title":"player(_:didReceiveOnStallEndedEvent:)","required":true,"defaultImplementations":1,"url":"\/documentation\/kksplayer\/uniplayerlistener\/player(_:didreceiveonstallendedevent:)-6tz7c"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerListener/player(_:didReceiveSourceUnloadEvent:)-w11":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveSourceUnloadEvent:)-w11","required":true,"title":"player(_:didReceiveSourceUnloadEvent:)","role":"symbol","url":"\/documentation\/kksplayer\/uniplayerlistener\/player(_:didreceivesourceunloadevent:)-w11","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"player"},{"kind":"text","text":"("},{"text":"UniPlayer","kind":"typeIdentifier","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer"},{"kind":"text","text":", "},{"text":"didReceiveSourceUnloadEvent","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UniSourceUnloadEvent","kind":"typeIdentifier","preciseIdentifier":"s:9KKSPlayer20UniSourceUnloadEventC"},{"kind":"text","text":")"}],"defaultImplementations":1,"kind":"symbol","abstract":[{"text":"Called when the player receives an ","type":"text"},{"code":"UniSourceUnloadEvent","type":"codeVoice"},{"type":"text","text":" indicating a media source is being unloaded."}],"type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerListener/player(_:didReceiveLoopChangedEvent:)-5mma9":{"role":"symbol","url":"\/documentation\/kksplayer\/uniplayerlistener\/player(_:didreceiveloopchangedevent:)-5mma9","defaultImplementations":1,"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Called when the player receives an "},{"type":"codeVoice","code":"UniLoopChangedLogEvent"},{"text":" indicating the loop has changed.","type":"text"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveLoopChangedEvent:)-5mma9","required":true,"title":"player(_:didReceiveLoopChangedEvent:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"player","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","kind":"typeIdentifier","text":"UniPlayer"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceiveLoopChangedEvent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:9KKSPlayer19UniLoopChangedEventC","text":"UniLoopChangedEvent"},{"kind":"text","text":")"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerListener/player(_:didReceiveAudioVolumeChangedEvent:)-81qq9":{"abstract":[{"text":"Called when the player receives an ","type":"text"},{"type":"codeVoice","code":"UniAudioVolumeChangedEvent"},{"text":" indicating the audio volume has changed.","type":"text"}],"required":true,"title":"player(_:didReceiveAudioVolumeChangedEvent:)","role":"symbol","type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveAudioVolumeChangedEvent:)-81qq9","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"player"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","text":"UniPlayer"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceiveAudioVolumeChangedEvent"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UniAudioVolumeChangedEvent","preciseIdentifier":"s:9KKSPlayer26UniAudioVolumeChangedEventC"},{"text":")","kind":"text"}],"url":"\/documentation\/kksplayer\/uniplayerlistener\/player(_:didreceiveaudiovolumechangedevent:)-81qq9","kind":"symbol","defaultImplementations":1},"doc://KKS.KKSPlayer/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerListener/player(_:didReceiveTimeShiftedEvent:)-decc":{"title":"player(_:didReceiveTimeShiftedEvent:)","url":"\/documentation\/kksplayer\/uniplayerlistener\/player(_:didreceivetimeshiftedevent:)-decc","abstract":[{"type":"text","text":"Called when the player receives an "},{"type":"codeVoice","code":"UniEvent"},{"text":" indicating a time shift operation has completed.","type":"text"}],"required":true,"role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveTimeShiftedEvent:)-decc","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"player"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","text":"UniPlayer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceiveTimeShiftedEvent"},{"kind":"text","text":": "},{"preciseIdentifier":"s:9KKSPlayer8UniEventP","text":"UniEvent","kind":"typeIdentifier"},{"text":")","kind":"text"}],"defaultImplementations":1,"type":"topic","kind":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerListener/player(_:didReceiveOnPlaybackFinishedEvent:)-9pho8":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveOnPlaybackFinishedEvent:)-9pho8","title":"player(_:didReceiveOnPlaybackFinishedEvent:)","role":"symbol","defaultImplementations":1,"required":true,"url":"\/documentation\/kksplayer\/uniplayerlistener\/player(_:didreceiveonplaybackfinishedevent:)-9pho8","abstract":[{"type":"text","text":"Called when the player receives an "},{"code":"UniEvent","type":"codeVoice"},{"type":"text","text":" indicating playback has finished."}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"player"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","text":"UniPlayer","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didReceiveOnPlaybackFinishedEvent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UniEvent","preciseIdentifier":"s:9KKSPlayer8UniEventP","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerListener/player(_:didReceiveOnSeekEvent:)-7gb9j":{"abstract":[{"text":"Called when the player receives an ","type":"text"},{"type":"codeVoice","code":"UniSeekEvent"},{"text":" indicating a seek operation.","type":"text"}],"required":true,"title":"player(_:didReceiveOnSeekEvent:)","role":"symbol","type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveOnSeekEvent:)-7gb9j","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"player"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","text":"UniPlayer"},{"text":", ","kind":"text"},{"text":"didReceiveOnSeekEvent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UniSeekEvent","kind":"typeIdentifier","preciseIdentifier":"s:9KKSPlayer12UniSeekEventC"},{"text":")","kind":"text"}],"url":"\/documentation\/kksplayer\/uniplayerlistener\/player(_:didreceiveonseekevent:)-7gb9j","kind":"symbol","defaultImplementations":1},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","role":"collection","url":"\/documentation\/kksplayer","kind":"symbol","title":"KKSPlayer","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerListener/player(_:didReceiveErrorEvent:)-5p989":{"abstract":[{"text":"Called when the player receives an ","type":"text"},{"type":"codeVoice","code":"UniPlayerErrorEvent"},{"text":" indicating an error occurred with the player.","type":"text"}],"required":true,"title":"player(_:didReceiveErrorEvent:)","role":"symbol","type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveErrorEvent:)-5p989","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"player"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","text":"UniPlayer"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceiveErrorEvent"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UniPlayerErrorEvent","preciseIdentifier":"s:9KKSPlayer19UniPlayerErrorEventC"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/kksplayer\/uniplayerlistener\/player(_:didreceiveerrorevent:)-5p989","defaultImplementations":1},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerListener/player(_:didReceiveOnPlayingEvent:)-3v4sh":{"abstract":[{"text":"Called when the player receives an ","type":"text"},{"type":"codeVoice","code":"UniEvent"},{"text":" on the playing event.","type":"text"}],"title":"player(_:didReceiveOnPlayingEvent:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"player","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UniPlayer","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceiveOnPlayingEvent"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:9KKSPlayer8UniEventP","text":"UniEvent"},{"kind":"text","text":")"}],"url":"\/documentation\/kksplayer\/uniplayerlistener\/player(_:didreceiveonplayingevent:)-3v4sh","kind":"symbol","type":"topic","required":true,"role":"symbol","defaultImplementations":1,"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveOnPlayingEvent:)-3v4sh"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerListener/player(_:didReceiveOnSourceLoadedEvent:)-hs20":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveOnSourceLoadedEvent:)-hs20","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"player","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","text":"UniPlayer","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveOnSourceLoadedEvent"},{"kind":"text","text":": "},{"preciseIdentifier":"s:9KKSPlayer20UniSourceLoadedEventC","text":"UniSourceLoadedEvent","kind":"typeIdentifier"},{"kind":"text","text":")"}],"defaultImplementations":1,"kind":"symbol","role":"symbol","type":"topic","title":"player(_:didReceiveOnSourceLoadedEvent:)","required":true,"url":"\/documentation\/kksplayer\/uniplayerlistener\/player(_:didreceiveonsourceloadedevent:)-hs20","abstract":[{"type":"text","text":"Called when the player receives an "},{"type":"codeVoice","code":"UniSourceLoadedEvent"},{"type":"text","text":" indicating a media source has finished loading."}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerListener/player(_:didReceiveTimeShiftEvent:)-5a093":{"defaultImplementations":1,"required":true,"role":"symbol","type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveTimeShiftEvent:)-5a093","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"player"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","text":"UniPlayer","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveTimeShiftEvent"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9KKSPlayer17UniTimeShiftEventC","text":"UniTimeShiftEvent","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"player(_:didReceiveTimeShiftEvent:)","kind":"symbol","url":"\/documentation\/kksplayer\/uniplayerlistener\/player(_:didreceivetimeshiftevent:)-5a093","abstract":[{"type":"text","text":"Called when the player receives an "},{"type":"codeVoice","code":"UniTimeShiftEvent"},{"text":" indicating a time shift operation.","type":"text"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerListener/player(_:didReceiveOnPausedEvent:)-55auq":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"player","kind":"identifier"},{"kind":"text","text":"("},{"text":"UniPlayer","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didReceiveOnPausedEvent","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UniEvent","kind":"typeIdentifier","preciseIdentifier":"s:9KKSPlayer8UniEventP"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/kksplayer\/uniplayerlistener\/player(_:didreceiveonpausedevent:)-55auq","abstract":[{"text":"Called when the player receives an ","type":"text"},{"code":"UniEvent","type":"codeVoice"},{"text":" on the paused event.","type":"text"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveOnPausedEvent:)-55auq","defaultImplementations":1,"title":"player(_:didReceiveOnPausedEvent:)"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerListener/player(_:didReceiveOnSeekedEvent:)-13yfq":{"role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveOnSeekedEvent:)-13yfq","defaultImplementations":1,"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"player"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","text":"UniPlayer","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveOnSeekedEvent"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:9KKSPlayer8UniEventP","text":"UniEvent"},{"kind":"text","text":")"}],"required":true,"url":"\/documentation\/kksplayer\/uniplayerlistener\/player(_:didreceiveonseekedevent:)-13yfq","title":"player(_:didReceiveOnSeekedEvent:)","abstract":[{"text":"Called when the player receives an ","type":"text"},{"code":"UniEvent","type":"codeVoice"},{"type":"text","text":" indicating a seek operation has completed."}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerListener/player(_:didReceiveSourceUnloadedEvent:)-7oit5":{"title":"player(_:didReceiveSourceUnloadedEvent:)","url":"\/documentation\/kksplayer\/uniplayerlistener\/player(_:didreceivesourceunloadedevent:)-7oit5","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"player","kind":"identifier"},{"kind":"text","text":"("},{"text":"UniPlayer","kind":"typeIdentifier","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer"},{"kind":"text","text":", "},{"text":"didReceiveSourceUnloadedEvent","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9KKSPlayer22UniSourceUnloadedEventC","kind":"typeIdentifier","text":"UniSourceUnloadedEvent"},{"kind":"text","text":")"}],"role":"symbol","defaultImplementations":1,"abstract":[{"type":"text","text":"Called when the player receives an "},{"code":"UniSourceUnloadedEvent","type":"codeVoice"},{"type":"text","text":" indicating a media source has been unloaded."}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveSourceUnloadedEvent:)-7oit5","required":true,"type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerListener/player(_:didReceiveLoadedTimeChangedEvent:)-89ljk":{"url":"\/documentation\/kksplayer\/uniplayerlistener\/player(_:didreceiveloadedtimechangedevent:)-89ljk","kind":"symbol","abstract":[{"type":"text","text":"Called when the player receives an "},{"code":"UniLoadedTimeChangedEvent","type":"codeVoice"},{"text":" indicating the loaded time ranges have changed.","type":"text"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveLoadedTimeChangedEvent:)-89ljk","defaultImplementations":1,"role":"symbol","title":"player(_:didReceiveLoadedTimeChangedEvent:)","type":"topic","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"player","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","text":"UniPlayer","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didReceiveLoadedTimeChangedEvent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UniLoadedTimeRangeChangedEvent","kind":"typeIdentifier","preciseIdentifier":"s:9KKSPlayer30UniLoadedTimeRangeChangedEventC"},{"text":")","kind":"text"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerListener/player(_:didReceiveUnmutedEvent:)-4unf2":{"kind":"symbol","required":true,"defaultImplementations":1,"abstract":[{"text":"Called when the player receives an ","type":"text"},{"code":"UniEvent","type":"codeVoice"},{"text":" indicating the audio is unmuted.","type":"text"}],"role":"symbol","url":"\/documentation\/kksplayer\/uniplayerlistener\/player(_:didreceiveunmutedevent:)-4unf2","type":"topic","title":"player(_:didReceiveUnmutedEvent:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"player"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","text":"UniPlayer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceiveUnmutedEvent"},{"text":": ","kind":"text"},{"text":"UniEvent","kind":"typeIdentifier","preciseIdentifier":"s:9KKSPlayer8UniEventP"},{"kind":"text","text":")"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveUnmutedEvent:)-4unf2"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerListener/player(_:didReceiveSourceErrorEvent:)-1tc7k":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener\/player(_:didReceiveSourceErrorEvent:)-1tc7k","title":"player(_:didReceiveSourceErrorEvent:)","role":"symbol","defaultImplementations":1,"required":true,"url":"\/documentation\/kksplayer\/uniplayerlistener\/player(_:didreceivesourceerrorevent:)-1tc7k","abstract":[{"text":"Called when the player receives an ","type":"text"},{"type":"codeVoice","code":"UniSourceErrorEvent"},{"type":"text","text":" indicating an error occurred with the media source."}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"player"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UniPlayer","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer"},{"text":", ","kind":"text"},{"text":"didReceiveSourceErrorEvent","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:9KKSPlayer19UniSourceErrorEventC","text":"UniSourceErrorEvent"},{"kind":"text","text":")"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"UniPlayerView","op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerView\/title"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerView\/fragments","value":[{"text":"UniPlayerView","kind":"identifier"}],"op":"replace"},{"value":"UniControllerPlayerView","op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniControllerPlayerView\/title"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniControllerPlayerView\/fragments","value":[{"kind":"identifier","text":"UniControllerPlayerView"}]}]}]}