{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniSubtitleTrack"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/kksplayer\/unisubtitletrack"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/kksplayer\/unisubtitletrack"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrack"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/KKS.KKSPlayer\/objc(pl)NSObject","doc:\/\/KKS.KKSPlayer\/s7CVarArgP","doc:\/\/KKS.KKSPlayer\/s28CustomDebugStringConvertibleP","doc:\/\/KKS.KKSPlayer\/s23CustomStringConvertibleP","doc:\/\/KKS.KKSPlayer\/SQ","doc:\/\/KKS.KKSPlayer\/SH","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrackProtocol"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSubtitleTrack","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniSubtitleTrack"}],"title":"UniSubtitleTrack","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@KKSPlayer@objc(cs)UniSubtitleTrack","modules":[{"name":"KKSPlayer"}],"navigatorTitle":[{"kind":"identifier","text":"UniSubtitleTrack"}]},"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer"]]},"references":{"doc://KKS.KKSPlayer/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/KKS.KKSPlayer\/s7CVarArgP"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniTrackProtocol":{"role":"symbol","title":"UniTrackProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniTrackProtocol"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrackProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UniTrackProtocol"}],"url":"\/documentation\/kksplayer\/unitrackprotocol"},"doc://KKS.KKSPlayer/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/KKS.KKSPlayer\/SQ"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniTrack":{"role":"symbol","title":"UniTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniTrack"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UniTrack"}],"url":"\/documentation\/kksplayer\/unitrack"},"doc://KKS.KKSPlayer/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/KKS.KKSPlayer\/s23CustomStringConvertibleP"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSubtitleTrack":{"role":"symbol","title":"UniSubtitleTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniSubtitleTrack"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSubtitleTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UniSubtitleTrack"}],"url":"\/documentation\/kksplayer\/unisubtitletrack"},"doc://KKS.KKSPlayer/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)NSObject"},"doc://KKS.KKSPlayer/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/KKS.KKSPlayer\/s28CustomDebugStringConvertibleP"},"doc://KKS.KKSPlayer/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/KKS.KKSPlayer\/SH"},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"role":"collection","title":"KKSPlayer","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","kind":"symbol","type":"topic","url":"\/documentation\/kksplayer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"UniSubtitleTrack"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"UniSubtitleTrack"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"UniSubtitleTrack"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrack"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniSubtitleTrack"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrack","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniTrack","text":"UniTrack"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniTrack\/title","value":"UniTrack"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniTrack\/fragments","value":[{"kind":"identifier","text":"UniTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSubtitleTrack\/title","value":"UniSubtitleTrack"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSubtitleTrack\/fragments","value":[{"kind":"identifier","text":"UniSubtitleTrack"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}