{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniSheetPresentationController"}]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSheetPresentationController\/init(rootViewController:detents:)"]}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/KKS.KKSPlayer\/objc(cs)UINavigationController"],"kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/KKS.KKSPlayer\/objc(pl)NSCoding","doc:\/\/KKS.KKSPlayer\/objc(pl)NSExtensionRequestHandling","doc:\/\/KKS.KKSPlayer\/objc(pl)NSObject","doc:\/\/KKS.KKSPlayer\/s7CVarArgP","doc:\/\/KKS.KKSPlayer\/s28CustomDebugStringConvertibleP","doc:\/\/KKS.KKSPlayer\/s23CustomStringConvertibleP","doc:\/\/KKS.KKSPlayer\/SQ","doc:\/\/KKS.KKSPlayer\/SH","doc:\/\/KKS.KKSPlayer\/s8SendableP","doc:\/\/KKS.KKSPlayer\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/KKS.KKSPlayer\/objc(pl)UIAppearanceContainer","doc:\/\/KKS.KKSPlayer\/objc(pl)UIContentContainer","doc:\/\/KKS.KKSPlayer\/objc(pl)UIFocusEnvironment","doc:\/\/KKS.KKSPlayer\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/KKS.KKSPlayer\/objc(pl)UIResponderStandardEditActions","doc:\/\/KKS.KKSPlayer\/objc(pl)UIStateRestoring","doc:\/\/KKS.KKSPlayer\/5UIKit23UITraitChangeObservableP","doc:\/\/KKS.KKSPlayer\/objc(pl)UITraitEnvironment","doc:\/\/KKS.KKSPlayer\/objc(pl)UIUserActivityRestoring"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kksplayer\/unisheetpresentationcontroller"]},{"paths":["\/documentation\/kksplayer\/unisheetpresentationcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer"]]},"metadata":{"externalID":"c:@M@KKSPlayer@objc(cs)UniSheetPresentationController","platforms":[{"beta":false,"unavailable":false,"name":"iOS","deprecated":false,"introducedAt":"15.0"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UniSheetPresentationController"}],"roleHeading":"Class","modules":[{"name":"KKSPlayer"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UniSheetPresentationController","kind":"identifier"}],"title":"UniSheetPresentationController","symbolKind":"class"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSheetPresentationController"},"references":{"doc://KKS.KKSPlayer/objc(pl)UIStateRestoring":{"title":"UIKit.UIStateRestoring","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIStateRestoring","type":"unresolvable"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSheetPresentationController":{"role":"symbol","navigatorTitle":[{"text":"UniSheetPresentationController","kind":"identifier"}],"title":"UniSheetPresentationController","kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSheetPresentationController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UniSheetPresentationController","kind":"identifier"}],"url":"\/documentation\/kksplayer\/unisheetpresentationcontroller","abstract":[],"type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSheetPresentationController/init(rootViewController:detents:)":{"title":"init(rootViewController:detents:)","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSheetPresentationController\/init(rootViewController:detents:)","abstract":[],"url":"\/documentation\/kksplayer\/unisheetpresentationcontroller\/init(rootviewcontroller:detents:)","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rootViewController","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"detents"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISheetPresentationController","text":"UISheetPresentationController"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Detent","preciseIdentifier":"c:objc(cs)UISheetPresentationControllerDetent"},{"kind":"text","text":"])"}]},"doc://KKS.KKSPlayer/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIResponderStandardEditActions","type":"unresolvable"},"doc://KKS.KKSPlayer/objc(pl)NSCoding":{"title":"Foundation.NSCoding","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)NSCoding","type":"unresolvable"},"doc://KKS.KKSPlayer/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable"},"doc://KKS.KKSPlayer/objc(cs)UINavigationController":{"title":"UINavigationController","identifier":"doc:\/\/KKS.KKSPlayer\/objc(cs)UINavigationController","type":"unresolvable"},"doc://KKS.KKSPlayer/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/KKS.KKSPlayer\/s8SendableP","type":"unresolvable"},"doc://KKS.KKSPlayer/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/KKS.KKSPlayer\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://KKS.KKSPlayer/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/KKS.KKSPlayer\/5UIKit23UITraitChangeObservableP","type":"unresolvable"},"doc://KKS.KKSPlayer/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/KKS.KKSPlayer\/SQ","type":"unresolvable"},"doc://KKS.KKSPlayer/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/KKS.KKSPlayer\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://KKS.KKSPlayer/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIAppearanceContainer","type":"unresolvable"},"doc://KKS.KKSPlayer/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://KKS.KKSPlayer/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling"},"doc://KKS.KKSPlayer/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://KKS.KKSPlayer/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/s7CVarArgP","title":"Swift.CVarArg"},"doc://KKS.KKSPlayer/objc(pl)UIContentContainer":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer"},"doc://KKS.KKSPlayer/SH":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/SH","title":"Swift.Hashable"},"doc://KKS.KKSPlayer/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://KKS.KKSPlayer/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","role":"collection","url":"\/documentation\/kksplayer","kind":"symbol","title":"KKSPlayer","type":"topic"},"doc://KKS.KKSPlayer/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"UniSheetPresentationController","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"UniSheetPresentationController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"UniSheetPresentationController","kind":"identifier"}]},{"value":null,"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/KKS.KKSPlayer\/objc(cs)UINavigationController"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UniSheetPresentationController","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationController","text":"UINavigationController"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"UniSheetPresentationController","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSheetPresentationController\/title","op":"replace"},{"value":[{"text":"UniSheetPresentationController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSheetPresentationController\/fragments"}]}]}