{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniSourceListener"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/kksplayer\/unisourcelistener"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/KKS.KKSPlayer\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniControllerPlayerView","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceListener","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceListener\/source(_:didReceiveSourceErrorEvent:)-8htqr"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniSourceListener"}],"title":"UniSourceListener","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:9KKSPlayer17UniSourceListenerP","modules":[{"name":"KKSPlayer"}],"navigatorTitle":[{"kind":"identifier","text":"UniSourceListener"}]},"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer"]]},"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView":{"role":"symbol","title":"UniPlayerView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniPlayerView"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UniPlayerView"}],"url":"\/documentation\/kksplayer\/uniplayerview"},"doc://KKS.KKSPlayer/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)NSObject"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSourceListener/source(_:didReceiveSourceErrorEvent:)-8htqr":{"defaultImplementations":1,"role":"symbol","title":"source(_:didReceiveSourceErrorEvent:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"source"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UniSource","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniSource"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveSourceErrorEvent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UniSourceErrorEvent","preciseIdentifier":"s:9KKSPlayer19UniSourceErrorEventC"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceListener\/source(_:didReceiveSourceErrorEvent:)-8htqr","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/kksplayer\/unisourcelistener\/source(_:didreceivesourceerrorevent:)-8htqr"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSourceListener":{"role":"symbol","title":"UniSourceListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniSourceListener"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UniSourceListener"}],"url":"\/documentation\/kksplayer\/unisourcelistener"},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"role":"collection","title":"KKSPlayer","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","kind":"symbol","type":"topic","url":"\/documentation\/kksplayer"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer":{"role":"symbol","title":"UniPlayer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniPlayer"}],"abstract":[{"type":"text","text":"An object that provides the interface to control the player’s transport behavior."}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UniPlayer"}],"url":"\/documentation\/kksplayer\/uniplayer"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniControllerPlayerView":{"role":"symbol","title":"UniControllerPlayerView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniControllerPlayerView"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniControllerPlayerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UniControllerPlayerView"}],"url":"\/documentation\/kksplayer\/unicontrollerplayerview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerView\/title","value":"UniPlayerView"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerView\/fragments","value":[{"kind":"identifier","text":"UniPlayerView"}]},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/title","value":"UniPlayer"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/fragments","value":[{"kind":"identifier","text":"UniPlayer"}]},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniControllerPlayerView\/title","value":"UniControllerPlayerView"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniControllerPlayerView\/fragments","value":[{"kind":"identifier","text":"UniControllerPlayerView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}