{"metadata":{"role":"symbol","roleHeading":"Class","title":"UniSettingViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniSettingViewController"}],"navigatorTitle":[{"kind":"identifier","text":"UniSettingViewController"}],"modules":[{"name":"KKSPlayer"}],"symbolKind":"class","externalID":"c:@M@KKSPlayer@objc(cs)UniSettingViewController"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kksplayer\/unisettingviewcontroller"]},{"paths":["\/documentation\/kksplayer\/unisettingviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniSettingViewController"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSettingViewController","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSettingViewController\/init(player:)"]},{"title":"Instance Methods","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSettingViewController\/numberOfSections(in:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSettingViewController\/tableView(_:cellForRowAt:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSettingViewController\/tableView(_:didSelectRowAt:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSettingViewController\/tableView(_:numberOfRowsInSection:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSettingViewController\/viewDidLoad()"]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniUITableViewController"],"title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/KKS.KKSPlayer\/objc(pl)NSCoding","doc:\/\/KKS.KKSPlayer\/objc(pl)NSExtensionRequestHandling","doc:\/\/KKS.KKSPlayer\/objc(pl)NSObject","doc:\/\/KKS.KKSPlayer\/s7CVarArgP","doc:\/\/KKS.KKSPlayer\/s28CustomDebugStringConvertibleP","doc:\/\/KKS.KKSPlayer\/s23CustomStringConvertibleP","doc:\/\/KKS.KKSPlayer\/SQ","doc:\/\/KKS.KKSPlayer\/SH","doc:\/\/KKS.KKSPlayer\/s8SendableP","doc:\/\/KKS.KKSPlayer\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/KKS.KKSPlayer\/objc(pl)UIAppearanceContainer","doc:\/\/KKS.KKSPlayer\/objc(pl)UIContentContainer","doc:\/\/KKS.KKSPlayer\/objc(pl)UIFocusEnvironment","doc:\/\/KKS.KKSPlayer\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/KKS.KKSPlayer\/objc(pl)UIResponderStandardEditActions","doc:\/\/KKS.KKSPlayer\/objc(pl)UIScrollViewDelegate","doc:\/\/KKS.KKSPlayer\/objc(pl)UIStateRestoring","doc:\/\/KKS.KKSPlayer\/objc(pl)UITableViewDataSource","doc:\/\/KKS.KKSPlayer\/objc(pl)UITableViewDelegate","doc:\/\/KKS.KKSPlayer\/5UIKit23UITraitChangeObservableP","doc:\/\/KKS.KKSPlayer\/objc(pl)UITraitEnvironment","doc:\/\/KKS.KKSPlayer\/objc(pl)UIUserActivityRestoring"],"kind":"relationships"}],"references":{"doc://KKS.KKSPlayer/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIUserActivityRestoring","type":"unresolvable","title":"UIKit.UIUserActivityRestoring"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSettingViewController":{"title":"UniSettingViewController","role":"symbol","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSettingViewController","url":"\/documentation\/kksplayer\/unisettingviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniSettingViewController"}],"navigatorTitle":[{"kind":"identifier","text":"UniSettingViewController"}]},"doc://KKS.KKSPlayer/SH":{"identifier":"doc:\/\/KKS.KKSPlayer\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://KKS.KKSPlayer/objc(pl)NSCoding":{"identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)NSCoding","type":"unresolvable","title":"Foundation.NSCoding"},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","role":"collection","url":"\/documentation\/kksplayer","kind":"symbol","title":"KKSPlayer","type":"topic"},"doc://KKS.KKSPlayer/objc(pl)NSExtensionRequestHandling":{"identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)NSExtensionRequestHandling","type":"unresolvable","title":"Foundation.NSExtensionRequestHandling"},"doc://KKS.KKSPlayer/objc(pl)UITableViewDataSource":{"identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UITableViewDataSource","type":"unresolvable","title":"UIKit.UITableViewDataSource"},"doc://KKS.KKSPlayer/s23CustomStringConvertibleP":{"identifier":"doc:\/\/KKS.KKSPlayer\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://KKS.KKSPlayer/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIStateRestoring","type":"unresolvable","title":"UIKit.UIStateRestoring"},"doc://KKS.KKSPlayer/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions","type":"unresolvable"},"doc://KKS.KKSPlayer/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSettingViewController/tableView(_:cellForRowAt:)":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSettingViewController\/tableView(_:cellForRowAt:)","role":"symbol","title":"tableView(_:cellForRowAt:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"tableView:cellForRowAtIndexPath:"}],"abstract":[],"url":"\/documentation\/kksplayer\/unisettingviewcontroller\/tableview(_:cellforrowat:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier","text":"UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cellForRowAt"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell"}],"type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSettingViewController/numberOfSections(in:)":{"kind":"symbol","abstract":[],"navigatorTitle":[{"text":"numberOfSectionsInTableView:","kind":"identifier"}],"title":"numberOfSections(in:)","url":"\/documentation\/kksplayer\/unisettingviewcontroller\/numberofsections(in:)","role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSettingViewController\/numberOfSections(in:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"numberOfSections","kind":"identifier"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}]},"doc://KKS.KKSPlayer/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://KKS.KKSPlayer/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://KKS.KKSPlayer/objc(pl)UITableViewDelegate":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UITableViewDelegate","title":"UIKit.UITableViewDelegate"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSettingViewController/viewDidLoad()":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSettingViewController\/viewDidLoad()","role":"symbol","title":"viewDidLoad()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/kksplayer\/unisettingviewcontroller\/viewdidload()","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"text":"()","kind":"text"}],"type":"topic"},"doc://KKS.KKSPlayer/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSettingViewController/tableView(_:didSelectRowAt:)":{"type":"topic","kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSettingViewController\/tableView(_:didSelectRowAt:)","abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didSelectRowAt"},{"kind":"text","text":": "},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"tableView:didSelectRowAtIndexPath:","kind":"identifier"}],"title":"tableView(_:didSelectRowAt:)","url":"\/documentation\/kksplayer\/unisettingviewcontroller\/tableview(_:didselectrowat:)"},"doc://KKS.KKSPlayer/objc(pl)UIContentContainer":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniUITableViewController":{"kind":"symbol","navigatorTitle":[{"text":"UniUITableViewController","kind":"identifier"}],"role":"symbol","abstract":[],"title":"UniUITableViewController","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniUITableViewController","type":"topic","url":"\/documentation\/kksplayer\/uniuitableviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniUITableViewController"}]},"doc://KKS.KKSPlayer/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://KKS.KKSPlayer/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://KKS.KKSPlayer/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/s7CVarArgP","title":"Swift.CVarArg"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSettingViewController/init(player:)":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSettingViewController\/init(player:)","role":"symbol","title":"init(player:)","kind":"symbol","url":"\/documentation\/kksplayer\/unisettingviewcontroller\/init(player:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"player"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","text":"UniPlayer"},{"kind":"text","text":")"}],"type":"topic"},"doc://KKS.KKSPlayer/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIFocusEnvironment"},"doc://KKS.KKSPlayer/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/s28CustomDebugStringConvertibleP"},"doc://KKS.KKSPlayer/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/s8SendableP"},"doc://KKS.KKSPlayer/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/SQ"},"doc://KKS.KKSPlayer/objc(pl)UIScrollViewDelegate":{"title":"UIKit.UIScrollViewDelegate","type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIScrollViewDelegate"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSettingViewController/tableView(_:numberOfRowsInSection:)":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSettingViewController\/tableView(_:numberOfRowsInSection:)","role":"symbol","title":"tableView(_:numberOfRowsInSection:)","kind":"symbol","navigatorTitle":[{"text":"tableView:numberOfRowsInSection:","kind":"identifier"}],"url":"\/documentation\/kksplayer\/unisettingviewcontroller\/tableview(_:numberofrowsinsection:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"numberOfRowsInSection"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"UniSettingViewController","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"UniSettingViewController","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"UniSettingViewController"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSettingViewController\/numberOfSections(in:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSettingViewController\/tableView(_:cellForRowAt:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSettingViewController\/tableView(_:didSelectRowAt:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSettingViewController\/tableView(_:numberOfRowsInSection:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSettingViewController\/viewDidLoad()"],"title":"Instance Methods"}]},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniUITableViewController"]}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"UniSettingViewController","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniUITableViewController","text":"UniUITableViewController","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniUITableViewController"}],"languages":["occ"]}]},"op":"replace"},{"value":"UniSettingViewController","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSettingViewController\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"UniSettingViewController"}],"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSettingViewController\/fragments"},{"value":"tableView:cellForRowAtIndexPath:","op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSettingViewController~1tableView(_:cellForRowAt:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSettingViewController~1tableView(_:cellForRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:cellForRowAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSettingViewController~1numberOfSections(in:)\/title","value":"numberOfSectionsInTableView:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"numberOfSectionsInTableView:","kind":"identifier"}],"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSettingViewController~1numberOfSections(in:)\/fragments"},{"value":"viewDidLoad","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSettingViewController~1viewDidLoad()\/title","op":"replace"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSettingViewController~1viewDidLoad()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSettingViewController~1tableView(_:didSelectRowAt:)\/title","value":"tableView:didSelectRowAtIndexPath:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"tableView:didSelectRowAtIndexPath:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSettingViewController~1tableView(_:didSelectRowAt:)\/fragments"},{"value":"UniUITableViewController","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniUITableViewController\/title","op":"replace"},{"value":[{"text":"UniUITableViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniUITableViewController\/fragments"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSettingViewController~1tableView(_:numberOfRowsInSection:)\/title","value":"tableView:numberOfRowsInSection:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"tableView:numberOfRowsInSection:","kind":"identifier"}],"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSettingViewController~1tableView(_:numberOfRowsInSection:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}