{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kksplayer\/unisource"]},{"paths":["\/documentation\/kksplayer\/unisource"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSource"},"topicSections":[{"identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSource\/sourceConfig"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSource\/add(listener:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSource\/remove(listener:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSource\/thumbnail(forTime:)"]}],"metadata":{"externalID":"c:@M@KKSPlayer@objc(cs)UniSource","navigatorTitle":[{"text":"UniSource","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"BVPlayer"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UniSource","kind":"identifier"}],"title":"UniSource","roleHeading":"Class"},"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/KKS.KKSPlayer\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/KKS.KKSPlayer\/objc(pl)NSObject","doc:\/\/KKS.KKSPlayer\/s7CVarArgP","doc:\/\/KKS.KKSPlayer\/s28CustomDebugStringConvertibleP","doc:\/\/KKS.KKSPlayer\/s23CustomStringConvertibleP","doc:\/\/KKS.KKSPlayer\/SQ","doc:\/\/KKS.KKSPlayer\/SH"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniSource"}],"languages":["swift"]}]}],"references":{"doc://KKS.KKSPlayer/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/s28CustomDebugStringConvertibleP"},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","abstract":[{"text":"BlendVision One iOS Player SDK","type":"text"}],"title":"BVPlayer","url":"\/documentation\/kksplayer","kind":"symbol","role":"collection"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSource/thumbnail(forTime:)":{"type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSource\/thumbnail(forTime:)","url":"\/documentation\/kksplayer\/unisource\/thumbnail(fortime:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"thumbnail"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forTime"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:9KKSPlayer12UniThumbnailV","text":"UniThumbnail","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"abstract":[{"text":"Returns the thumbnail image for a certain time.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Requires a configured UniThumbnailTrack in the corresponding UniSourceConfig."},{"text":" ","type":"text"},{"type":"text","text":"NOTE: This function returns nil"}],"title":"thumbnail(forTime:)"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSource/sourceConfig":{"url":"\/documentation\/kksplayer\/unisource\/sourceconfig","title":"sourceConfig","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"sourceConfig","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9KKSPlayer15UniSourceConfigC","text":"UniSourceConfig","kind":"typeIdentifier"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSource\/sourceConfig","kind":"symbol","role":"symbol","type":"topic","abstract":[]},"doc://KKS.KKSPlayer/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSource/add(listener:)":{"kind":"symbol","abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSource\/add(listener:)","title":"add(listener:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"add","kind":"identifier"},{"kind":"text","text":"("},{"text":"listener","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9KKSPlayer17UniSourceListenerP","text":"UniSourceListener","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/kksplayer\/unisource\/add(listener:)"},"doc://KKS.KKSPlayer/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(cs)NSObject","title":"NSObject"},"doc://KKS.KKSPlayer/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/s7CVarArgP","title":"Swift.CVarArg"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSource":{"role":"symbol","title":"UniSource","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSource","url":"\/documentation\/kksplayer\/unisource","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"UniSource","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UniSource","kind":"identifier"}]},"doc://KKS.KKSPlayer/SQ":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/SQ","title":"Swift.Equatable"},"doc://KKS.KKSPlayer/SH":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/SH","title":"Swift.Hashable"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSource/remove(listener:)":{"type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSource\/remove(listener:)","url":"\/documentation\/kksplayer\/unisource\/remove(listener:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"remove"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"preciseIdentifier":"s:9KKSPlayer17UniSourceListenerP","text":"UniSourceListener","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[],"title":"remove(listener:)"},"doc://KKS.KKSPlayer/s23CustomStringConvertibleP":{"identifier":"doc:\/\/KKS.KKSPlayer\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"UniSource"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"UniSource"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"UniSource"}],"path":"\/metadata\/navigatorTitle"},{"value":null,"path":"\/topicSections","op":"replace"},{"value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/KKS.KKSPlayer\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"UniSource","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSource\/title","value":"UniSource"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSource\/fragments","value":[{"text":"UniSource","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}