{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniThumbnailTrack"},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrack"]},{"identifiers":["doc:\/\/KKS.KKSPlayer\/objc(pl)NSObject","doc:\/\/KKS.KKSPlayer\/s7CVarArgP","doc:\/\/KKS.KKSPlayer\/s28CustomDebugStringConvertibleP","doc:\/\/KKS.KKSPlayer\/s23CustomStringConvertibleP","doc:\/\/KKS.KKSPlayer\/SQ","doc:\/\/KKS.KKSPlayer\/SH","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrackProtocol"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"metadata":{"externalID":"c:@M@KKSPlayer@objc(cs)UniThumbnailTrack","title":"UniThumbnailTrack","roleHeading":"Class","symbolKind":"class","role":"symbol","modules":[{"name":"BVPlayer"}],"navigatorTitle":[{"kind":"identifier","text":"UniThumbnailTrack"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UniThumbnailTrack","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kksplayer\/unithumbnailtrack"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/kksplayer\/unithumbnailtrack"]}],"sections":[],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniThumbnailTrack\/init(url:label:identifier:isDefaultTrack:)"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniThumbnailTrack"}]}],"kind":"declarations"}],"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniTrackProtocol":{"kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrackProtocol","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniTrackProtocol"}],"navigatorTitle":[{"text":"UniTrackProtocol","kind":"identifier"}],"url":"\/documentation\/kksplayer\/unitrackprotocol","type":"topic","title":"UniTrackProtocol","role":"symbol"},"doc://KKS.KKSPlayer/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/KKS.KKSPlayer\/SQ"},"doc://KKS.KKSPlayer/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/KKS.KKSPlayer\/s23CustomStringConvertibleP"},"doc://KKS.KKSPlayer/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/KKS.KKSPlayer\/s7CVarArgP"},"doc://KKS.KKSPlayer/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/KKS.KKSPlayer\/SH"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniTrack":{"type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrack","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"UniTrack","kind":"identifier"}],"title":"UniTrack","url":"\/documentation\/kksplayer\/unitrack","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UniTrack","kind":"identifier"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","abstract":[{"text":"BlendVision One iOS Player SDK","type":"text"}],"title":"BVPlayer","url":"\/documentation\/kksplayer","kind":"symbol","role":"collection"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniThumbnailTrack":{"url":"\/documentation\/kksplayer\/unithumbnailtrack","title":"UniThumbnailTrack","type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniThumbnailTrack"}],"navigatorTitle":[{"text":"UniThumbnailTrack","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniThumbnailTrack"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniThumbnailTrack/init(url:label:identifier:isDefaultTrack:)":{"kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"url","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"label","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"isDefaultTrack","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniThumbnailTrack\/init(url:label:identifier:isDefaultTrack:)","title":"init(url:label:identifier:isDefaultTrack:)","type":"topic","url":"\/documentation\/kksplayer\/unithumbnailtrack\/init(url:label:identifier:isdefaulttrack:)"},"doc://KKS.KKSPlayer/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://KKS.KKSPlayer/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"UniThumbnailTrack"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"UniThumbnailTrack","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"UniThumbnailTrack","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrack"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"UniThumbnailTrack","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrack","text":"UniTrack","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniTrack"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniTrack\/title","op":"replace","value":"UniTrack"},{"op":"replace","value":[{"kind":"identifier","text":"UniTrack"}],"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniTrack\/fragments"},{"value":"UniThumbnailTrack","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniThumbnailTrack\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniThumbnailTrack\/fragments","value":[{"kind":"identifier","text":"UniThumbnailTrack"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}