{"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/KKS.KKSPlayer\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Inherited By","type":"inheritedBy","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniAudioTrack","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSubtitleTrack","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniThumbnailTrack"]},{"identifiers":["doc:\/\/KKS.KKSPlayer\/objc(pl)NSObject","doc:\/\/KKS.KKSPlayer\/s7CVarArgP","doc:\/\/KKS.KKSPlayer\/s28CustomDebugStringConvertibleP","doc:\/\/KKS.KKSPlayer\/s23CustomStringConvertibleP","doc:\/\/KKS.KKSPlayer\/SQ","doc:\/\/KKS.KKSPlayer\/SH","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrackProtocol"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"metadata":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniTrack"}],"modules":[{"name":"BVPlayer"}],"externalID":"c:@M@KKSPlayer@objc(cs)UniTrack","navigatorTitle":[{"text":"UniTrack","kind":"identifier"}],"symbolKind":"class","title":"UniTrack","roleHeading":"Class"},"topicSections":[{"identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrack\/identifier","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrack\/isDefaultTrack","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrack\/label","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrack\/language","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrack\/url"],"title":"Instance Properties"}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kksplayer\/unitrack"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/kksplayer\/unitrack"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrack","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"UniTrack","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://KKS.KKSPlayer/objc(pl)NSObject":{"identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniTrack":{"type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrack","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"UniTrack","kind":"identifier"}],"title":"UniTrack","url":"\/documentation\/kksplayer\/unitrack","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UniTrack","kind":"identifier"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniTrack/label":{"type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrack\/label","kind":"symbol","role":"symbol","title":"label","url":"\/documentation\/kksplayer\/unitrack\/label","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"label","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://KKS.KKSPlayer/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/KKS.KKSPlayer\/SH"},"doc://KKS.KKSPlayer/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/KKS.KKSPlayer\/SQ"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSubtitleTrack":{"abstract":[],"type":"topic","title":"UniSubtitleTrack","url":"\/documentation\/kksplayer\/unisubtitletrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"UniSubtitleTrack","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"UniSubtitleTrack"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSubtitleTrack","role":"symbol","kind":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniTrack/identifier":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"identifier","role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/kksplayer\/unitrack\/identifier","kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrack\/identifier"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniTrack/url":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrack\/url","title":"url","type":"topic","url":"\/documentation\/kksplayer\/unitrack\/url","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"url","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","abstract":[{"text":"BlendVision One iOS Player SDK","type":"text"}],"title":"BVPlayer","url":"\/documentation\/kksplayer","kind":"symbol","role":"collection"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniThumbnailTrack":{"url":"\/documentation\/kksplayer\/unithumbnailtrack","title":"UniThumbnailTrack","type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniThumbnailTrack"}],"navigatorTitle":[{"text":"UniThumbnailTrack","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniThumbnailTrack"},"doc://KKS.KKSPlayer/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://KKS.KKSPlayer/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/objc(cs)NSObject","title":"NSObject"},"doc://KKS.KKSPlayer/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniTrack/language":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"language"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"abstract":[],"type":"topic","url":"\/documentation\/kksplayer\/unitrack\/language","kind":"symbol","title":"language","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrack\/language","role":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniAudioTrack":{"url":"\/documentation\/kksplayer\/uniaudiotrack","title":"UniAudioTrack","abstract":[],"role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniAudioTrack","navigatorTitle":[{"text":"UniAudioTrack","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UniAudioTrack","kind":"identifier"}],"kind":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniTrack/isDefaultTrack":{"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isDefaultTrack","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","url":"\/documentation\/kksplayer\/unitrack\/isdefaulttrack","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrack\/isDefaultTrack","role":"symbol","type":"topic","title":"isDefaultTrack"},"doc://KKS.KKSPlayer/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/KKS.KKSPlayer\/s7CVarArgP","title":"Swift.CVarArg"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniTrackProtocol":{"kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrackProtocol","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniTrackProtocol"}],"navigatorTitle":[{"text":"UniTrackProtocol","kind":"identifier"}],"url":"\/documentation\/kksplayer\/unitrackprotocol","type":"topic","title":"UniTrackProtocol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"UniTrack","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"UniTrack","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"UniTrack","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/KKS.KKSPlayer\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Inherited By","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniAudioTrack","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSubtitleTrack","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniThumbnailTrack"],"kind":"relationships","type":"inheritedBy"}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"UniTrack","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}]}},{"value":"UniTrack","op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniTrack\/title"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniTrack\/fragments","value":[{"kind":"identifier","text":"UniTrack"}]},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSubtitleTrack\/title","value":"UniSubtitleTrack","op":"replace"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSubtitleTrack\/fragments","value":[{"kind":"identifier","text":"UniSubtitleTrack"}],"op":"replace"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniThumbnailTrack\/title","value":"UniThumbnailTrack","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniThumbnailTrack\/fragments","value":[{"kind":"identifier","text":"UniThumbnailTrack"}]},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniAudioTrack\/title","op":"replace","value":"UniAudioTrack"},{"value":[{"text":"UniAudioTrack","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniAudioTrack\/fragments"}]}]}