{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniTrackProtocol"}]}],"kind":"declarations"}],"kind":"symbol","sections":[],"metadata":{"role":"symbol","symbolKind":"protocol","title":"UniTrackProtocol","roleHeading":"Protocol","externalID":"s:9KKSPlayer16UniTrackProtocolP","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"UniTrackProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"UniTrackProtocol","kind":"identifier"}],"modules":[{"name":"KKSPlayer"}]},"relationshipsSections":[{"kind":"relationships","type":"conformingTypes","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniAudioTrack","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSubtitleTrack","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniThumbnailTrack","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrack"],"title":"Conforming Types"}],"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer"]]},"variants":[{"paths":["\/documentation\/kksplayer\/unitrackprotocol"],"traits":[{"interfaceLanguage":"swift"}]}],"topicSections":[{"identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrackProtocol\/identifier","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrackProtocol\/isDefaultTrack","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrackProtocol\/label","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrackProtocol\/language","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrackProtocol\/url"],"title":"Instance Properties"}],"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrackProtocol","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniTrack":{"navigatorTitle":[{"kind":"identifier","text":"UniTrack"}],"url":"\/documentation\/kksplayer\/unitrack","type":"topic","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrack","kind":"symbol","title":"UniTrack","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniTrack"}],"role":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSubtitleTrack":{"abstract":[],"role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSubtitleTrack","title":"UniSubtitleTrack","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniSubtitleTrack"}],"navigatorTitle":[{"text":"UniSubtitleTrack","kind":"identifier"}],"url":"\/documentation\/kksplayer\/unisubtitletrack","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniTrackProtocol":{"url":"\/documentation\/kksplayer\/unitrackprotocol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrackProtocol","type":"topic","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"UniTrackProtocol","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"UniTrackProtocol"}],"title":"UniTrackProtocol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniThumbnailTrack":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UniThumbnailTrack"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniThumbnailTrack","url":"\/documentation\/kksplayer\/unithumbnailtrack","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UniThumbnailTrack","kind":"identifier"}],"title":"UniThumbnailTrack","abstract":[]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniTrackProtocol/isDefaultTrack":{"url":"\/documentation\/kksplayer\/unitrackprotocol\/isdefaulttrack","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrackProtocol\/isDefaultTrack","type":"topic","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isDefaultTrack","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"required":true,"title":"isDefaultTrack"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniAudioTrack":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniAudioTrack"}],"title":"UniAudioTrack","url":"\/documentation\/kksplayer\/uniaudiotrack","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniAudioTrack","abstract":[],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UniAudioTrack"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniTrackProtocol/language":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"language"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[],"url":"\/documentation\/kksplayer\/unitrackprotocol\/language","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrackProtocol\/language","title":"language","type":"topic","kind":"symbol","required":true,"role":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniTrackProtocol/label":{"kind":"symbol","required":true,"type":"topic","url":"\/documentation\/kksplayer\/unitrackprotocol\/label","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"label","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[],"title":"label","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrackProtocol\/label","role":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniTrackProtocol/identifier":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrackProtocol\/identifier","role":"symbol","title":"identifier","kind":"symbol","url":"\/documentation\/kksplayer\/unitrackprotocol\/identifier","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","required":true},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniTrackProtocol/url":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrackProtocol\/url","role":"symbol","title":"url","kind":"symbol","url":"\/documentation\/kksplayer\/unitrackprotocol\/url","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","required":true},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","role":"collection","url":"\/documentation\/kksplayer","kind":"symbol","title":"KKSPlayer","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniTrack\/title","op":"replace","value":"UniTrack"},{"value":[{"text":"UniTrack","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniTrack\/fragments"},{"value":"UniSubtitleTrack","op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSubtitleTrack\/title"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSubtitleTrack\/fragments","op":"replace","value":[{"kind":"identifier","text":"UniSubtitleTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniThumbnailTrack\/title","value":"UniThumbnailTrack"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniThumbnailTrack\/fragments","value":[{"text":"UniThumbnailTrack","kind":"identifier"}]},{"value":"UniAudioTrack","op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniAudioTrack\/title"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniAudioTrack\/fragments","value":[{"text":"UniAudioTrack","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}