{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniUITableViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/kksplayer\/uniuitableviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/kksplayer\/uniuitableviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/KKS.KKSPlayer\/objc(cs)UITableViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSettingViewController"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/KKS.KKSPlayer\/objc(pl)NSCoding","doc:\/\/KKS.KKSPlayer\/objc(pl)NSExtensionRequestHandling","doc:\/\/KKS.KKSPlayer\/objc(pl)NSObject","doc:\/\/KKS.KKSPlayer\/s7CVarArgP","doc:\/\/KKS.KKSPlayer\/s28CustomDebugStringConvertibleP","doc:\/\/KKS.KKSPlayer\/s23CustomStringConvertibleP","doc:\/\/KKS.KKSPlayer\/SQ","doc:\/\/KKS.KKSPlayer\/SH","doc:\/\/KKS.KKSPlayer\/s8SendableP","doc:\/\/KKS.KKSPlayer\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/KKS.KKSPlayer\/objc(pl)UIAppearanceContainer","doc:\/\/KKS.KKSPlayer\/objc(pl)UIContentContainer","doc:\/\/KKS.KKSPlayer\/objc(pl)UIFocusEnvironment","doc:\/\/KKS.KKSPlayer\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/KKS.KKSPlayer\/objc(pl)UIResponderStandardEditActions","doc:\/\/KKS.KKSPlayer\/objc(pl)UIScrollViewDelegate","doc:\/\/KKS.KKSPlayer\/objc(pl)UIStateRestoring","doc:\/\/KKS.KKSPlayer\/objc(pl)UITableViewDataSource","doc:\/\/KKS.KKSPlayer\/objc(pl)UITableViewDelegate","doc:\/\/KKS.KKSPlayer\/5UIKit23UITraitChangeObservableP","doc:\/\/KKS.KKSPlayer\/objc(pl)UITraitEnvironment","doc:\/\/KKS.KKSPlayer\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniUITableViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniUITableViewController\/viewDidLoad()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniUITableViewController"}],"title":"UniUITableViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@KKSPlayer@objc(cs)UniUITableViewController","modules":[{"name":"KKSPlayer"}],"navigatorTitle":[{"kind":"identifier","text":"UniUITableViewController"}]},"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer"]]},"references":{"doc://KKS.KKSPlayer/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://KKS.KKSPlayer/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIFocusEnvironment"},"doc://KKS.KKSPlayer/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIStateRestoring"},"doc://KKS.KKSPlayer/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)NSExtensionRequestHandling"},"doc://KKS.KKSPlayer/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIResponderStandardEditActions"},"doc://KKS.KKSPlayer/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/KKS.KKSPlayer\/s7CVarArgP"},"doc://KKS.KKSPlayer/objc(pl)UITableViewDelegate":{"type":"unresolvable","title":"UIKit.UITableViewDelegate","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UITableViewDelegate"},"doc://KKS.KKSPlayer/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UITraitEnvironment"},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"role":"collection","title":"KKSPlayer","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","kind":"symbol","type":"topic","url":"\/documentation\/kksplayer"},"doc://KKS.KKSPlayer/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/KKS.KKSPlayer\/s8SendableP"},"doc://KKS.KKSPlayer/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIContentContainer"},"doc://KKS.KKSPlayer/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","title":"UIKit.UIScrollViewDelegate","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIScrollViewDelegate"},"doc://KKS.KKSPlayer/objc(pl)UITableViewDataSource":{"type":"unresolvable","title":"UIKit.UITableViewDataSource","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UITableViewDataSource"},"doc://KKS.KKSPlayer/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)NSCoding"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniUITableViewController/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniUITableViewController\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/kksplayer\/uniuitableviewcontroller\/initwithcoder:"},"doc://KKS.KKSPlayer/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/KKS.KKSPlayer\/s23CustomStringConvertibleP"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniUITableViewController/initWithStyle:":{"role":"symbol","title":"initWithStyle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStyle:"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniUITableViewController\/initWithStyle:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithStyle:"}],"url":"\/documentation\/kksplayer\/uniuitableviewcontroller\/initwithstyle:"},"doc://KKS.KKSPlayer/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/KKS.KKSPlayer\/SH"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniUITableViewController":{"role":"symbol","title":"UniUITableViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniUITableViewController"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniUITableViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UniUITableViewController"}],"url":"\/documentation\/kksplayer\/uniuitableviewcontroller"},"doc://KKS.KKSPlayer/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/KKS.KKSPlayer\/5UIKit23UITraitChangeObservableP"},"doc://KKS.KKSPlayer/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/KKS.KKSPlayer\/s28CustomDebugStringConvertibleP"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniUITableViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniUITableViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/kksplayer\/uniuitableviewcontroller\/viewdidload()"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSettingViewController":{"role":"symbol","title":"UniSettingViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniSettingViewController"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSettingViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UniSettingViewController"}],"url":"\/documentation\/kksplayer\/unisettingviewcontroller"},"doc://KKS.KKSPlayer/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIPasteConfigurationSupporting"},"doc://KKS.KKSPlayer/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/KKS.KKSPlayer\/SQ"},"doc://KKS.KKSPlayer/objc(cs)UITableViewController":{"type":"unresolvable","title":"UITableViewController","identifier":"doc:\/\/KKS.KKSPlayer\/objc(cs)UITableViewController"},"doc://KKS.KKSPlayer/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIUserActivityRestoring"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniUITableViewController/initWithNibName:bundle:":{"role":"symbol","title":"initWithNibName:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniUITableViewController\/initWithNibName:bundle:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/kksplayer\/uniuitableviewcontroller\/initwithnibname:bundle:"},"doc://KKS.KKSPlayer/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)NSObject"},"doc://KKS.KKSPlayer/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/KKS.KKSPlayer\/objc(pl)UIAppearanceContainer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"UniUITableViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"UniUITableViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"UniUITableViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniUITableViewController\/initWithCoder:","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniUITableViewController\/initWithNibName:bundle:","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniUITableViewController\/initWithStyle:","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniUITableViewController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/KKS.KKSPlayer\/objc(cs)UITableViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSettingViewController"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniUITableViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UITableViewController","preciseIdentifier":"c:objc(cs)UITableViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniUITableViewController\/title","value":"UniUITableViewController"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniUITableViewController\/fragments","value":[{"kind":"identifier","text":"UniUITableViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniUITableViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniUITableViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSettingViewController\/title","value":"UniSettingViewController"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSettingViewController\/fragments","value":[{"kind":"identifier","text":"UniSettingViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}