{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"player"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"player"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","text":"UniPlayer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveSourceUnloadEvent"},{"kind":"text","text":" "},{"kind":"internalParam","text":"event"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceUnloadEvent","preciseIdentifier":"s:9KKSPlayer20UniSourceUnloadEventC","text":"UniSourceUnloadEvent"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"player","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"UniPlayer"},{"type":"text","text":" instance."}]}]},{"name":"event","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"UniSourceUnloadEvent"},{"type":"text","text":" that was received."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/kksplayer\/uniplayerview\/player(_:didreceivesourceunloadevent:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/player(_:didReceiveSourceUnloadEvent:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when the player receives an "},{"type":"codeVoice","code":"UniSourceUnloadEvent"},{"type":"text","text":" indicating a media source is being unloaded."}],"kind":"symbol","metadata":{"role":"symbol","title":"player(_:didReceiveSourceUnloadEvent:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"player"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UniPlayer","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveSourceUnloadEvent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UniSourceUnloadEvent","preciseIdentifier":"s:9KKSPlayer20UniSourceUnloadEventC"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:9KKSPlayer13UniPlayerViewC6player_27didReceiveSourceUnloadEventyAA0bC0C_AA0bhiJ0CtF","extendedModule":"KKSPlayer","modules":[{"name":"KKSPlayer"}]},"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/UniPlayerListener-Implementations"]]},"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"role":"collection","title":"KKSPlayer","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","kind":"symbol","type":"topic","url":"\/documentation\/kksplayer"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView/UniPlayerListener-Implementations":{"role":"collectionGroup","title":"UniPlayerListener Implementations","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/UniPlayerListener-Implementations","kind":"article","type":"topic","url":"\/documentation\/kksplayer\/uniplayerview\/uniplayerlistener-implementations"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView":{"role":"symbol","title":"UniPlayerView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniPlayerView"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UniPlayerView"}],"url":"\/documentation\/kksplayer\/uniplayerview"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView/player(_:didReceiveSourceUnloadEvent:)":{"role":"symbol","title":"player(_:didReceiveSourceUnloadEvent:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"player"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UniPlayer","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveSourceUnloadEvent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UniSourceUnloadEvent","preciseIdentifier":"s:9KKSPlayer20UniSourceUnloadEventC"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when the player receives an "},{"type":"codeVoice","code":"UniSourceUnloadEvent"},{"type":"text","text":" indicating a media source is being unloaded."}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/player(_:didReceiveSourceUnloadEvent:)","kind":"symbol","type":"topic","url":"\/documentation\/kksplayer\/uniplayerview\/player(_:didreceivesourceunloadevent:)"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer":{"role":"symbol","title":"UniPlayer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniPlayer"}],"abstract":[{"type":"text","text":"An object that provides the interface to control the player’s transport behavior."}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UniPlayer"}],"url":"\/documentation\/kksplayer\/uniplayer"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSourceUnloadEvent":{"role":"symbol","title":"UniSourceUnloadEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniSourceUnloadEvent"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceUnloadEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UniSourceUnloadEvent"}],"url":"\/documentation\/kksplayer\/unisourceunloadevent"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerView\/title","value":"UniPlayerView"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerView\/fragments","value":[{"kind":"identifier","text":"UniPlayerView"}]},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/title","value":"UniPlayer"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/fragments","value":[{"kind":"identifier","text":"UniPlayer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}