{"metadata":{"externalID":"s:9KKSPlayer13UniPlayerViewC6player_26didReceiveSourceErrorEventyAA0bC0C_AA0bhiJ0CtF","role":"symbol","roleHeading":"Instance Method","title":"player(_:didReceiveSourceErrorEvent:)","modules":[{"relatedModules":["KKSPlayer"],"name":"BVPlayer"}],"extendedModule":"KKSPlayer","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"player","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","text":"UniPlayer"},{"text":", ","kind":"text"},{"text":"didReceiveSourceErrorEvent","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:9KKSPlayer19UniSourceErrorEventC","text":"UniSourceErrorEvent","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/player(_:didReceiveSourceErrorEvent:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"player","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"player","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UniPlayer","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer"},{"kind":"text","text":", "},{"text":"didReceiveSourceErrorEvent","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"event"},{"text":": ","kind":"text"},{"text":"UniSourceErrorEvent","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceErrorEvent","kind":"typeIdentifier","preciseIdentifier":"s:9KKSPlayer19UniSourceErrorEventC"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"player","content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"UniPlayer"},{"text":" instance.","type":"text"}]}]},{"name":"event","content":[{"inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"UniSourceErrorEvent"},{"type":"text","text":" that was received."}],"type":"paragraph"}]}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/UniPlayerListener-Implementations"]]},"abstract":[{"type":"text","text":"Called when the player receives an "},{"type":"codeVoice","code":"UniSourceErrorEvent"},{"text":" indicating an error occurred with the media source.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kksplayer\/uniplayerview\/player(_:didreceivesourceerrorevent:)"]}],"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniPlayerView"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView","role":"symbol","abstract":[],"navigatorTitle":[{"text":"UniPlayerView","kind":"identifier"}],"type":"topic","title":"UniPlayerView","url":"\/documentation\/kksplayer\/uniplayerview","kind":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","abstract":[{"text":"BlendVision One iOS Player SDK","type":"text"}],"title":"BVPlayer","url":"\/documentation\/kksplayer","kind":"symbol","role":"collection"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer":{"url":"\/documentation\/kksplayer\/uniplayer","title":"UniPlayer","abstract":[{"text":"An object that provides the interface to control the player’s transport behavior.","type":"text"}],"role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer","navigatorTitle":[{"kind":"identifier","text":"UniPlayer"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UniPlayer","kind":"identifier"}],"kind":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView/UniPlayerListener-Implementations":{"role":"collectionGroup","type":"topic","url":"\/documentation\/kksplayer\/uniplayerview\/uniplayerlistener-implementations","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/UniPlayerListener-Implementations","title":"UniPlayerListener Implementations","kind":"article","abstract":[]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSourceErrorEvent":{"type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceErrorEvent","navigatorTitle":[{"kind":"identifier","text":"UniSourceErrorEvent"}],"title":"UniSourceErrorEvent","url":"\/documentation\/kksplayer\/unisourceerrorevent","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniSourceErrorEvent"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView/player(_:didReceiveSourceErrorEvent:)":{"abstract":[{"type":"text","text":"Called when the player receives an "},{"type":"codeVoice","code":"UniSourceErrorEvent"},{"type":"text","text":" indicating an error occurred with the media source."}],"role":"symbol","type":"topic","title":"player(_:didReceiveSourceErrorEvent:)","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/player(_:didReceiveSourceErrorEvent:)","kind":"symbol","url":"\/documentation\/kksplayer\/uniplayerview\/player(_:didreceivesourceerrorevent:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"player"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","text":"UniPlayer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceiveSourceErrorEvent"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:9KKSPlayer19UniSourceErrorEventC","text":"UniSourceErrorEvent"},{"text":")","kind":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"UniPlayerView","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerView\/title"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerView\/fragments","value":[{"text":"UniPlayerView","kind":"identifier"}],"op":"replace"},{"value":"UniPlayer","op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/title"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/fragments","op":"replace","value":[{"text":"UniPlayer","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}