{"abstract":[{"type":"text","text":"Called when the player receives an "},{"code":"UniSourceLoadEvent","type":"codeVoice"},{"type":"text","text":" indicating a new media source is being loaded."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/player(_:didReceiveOnSourceLoadEvent:)"},"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/UniPlayerListener-Implementations"]]},"kind":"symbol","metadata":{"symbolKind":"method","role":"symbol","externalID":"s:9KKSPlayer13UniPlayerViewC6player_27didReceiveOnSourceLoadEventyAA0bC0C_AA0bijK0CtF","extendedModule":"KKSPlayer","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"player","kind":"identifier"},{"kind":"text","text":"("},{"text":"UniPlayer","kind":"typeIdentifier","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer"},{"kind":"text","text":", "},{"text":"didReceiveOnSourceLoadEvent","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9KKSPlayer18UniSourceLoadEventC","text":"UniSourceLoadEvent","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"player(_:didReceiveOnSourceLoadEvent:)","modules":[{"relatedModules":["KKSPlayer"],"name":"BVPlayer"}],"roleHeading":"Instance Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"player","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"player","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","kind":"typeIdentifier","text":"UniPlayer","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer"},{"text":", ","kind":"text"},{"text":"didReceiveOnSourceLoadEvent","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"event"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9KKSPlayer18UniSourceLoadEventC","kind":"typeIdentifier","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceLoadEvent","text":"UniSourceLoadEvent"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The ","type":"text"},{"code":"UniPlayer","type":"codeVoice"},{"text":" instance.","type":"text"}],"type":"paragraph"}],"name":"player"},{"content":[{"inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"UniSourceLoadEvent"},{"type":"text","text":" that was received."}],"type":"paragraph"}],"name":"event"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kksplayer\/uniplayerview\/player(_:didreceiveonsourceloadevent:)"]}],"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView/UniPlayerListener-Implementations":{"role":"collectionGroup","type":"topic","url":"\/documentation\/kksplayer\/uniplayerview\/uniplayerlistener-implementations","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/UniPlayerListener-Implementations","title":"UniPlayerListener Implementations","kind":"article","abstract":[]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer":{"url":"\/documentation\/kksplayer\/uniplayer","title":"UniPlayer","abstract":[{"text":"An object that provides the interface to control the player’s transport behavior.","type":"text"}],"role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer","navigatorTitle":[{"kind":"identifier","text":"UniPlayer"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UniPlayer","kind":"identifier"}],"kind":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSourceLoadEvent":{"title":"UniSourceLoadEvent","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceLoadEvent","kind":"symbol","role":"symbol","url":"\/documentation\/kksplayer\/unisourceloadevent","type":"topic","navigatorTitle":[{"text":"UniSourceLoadEvent","kind":"identifier"}],"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UniSourceLoadEvent","kind":"identifier"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView/player(_:didReceiveOnSourceLoadEvent:)":{"title":"player(_:didReceiveOnSourceLoadEvent:)","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/player(_:didReceiveOnSourceLoadEvent:)","kind":"symbol","role":"symbol","url":"\/documentation\/kksplayer\/uniplayerview\/player(_:didreceiveonsourceloadevent:)","type":"topic","abstract":[{"type":"text","text":"Called when the player receives an "},{"code":"UniSourceLoadEvent","type":"codeVoice"},{"text":" indicating a new media source is being loaded.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"player","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","text":"UniPlayer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didReceiveOnSourceLoadEvent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UniSourceLoadEvent","kind":"typeIdentifier","preciseIdentifier":"s:9KKSPlayer18UniSourceLoadEventC"},{"kind":"text","text":")"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniPlayerView"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView","role":"symbol","abstract":[],"navigatorTitle":[{"text":"UniPlayerView","kind":"identifier"}],"type":"topic","title":"UniPlayerView","url":"\/documentation\/kksplayer\/uniplayerview","kind":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","abstract":[{"text":"BlendVision One iOS Player SDK","type":"text"}],"title":"BVPlayer","url":"\/documentation\/kksplayer","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/title","value":"UniPlayer"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/fragments","value":[{"text":"UniPlayer","kind":"identifier"}],"op":"replace"},{"value":"UniPlayerView","op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerView\/title"},{"value":[{"text":"UniPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerView\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}