{"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/player(_:didReceiveOnStallStartedEvent:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/kksplayer\/uniplayerview\/player(_:didreceiveonstallstartedevent:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"extendedModule":"KKSPlayer","title":"player(_:didReceiveOnStallStartedEvent:)","externalID":"s:9KKSPlayer13UniPlayerViewC6player_29didReceiveOnStallStartedEventyAA0bC0C_AA0bK0_ptF","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"KKSPlayer"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"player","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","text":"UniPlayer","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveOnStallStartedEvent"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9KKSPlayer8UniEventP","text":"UniEvent","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/UniPlayerListener-Implementations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"player","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"player","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer","text":"UniPlayer","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceiveOnStallStartedEvent"},{"kind":"text","text":" "},{"text":"event","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:9KKSPlayer8UniEventP","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniEvent","text":"UniEvent"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"player","content":[{"inlineContent":[{"type":"text","text":"The "},{"code":"UniPlayer","type":"codeVoice"},{"type":"text","text":" instance."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"UniEvent"},{"type":"text","text":" that was received."}],"type":"paragraph"}],"name":"event"}],"kind":"parameters"}],"kind":"symbol","abstract":[{"text":"Called when the player receives an ","type":"text"},{"type":"codeVoice","code":"UniEvent"},{"type":"text","text":" indicating a stall has started."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView/player(_:didReceiveOnStallStartedEvent:)":{"role":"symbol","url":"\/documentation\/kksplayer\/uniplayerview\/player(_:didreceiveonstallstartedevent:)","type":"topic","kind":"symbol","abstract":[{"text":"Called when the player receives an ","type":"text"},{"code":"UniEvent","type":"codeVoice"},{"type":"text","text":" indicating a stall has started."}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/player(_:didReceiveOnStallStartedEvent:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"player","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","text":"UniPlayer"},{"kind":"text","text":", "},{"text":"didReceiveOnStallStartedEvent","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9KKSPlayer8UniEventP","text":"UniEvent","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"player(_:didReceiveOnStallStartedEvent:)"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UniPlayer","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"UniPlayer"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer","type":"topic","url":"\/documentation\/kksplayer\/uniplayer","title":"UniPlayer","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"An object that provides the interface to control the player’s transport behavior."}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","role":"collection","url":"\/documentation\/kksplayer","kind":"symbol","title":"KKSPlayer","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniPlayerView"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UniPlayerView"}],"url":"\/documentation\/kksplayer\/uniplayerview","type":"topic","abstract":[],"title":"UniPlayerView"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniEvent":{"abstract":[],"title":"UniEvent","url":"\/documentation\/kksplayer\/unievent","role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniEvent","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniEvent"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UniEvent"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView/UniPlayerListener-Implementations":{"kind":"article","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/UniPlayerListener-Implementations","type":"topic","role":"collectionGroup","abstract":[],"title":"UniPlayerListener Implementations","url":"\/documentation\/kksplayer\/uniplayerview\/uniplayerlistener-implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"UniPlayer","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/title"},{"value":[{"kind":"identifier","text":"UniPlayer"}],"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerView\/title","value":"UniPlayerView"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerView\/fragments","op":"replace","value":[{"text":"UniPlayerView","kind":"identifier"}]}]}]}