{"variants":[{"paths":["\/documentation\/kksplayer\/uniplayerview\/player(_:didreceiveonstallendedevent:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"player","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"player"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","kind":"typeIdentifier","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer","text":"UniPlayer"},{"text":", ","kind":"text"},{"text":"didReceiveOnStallEndedEvent","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"event","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UniEvent","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniEvent","kind":"typeIdentifier","preciseIdentifier":"s:9KKSPlayer8UniEventP"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"parameters":[{"name":"player","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"UniPlayer"},{"type":"text","text":" instance."}]}]},{"name":"event","content":[{"inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"UniEvent"},{"type":"text","text":" that was received."}],"type":"paragraph"}]}],"kind":"parameters"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/player(_:didReceiveOnStallEndedEvent:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Called when the player receives an ","type":"text"},{"code":"UniEvent","type":"codeVoice"},{"type":"text","text":" indicating a stall has ended."}],"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/UniPlayerListener-Implementations"]]},"kind":"symbol","sections":[],"metadata":{"externalID":"s:9KKSPlayer13UniPlayerViewC6player_27didReceiveOnStallEndedEventyAA0bC0C_AA0bK0_ptF","title":"player(_:didReceiveOnStallEndedEvent:)","roleHeading":"Instance Method","symbolKind":"method","role":"symbol","modules":[{"name":"BVPlayer","relatedModules":["KKSPlayer"]}],"extendedModule":"KKSPlayer","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"player","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","text":"UniPlayer","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didReceiveOnStallEndedEvent","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:9KKSPlayer8UniEventP","text":"UniEvent","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniPlayerView"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView","role":"symbol","abstract":[],"navigatorTitle":[{"text":"UniPlayerView","kind":"identifier"}],"type":"topic","title":"UniPlayerView","url":"\/documentation\/kksplayer\/uniplayerview","kind":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView/player(_:didReceiveOnStallEndedEvent:)":{"kind":"symbol","url":"\/documentation\/kksplayer\/uniplayerview\/player(_:didreceiveonstallendedevent:)","title":"player(_:didReceiveOnStallEndedEvent:)","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/player(_:didReceiveOnStallEndedEvent:)","abstract":[{"text":"Called when the player receives an ","type":"text"},{"code":"UniEvent","type":"codeVoice"},{"text":" indicating a stall has ended.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"player","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","text":"UniPlayer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didReceiveOnStallEndedEvent","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UniEvent","kind":"typeIdentifier","preciseIdentifier":"s:9KKSPlayer8UniEventP"},{"text":")","kind":"text"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView/UniPlayerListener-Implementations":{"role":"collectionGroup","type":"topic","url":"\/documentation\/kksplayer\/uniplayerview\/uniplayerlistener-implementations","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/UniPlayerListener-Implementations","title":"UniPlayerListener Implementations","kind":"article","abstract":[]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer":{"url":"\/documentation\/kksplayer\/uniplayer","title":"UniPlayer","abstract":[{"text":"An object that provides the interface to control the player’s transport behavior.","type":"text"}],"role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer","navigatorTitle":[{"kind":"identifier","text":"UniPlayer"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UniPlayer","kind":"identifier"}],"kind":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","abstract":[{"text":"BlendVision One iOS Player SDK","type":"text"}],"title":"BVPlayer","url":"\/documentation\/kksplayer","kind":"symbol","role":"collection"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniEvent":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniEvent","navigatorTitle":[{"text":"UniEvent","kind":"identifier"}],"title":"UniEvent","role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/kksplayer\/unievent","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UniEvent","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerView\/title","op":"replace","value":"UniPlayerView"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerView\/fragments","op":"replace","value":[{"kind":"identifier","text":"UniPlayerView"}]},{"op":"replace","value":"UniPlayer","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/title"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/fragments","value":[{"text":"UniPlayer","kind":"identifier"}]}]}]}