{"sections":[],"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/source(_:didReceiveSourceErrorEvent:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Inherited from "},{"code":"UniSourceListener.source(_:didReceiveSourceErrorEvent:)","type":"codeVoice"},{"text":".","type":"text"}],"metadata":{"modules":[{"relatedModules":["KKSPlayer"],"name":"BVPlayer"}],"extendedModule":"KKSPlayer","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"source"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UniSource","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniSource"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveSourceErrorEvent"},{"text":": ","kind":"text"},{"text":"UniSourceErrorEvent","preciseIdentifier":"s:9KKSPlayer19UniSourceErrorEventC","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"s:9KKSPlayer13UniPlayerViewC6source_26didReceiveSourceErrorEventyAA0bH0C_AA0bhiJ0CtF","symbolKind":"method","title":"source(_:didReceiveSourceErrorEvent:)","roleHeading":"Instance Method","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/UniSourceListener-Implementations"]]},"variants":[{"paths":["\/documentation\/kksplayer\/uniplayerview\/source(_:didreceivesourceerrorevent:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"source"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"source","kind":"internalParam"},{"kind":"text","text":": "},{"text":"UniSource","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniSource","kind":"typeIdentifier","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSource"},{"kind":"text","text":", "},{"text":"didReceiveSourceErrorEvent","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"event"},{"kind":"text","text":": "},{"preciseIdentifier":"s:9KKSPlayer19UniSourceErrorEventC","text":"UniSourceErrorEvent","kind":"typeIdentifier","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceErrorEvent"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSource":{"role":"symbol","title":"UniSource","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSource","url":"\/documentation\/kksplayer\/unisource","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"UniSource","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UniSource","kind":"identifier"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","abstract":[{"text":"BlendVision One iOS Player SDK","type":"text"}],"title":"BVPlayer","url":"\/documentation\/kksplayer","kind":"symbol","role":"collection"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView/UniSourceListener-Implementations":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/UniSourceListener-Implementations","type":"topic","abstract":[],"role":"collectionGroup","kind":"article","title":"UniSourceListener Implementations","url":"\/documentation\/kksplayer\/uniplayerview\/unisourcelistener-implementations"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSourceErrorEvent":{"type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceErrorEvent","navigatorTitle":[{"kind":"identifier","text":"UniSourceErrorEvent"}],"title":"UniSourceErrorEvent","url":"\/documentation\/kksplayer\/unisourceerrorevent","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniSourceErrorEvent"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniPlayerView"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView","role":"symbol","abstract":[],"navigatorTitle":[{"text":"UniPlayerView","kind":"identifier"}],"type":"topic","title":"UniPlayerView","url":"\/documentation\/kksplayer\/uniplayerview","kind":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView/source(_:didReceiveSourceErrorEvent:)":{"title":"source(_:didReceiveSourceErrorEvent:)","url":"\/documentation\/kksplayer\/uniplayerview\/source(_:didreceivesourceerrorevent:)","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView\/source(_:didReceiveSourceErrorEvent:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"source","kind":"identifier"},{"kind":"text","text":"("},{"text":"UniSource","kind":"typeIdentifier","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniSource"},{"kind":"text","text":", "},{"text":"didReceiveSourceErrorEvent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UniSourceErrorEvent","preciseIdentifier":"s:9KKSPlayer19UniSourceErrorEventC","kind":"typeIdentifier"},{"text":")","kind":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSource\/title","op":"replace","value":"UniSource"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSource\/fragments","value":[{"kind":"identifier","text":"UniSource"}],"op":"replace"},{"value":"UniPlayerView","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerView\/title","op":"replace"},{"value":[{"kind":"identifier","text":"UniPlayerView"}],"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerView\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}