{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayerView","text":"UniPlayerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveSettingPressed"},{"kind":"text","text":" "},{"kind":"internalParam","text":"event"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniUIEvent","preciseIdentifier":"s:9KKSPlayer10UniUIEventC","text":"UniUIEvent"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/kksplayer\/uniplayerviewcontroller\/playerview(_:didreceivesettingpressed:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController\/playerView(_:didReceiveSettingPressed:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UniUserInterfaceListener.playerView(_:didReceiveSettingPressed:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"playerView(_:didReceiveSettingPressed:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UniPlayerView","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveSettingPressed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UniUIEvent","preciseIdentifier":"s:9KKSPlayer10UniUIEventC"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:9KKSPlayer23UniPlayerViewControllerC06playerD0_24didReceiveSettingPressedyAA0bcD0C_AA0B7UIEventCtF","extendedModule":"KKSPlayer","modules":[{"name":"KKSPlayer"}]},"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController\/UniUserInterfaceListener-Implementations"]]},"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerViewController/playerView(_:didReceiveSettingPressed:)":{"role":"symbol","title":"playerView(_:didReceiveSettingPressed:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UniPlayerView","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveSettingPressed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UniUIEvent","preciseIdentifier":"s:9KKSPlayer10UniUIEventC"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController\/playerView(_:didReceiveSettingPressed:)","kind":"symbol","type":"topic","url":"\/documentation\/kksplayer\/uniplayerviewcontroller\/playerview(_:didreceivesettingpressed:)"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerViewController/UniUserInterfaceListener-Implementations":{"role":"collectionGroup","title":"UniUserInterfaceListener Implementations","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController\/UniUserInterfaceListener-Implementations","kind":"article","type":"topic","url":"\/documentation\/kksplayer\/uniplayerviewcontroller\/uniuserinterfacelistener-implementations"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerViewController":{"role":"symbol","title":"UniPlayerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniPlayerViewController"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UniPlayerViewController"}],"url":"\/documentation\/kksplayer\/uniplayerviewcontroller"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView":{"role":"symbol","title":"UniPlayerView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniPlayerView"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UniPlayerView"}],"url":"\/documentation\/kksplayer\/uniplayerview"},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"role":"collection","title":"KKSPlayer","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","kind":"symbol","type":"topic","url":"\/documentation\/kksplayer"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniUIEvent":{"role":"symbol","title":"UniUIEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniUIEvent"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniUIEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UniUIEvent"}],"url":"\/documentation\/kksplayer\/uniuievent"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerViewController\/title","value":"UniPlayerViewController"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerViewController\/fragments","value":[{"kind":"identifier","text":"UniPlayerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerView\/title","value":"UniPlayerView"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerView\/fragments","value":[{"kind":"identifier","text":"UniPlayerView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}