{"sections":[],"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController\/playerView(_:didReceivePictureInPictureExit:)","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"BVPlayer","relatedModules":["KKSPlayer"]}],"roleHeading":"Instance Method","extendedModule":"KKSPlayer","symbolKind":"method","role":"symbol","title":"playerView(_:didReceivePictureInPictureExit:)","externalID":"s:9KKSPlayer24UniUserInterfaceListenerPAAE10playerView_019didReceivePictureInJ4ExityAA0b6PlayerG0C_AA0jkjL5EventCtF::SYNTHESIZED::c:@M@KKSPlayer@objc(cs)UniPlayerViewController","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"playerView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayerView","text":"UniPlayerView"},{"text":", ","kind":"text"},{"text":"didReceivePictureInPictureExit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PictureInPictureExitEvent","kind":"typeIdentifier","preciseIdentifier":"s:9KKSPlayer09PictureInB9ExitEventC"},{"kind":"text","text":")"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController\/UniUserInterfaceListener-Implementations"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"UniUserInterfaceListener.playerView(_:didReceivePictureInPictureExit:)"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerView"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"view","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UniPlayerView","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceivePictureInPictureExit"},{"text":" ","kind":"text"},{"text":"event","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/PictureInPictureExitEvent","preciseIdentifier":"s:9KKSPlayer09PictureInB9ExitEventC","text":"PictureInPictureExitEvent"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/kksplayer\/uniplayerviewcontroller\/playerview(_:didreceivepictureinpictureexit:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","abstract":[{"text":"BlendVision One iOS Player SDK","type":"text"}],"title":"BVPlayer","url":"\/documentation\/kksplayer","kind":"symbol","role":"collection"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerViewController":{"type":"topic","abstract":[],"title":"UniPlayerViewController","url":"\/documentation\/kksplayer\/uniplayerviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniPlayerViewController"}],"navigatorTitle":[{"text":"UniPlayerViewController","kind":"identifier"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController","role":"symbol","kind":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerViewController/playerView(_:didReceivePictureInPictureExit:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playerView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayerView","text":"UniPlayerView"},{"kind":"text","text":", "},{"text":"didReceivePictureInPictureExit","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:9KKSPlayer09PictureInB9ExitEventC","text":"PictureInPictureExitEvent"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController\/playerView(_:didReceivePictureInPictureExit:)","url":"\/documentation\/kksplayer\/uniplayerviewcontroller\/playerview(_:didreceivepictureinpictureexit:)","title":"playerView(_:didReceivePictureInPictureExit:)","kind":"symbol","role":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerViewController/UniUserInterfaceListener-Implementations":{"title":"UniUserInterfaceListener Implementations","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController\/UniUserInterfaceListener-Implementations","url":"\/documentation\/kksplayer\/uniplayerviewcontroller\/uniuserinterfacelistener-implementations","abstract":[],"kind":"article","type":"topic","role":"collectionGroup"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniPlayerView"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView","role":"symbol","abstract":[],"navigatorTitle":[{"text":"UniPlayerView","kind":"identifier"}],"type":"topic","title":"UniPlayerView","url":"\/documentation\/kksplayer\/uniplayerview","kind":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/PictureInPictureExitEvent":{"type":"topic","url":"\/documentation\/kksplayer\/pictureinpictureexitevent","navigatorTitle":[{"text":"PictureInPictureExitEvent","kind":"identifier"}],"title":"PictureInPictureExitEvent","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PictureInPictureExitEvent","kind":"identifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/PictureInPictureExitEvent","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerViewController\/title","value":"UniPlayerViewController"},{"value":[{"text":"UniPlayerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerViewController\/fragments"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerView\/title","op":"replace","value":"UniPlayerView"},{"value":[{"kind":"identifier","text":"UniPlayerView"}],"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerView\/fragments"}]}]}