{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kksplayer\/uniplayerviewcontroller\/playerview(_:didreceivecontrolviewchanged:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController\/playerView(_:didReceiveControlViewChanged:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController\/UniUserInterfaceListener-Implementations"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"UniUserInterfaceListener.playerView(_:didReceiveControlViewChanged:)","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","sections":[],"metadata":{"externalID":"s:9KKSPlayer23UniPlayerViewControllerC06playerD0_017didReceiveControlD7ChangedyAA0bcD0C_AA0bidJ5EventCtF","title":"playerView(_:didReceiveControlViewChanged:)","roleHeading":"Instance Method","symbolKind":"method","extendedModule":"KKSPlayer","role":"symbol","modules":[{"relatedModules":["KKSPlayer"],"name":"BVPlayer"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerView"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayerView","text":"UniPlayerView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveControlViewChanged"},{"kind":"text","text":": "},{"text":"UniControlViewChangedEvent","preciseIdentifier":"s:9KKSPlayer26UniControlViewChangedEventC","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"playerView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"view","kind":"internalParam"},{"kind":"text","text":": "},{"text":"UniPlayerView","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView","kind":"typeIdentifier","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayerView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceiveControlViewChanged"},{"kind":"text","text":" "},{"text":"event","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9KKSPlayer26UniControlViewChangedEventC","text":"UniControlViewChangedEvent","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniControlViewChangedEvent","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerViewController/playerView(_:didReceiveControlViewChanged:)":{"kind":"symbol","url":"\/documentation\/kksplayer\/uniplayerviewcontroller\/playerview(_:didreceivecontrolviewchanged:)","title":"playerView(_:didReceiveControlViewChanged:)","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController\/playerView(_:didReceiveControlViewChanged:)","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playerView"},{"text":"(","kind":"text"},{"text":"UniPlayerView","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayerView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveControlViewChanged"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9KKSPlayer26UniControlViewChangedEventC","kind":"typeIdentifier","text":"UniControlViewChangedEvent"},{"text":")","kind":"text"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","abstract":[{"text":"BlendVision One iOS Player SDK","type":"text"}],"title":"BVPlayer","url":"\/documentation\/kksplayer","kind":"symbol","role":"collection"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniControlViewChangedEvent":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UniControlViewChangedEvent","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniControlViewChangedEvent","type":"topic","role":"symbol","abstract":[],"title":"UniControlViewChangedEvent","navigatorTitle":[{"text":"UniControlViewChangedEvent","kind":"identifier"}],"url":"\/documentation\/kksplayer\/unicontrolviewchangedevent"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerViewController":{"type":"topic","abstract":[],"title":"UniPlayerViewController","url":"\/documentation\/kksplayer\/uniplayerviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniPlayerViewController"}],"navigatorTitle":[{"text":"UniPlayerViewController","kind":"identifier"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController","role":"symbol","kind":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniPlayerView"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView","role":"symbol","abstract":[],"navigatorTitle":[{"text":"UniPlayerView","kind":"identifier"}],"type":"topic","title":"UniPlayerView","url":"\/documentation\/kksplayer\/uniplayerview","kind":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerViewController/UniUserInterfaceListener-Implementations":{"title":"UniUserInterfaceListener Implementations","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController\/UniUserInterfaceListener-Implementations","url":"\/documentation\/kksplayer\/uniplayerviewcontroller\/uniuserinterfacelistener-implementations","abstract":[],"kind":"article","type":"topic","role":"collectionGroup"}},"variantOverrides":[{"patch":[{"op":"replace","value":"UniPlayerViewController","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerViewController\/title"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerViewController\/fragments","value":[{"text":"UniPlayerViewController","kind":"identifier"}],"op":"replace"},{"value":"UniPlayerView","op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerView\/title"},{"op":"replace","value":[{"text":"UniPlayerView","kind":"identifier"}],"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerView\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}