{"variants":[{"paths":["\/documentation\/kksplayer\/uniplayerviewcontroller\/playerview(_:didreceivesharepressed:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController\/playerView(_:didReceiveSharePressed:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UniUserInterfaceListener.playerView(_:didReceiveSharePressed:)"},{"text":".","type":"text"}],"kind":"symbol","metadata":{"extendedModule":"KKSPlayer","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerView"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayerView","text":"UniPlayerView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceiveSharePressed"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9KKSPlayer20UniSharePressedEventC","text":"UniSharePressedEvent","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"s:9KKSPlayer24UniUserInterfaceListenerPAAE10playerView_22didReceiveSharePressedyAA0b6PlayerG0C_AA0bjK5EventCtF::SYNTHESIZED::c:@M@KKSPlayer@objc(cs)UniPlayerViewController","modules":[{"name":"KKSPlayer"}],"title":"playerView(_:didReceiveSharePressed:)","roleHeading":"Instance Method","symbolKind":"method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerView"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"view"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView","text":"UniPlayerView","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayerView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveSharePressed"},{"text":" ","kind":"text"},{"text":"event","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSharePressedEvent","kind":"typeIdentifier","preciseIdentifier":"s:9KKSPlayer20UniSharePressedEventC","text":"UniSharePressedEvent"},{"text":")","kind":"text"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController\/UniUserInterfaceListener-Implementations"]]},"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerViewController/playerView(_:didReceiveSharePressed:)":{"url":"\/documentation\/kksplayer\/uniplayerviewcontroller\/playerview(_:didreceivesharepressed:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController\/playerView(_:didReceiveSharePressed:)","role":"symbol","title":"playerView(_:didReceiveSharePressed:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UniPlayerView","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayerView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didReceiveSharePressed","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:9KKSPlayer20UniSharePressedEventC","text":"UniSharePressedEvent"},{"kind":"text","text":")"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSharePressedEvent":{"type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSharePressedEvent","url":"\/documentation\/kksplayer\/unisharepressedevent","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UniSharePressedEvent","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"UniSharePressedEvent","kind":"identifier"}],"title":"UniSharePressedEvent"},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","role":"collection","url":"\/documentation\/kksplayer","kind":"symbol","title":"KKSPlayer","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerViewController/UniUserInterfaceListener-Implementations":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController\/UniUserInterfaceListener-Implementations","role":"collectionGroup","abstract":[],"title":"UniUserInterfaceListener Implementations","type":"topic","kind":"article","url":"\/documentation\/kksplayer\/uniplayerviewcontroller\/uniuserinterfacelistener-implementations"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniPlayerView"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UniPlayerView"}],"url":"\/documentation\/kksplayer\/uniplayerview","type":"topic","abstract":[],"title":"UniPlayerView"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerViewController":{"title":"UniPlayerViewController","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"UniPlayerViewController","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UniPlayerViewController"}],"url":"\/documentation\/kksplayer\/uniplayerviewcontroller","type":"topic","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"UniPlayerView","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerView\/title"},{"value":[{"text":"UniPlayerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerViewController\/title","value":"UniPlayerViewController"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerViewController\/fragments","value":[{"text":"UniPlayerViewController","kind":"identifier"}],"op":"replace"}]}]}