{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniControllerPlayerView","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniControllerPlayerView","text":"UniControllerPlayerView"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/kksplayer\/uniplayerviewcontroller\/playerview"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController\/playerView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The player view will be available after viewDidLoad()"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UniControllerPlayerView","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniControllerPlayerView"},{"kind":"text","text":"?"}],"title":"playerView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:9KKSPlayer23UniPlayerViewControllerC06playerD0AA0becD0CSgvp","modules":[{"name":"KKSPlayer"}]},"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController"]]},"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"role":"collection","title":"KKSPlayer","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","kind":"symbol","type":"topic","url":"\/documentation\/kksplayer"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerViewController/playerView":{"role":"symbol","title":"playerView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UniControllerPlayerView","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniControllerPlayerView"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The player view will be available after viewDidLoad()"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController\/playerView","kind":"symbol","type":"topic","url":"\/documentation\/kksplayer\/uniplayerviewcontroller\/playerview"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniControllerPlayerView":{"role":"symbol","title":"UniControllerPlayerView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniControllerPlayerView"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniControllerPlayerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UniControllerPlayerView"}],"url":"\/documentation\/kksplayer\/unicontrollerplayerview"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerViewController":{"role":"symbol","title":"UniPlayerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniPlayerViewController"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UniPlayerViewController"}],"url":"\/documentation\/kksplayer\/uniplayerviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniControllerPlayerView\/title","value":"UniControllerPlayerView"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniControllerPlayerView\/fragments","value":[{"kind":"identifier","text":"UniControllerPlayerView"}]},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerViewController\/title","value":"UniPlayerViewController"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerViewController\/fragments","value":[{"kind":"identifier","text":"UniPlayerViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}