{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UniPlayerView","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayerView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceivePictureInPictureExited"},{"kind":"text","text":": "},{"text":"PictureInPictureExitedEvent","kind":"typeIdentifier","preciseIdentifier":"s:9KKSPlayer09PictureInB11ExitedEventC"},{"text":")","kind":"text"}],"role":"symbol","externalID":"s:9KKSPlayer24UniUserInterfaceListenerPAAE10playerView_019didReceivePictureInJ6ExitedyAA0b6PlayerG0C_AA0jkjL5EventCtF::SYNTHESIZED::c:@M@KKSPlayer@objc(cs)UniPlayerViewController","extendedModule":"KKSPlayer","title":"playerView(_:didReceivePictureInPictureExited:)","modules":[{"relatedModules":["KKSPlayer"],"name":"BVPlayer"}],"roleHeading":"Instance Method","symbolKind":"method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController\/playerView(_:didReceivePictureInPictureExited:)"},"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController\/UniUserInterfaceListener-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"code":"UniUserInterfaceListener.playerView(_:didReceivePictureInPictureExited:)","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kksplayer\/uniplayerviewcontroller\/playerview(_:didreceivepictureinpictureexited:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"playerView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"view","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayerView","text":"UniPlayerView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didReceivePictureInPictureExited","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"event"},{"kind":"text","text":": "},{"preciseIdentifier":"s:9KKSPlayer09PictureInB11ExitedEventC","text":"PictureInPictureExitedEvent","kind":"typeIdentifier","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/PictureInPictureExitedEvent"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerViewController":{"type":"topic","abstract":[],"title":"UniPlayerViewController","url":"\/documentation\/kksplayer\/uniplayerviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniPlayerViewController"}],"navigatorTitle":[{"text":"UniPlayerViewController","kind":"identifier"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController","role":"symbol","kind":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/PictureInPictureExitedEvent":{"role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/PictureInPictureExitedEvent","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PictureInPictureExitedEvent"}],"navigatorTitle":[{"text":"PictureInPictureExitedEvent","kind":"identifier"}],"title":"PictureInPictureExitedEvent","type":"topic","abstract":[],"url":"\/documentation\/kksplayer\/pictureinpictureexitedevent"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerViewController/playerView(_:didReceivePictureInPictureExited:)":{"abstract":[],"role":"symbol","type":"topic","title":"playerView(_:didReceivePictureInPictureExited:)","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController\/playerView(_:didReceivePictureInPictureExited:)","kind":"symbol","url":"\/documentation\/kksplayer\/uniplayerviewcontroller\/playerview(_:didreceivepictureinpictureexited:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"playerView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayerView","text":"UniPlayerView"},{"kind":"text","text":", "},{"text":"didReceivePictureInPictureExited","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PictureInPictureExitedEvent","preciseIdentifier":"s:9KKSPlayer09PictureInB11ExitedEventC"},{"text":")","kind":"text"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","abstract":[{"text":"BlendVision One iOS Player SDK","type":"text"}],"title":"BVPlayer","url":"\/documentation\/kksplayer","kind":"symbol","role":"collection"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerViewController/UniUserInterfaceListener-Implementations":{"title":"UniUserInterfaceListener Implementations","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController\/UniUserInterfaceListener-Implementations","url":"\/documentation\/kksplayer\/uniplayerviewcontroller\/uniuserinterfacelistener-implementations","abstract":[],"kind":"article","type":"topic","role":"collectionGroup"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniPlayerView"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView","role":"symbol","abstract":[],"navigatorTitle":[{"text":"UniPlayerView","kind":"identifier"}],"type":"topic","title":"UniPlayerView","url":"\/documentation\/kksplayer\/uniplayerview","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerViewController\/title","op":"replace","value":"UniPlayerViewController"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerViewController\/fragments","value":[{"text":"UniPlayerViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerView\/title","op":"replace","value":"UniPlayerView"},{"value":[{"kind":"identifier","text":"UniPlayerView"}],"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerView\/fragments"}]}]}