{"sections":[],"variants":[{"paths":["\/documentation\/kksplayer\/uniplayerviewcontroller\/player"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"player","kind":"identifier"},{"kind":"text","text":": "},{"text":"UniPlayer","kind":"typeIdentifier","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer"},{"text":"?","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController\/player"},"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController"]]},"metadata":{"title":"player","modules":[{"name":"KKSPlayer"}],"symbolKind":"property","roleHeading":"Instance Property","externalID":"s:9KKSPlayer23UniPlayerViewControllerC6playerAA0bC0CSgvp","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"player"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","kind":"typeIdentifier","text":"UniPlayer"},{"text":"?","kind":"text"}],"role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UniPlayer","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"UniPlayer"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer","type":"topic","url":"\/documentation\/kksplayer\/uniplayer","title":"UniPlayer","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"An object that provides the interface to control the player’s transport behavior."}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerViewController":{"title":"UniPlayerViewController","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"UniPlayerViewController","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UniPlayerViewController"}],"url":"\/documentation\/kksplayer\/uniplayerviewcontroller","type":"topic","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerViewController/player":{"url":"\/documentation\/kksplayer\/uniplayerviewcontroller\/player","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"player"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","text":"UniPlayer"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController\/player","type":"topic","role":"symbol","title":"player","kind":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","role":"collection","url":"\/documentation\/kksplayer","kind":"symbol","title":"KKSPlayer","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"UniPlayer","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/title"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/fragments","op":"replace","value":[{"text":"UniPlayer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerViewController\/title","value":"UniPlayerViewController"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerViewController\/fragments","value":[{"kind":"identifier","text":"UniPlayerViewController"}]}]}]}