{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationControllerDidDismiss"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"presentationController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIPresentationController","preciseIdentifier":"c:objc(cs)UIPresentationController"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/kksplayer\/uniplayerviewcontroller\/presentationcontrollerdiddismiss(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/kksplayer\/uniplayerviewcontroller\/presentationcontrollerdiddismiss(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController\/presentationControllerDidDismiss(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIAdaptivePresentationControllerDelegate.presentationControllerDidDismiss(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationControllerDidDismiss"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIPresentationController","preciseIdentifier":"c:objc(cs)UIPresentationController"},{"kind":"text","text":")"}],"title":"presentationControllerDidDismiss(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@KKSPlayer@objc(cs)UniPlayerViewController(im)presentationControllerDidDismiss:","modules":[{"name":"KKSPlayer"}],"navigatorTitle":[{"kind":"identifier","text":"presentationControllerDidDismiss:"}]},"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController\/UIAdaptivePresentationControllerDelegate-Implementations"]]},"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerViewController":{"role":"symbol","title":"UniPlayerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniPlayerViewController"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UniPlayerViewController"}],"url":"\/documentation\/kksplayer\/uniplayerviewcontroller"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerViewController/UIAdaptivePresentationControllerDelegate-Implementations":{"role":"collectionGroup","title":"UIAdaptivePresentationControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController\/UIAdaptivePresentationControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/kksplayer\/uniplayerviewcontroller\/uiadaptivepresentationcontrollerdelegate-implementations"},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"role":"collection","title":"KKSPlayer","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","kind":"symbol","type":"topic","url":"\/documentation\/kksplayer"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerViewController/presentationControllerDidDismiss(_:)":{"role":"symbol","title":"presentationControllerDidDismiss(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationControllerDidDismiss"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIPresentationController","preciseIdentifier":"c:objc(cs)UIPresentationController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController\/presentationControllerDidDismiss(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"presentationControllerDidDismiss:"}],"url":"\/documentation\/kksplayer\/uniplayerviewcontroller\/presentationcontrollerdiddismiss(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"presentationControllerDidDismiss:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentationControllerDidDismiss:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"presentationControllerDidDismiss:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIPresentationController","preciseIdentifier":"c:objc(cs)UIPresentationController"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"presentationController"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerViewController\/title","value":"UniPlayerViewController"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerViewController\/fragments","value":[{"kind":"identifier","text":"UniPlayerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerViewController~1presentationControllerDidDismiss(_:)\/title","value":"presentationControllerDidDismiss:"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerViewController~1presentationControllerDidDismiss(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentationControllerDidDismiss:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}