{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController\/UIAdaptivePresentationControllerDelegate-Implementations","interfaceLanguage":"swift"},"metadata":{"role":"collectionGroup","title":"UIAdaptivePresentationControllerDelegate Implementations","modules":[{"name":"BVPlayer"}]},"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController"]]},"kind":"article","variants":[{"paths":["\/documentation\/kksplayer\/uniplayerviewcontroller\/uiadaptivepresentationcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/kksplayer\/uniplayerviewcontroller\/uiadaptivepresentationcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController\/presentationControllerDidDismiss(_:)"],"generated":true}],"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","abstract":[{"text":"BlendVision One iOS Player SDK","type":"text"}],"title":"BVPlayer","url":"\/documentation\/kksplayer","kind":"symbol","role":"collection"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerViewController":{"type":"topic","abstract":[],"title":"UniPlayerViewController","url":"\/documentation\/kksplayer\/uniplayerviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniPlayerViewController"}],"navigatorTitle":[{"text":"UniPlayerViewController","kind":"identifier"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController","role":"symbol","kind":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerViewController/presentationControllerDidDismiss(_:)":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController\/presentationControllerDidDismiss(_:)","abstract":[],"title":"presentationControllerDidDismiss(_:)","url":"\/documentation\/kksplayer\/uniplayerviewcontroller\/presentationcontrollerdiddismiss(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"presentationControllerDidDismiss"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIPresentationController","text":"UIPresentationController"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"presentationControllerDidDismiss:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"generated":true,"identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController\/presentationControllerDidDismiss(_:)"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":"UniPlayerViewController","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerViewController\/title"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerViewController\/fragments","value":[{"text":"UniPlayerViewController","kind":"identifier"}],"op":"replace"},{"value":"presentationControllerDidDismiss:","op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerViewController~1presentationControllerDidDismiss(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerViewController~1presentationControllerDidDismiss(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"presentationControllerDidDismiss:","kind":"identifier"}]}]}]}