{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"player"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","text":"UniPlayer","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer"},{"text":")","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSettingViewController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kksplayer\/unisettingviewcontroller\/init(player:)"]}],"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"player","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UniPlayer","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer"},{"text":")","kind":"text"}],"roleHeading":"Initializer","modules":[{"name":"KKSPlayer"}],"symbolKind":"init","externalID":"s:9KKSPlayer24UniSettingViewControllerC6playerAcA0B6PlayerC_tcfc","title":"init(player:)","role":"symbol"},"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSettingViewController\/init(player:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","role":"collection","url":"\/documentation\/kksplayer","kind":"symbol","title":"KKSPlayer","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UniPlayer","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"UniPlayer"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer","type":"topic","url":"\/documentation\/kksplayer\/uniplayer","title":"UniPlayer","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"An object that provides the interface to control the player’s transport behavior."}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSettingViewController/init(player:)":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSettingViewController\/init(player:)","role":"symbol","title":"init(player:)","kind":"symbol","url":"\/documentation\/kksplayer\/unisettingviewcontroller\/init(player:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"player"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","text":"UniPlayer"},{"kind":"text","text":")"}],"type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSettingViewController":{"title":"UniSettingViewController","role":"symbol","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSettingViewController","url":"\/documentation\/kksplayer\/unisettingviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniSettingViewController"}],"navigatorTitle":[{"kind":"identifier","text":"UniSettingViewController"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/title","value":"UniPlayer"},{"value":[{"kind":"identifier","text":"UniPlayer"}],"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/fragments","op":"replace"},{"op":"replace","value":"UniSettingViewController","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSettingViewController\/title"},{"op":"replace","value":[{"text":"UniSettingViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSettingViewController\/fragments"}]}]}