{"sections":[],"variants":[{"paths":["\/documentation\/kksplayer"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/kksplayer"]}],"metadata":{"title":"KKSPlayer","role":"collection","symbolKind":"module","externalID":"KKSPlayer","modules":[{"name":"KKSPlayer"}],"roleHeading":"Framework"},"kind":"symbol","hierarchy":{"paths":[[]]},"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/Analytics","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManagerOptions","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/PLLogPitch","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/PLPrioritizingLogSystem","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/PictureInPictureEnterEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/PictureInPictureEnteredEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/PictureInPictureExitEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/PictureInPictureExitedEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/RemoteControlConfig","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/SeekPosition","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniAdaptationConfig","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniApiAudioMuteChangedLogEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniApiAudioTrackChangedLogEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniApiAudioVolumeChangedLogEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniApiForwardLogEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniApiLoopChangedEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniApiPauseLogEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniApiPlayLogEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniApiRewindLogEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniApiSeekLogEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniApiSpeedChangedLogEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniApiSubtitleChangedLogEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniApiVideoQualityChangedLogEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniAudioChangedEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniAudioMuteChangedLogEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniAudioTrack","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniAudioVolumeChangedEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniAudioVolumeChangedLogEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniBufferConfig","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniBufferMediaTypeConfig","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniControlViewChangedEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniControllerPlayerView","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniDrmConfig","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniFairPlayConfig","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniInfoPressedEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniLoadedTimeRangeChangedEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniLogEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniLogger","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniLoopChangedEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniLoopChangedLogEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniMutedEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPausedEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlaybackBeganLogEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlaybackBufferBeganLogEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlaybackBufferEndedLogEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlaybackConfig","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlaybackEndedLogEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlaybackErrorLogEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlaybackFinishedEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlaybackPausedLogEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlaybackSeekBeganLogEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlaybackSeekEndedLogEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlaybackSpeedChangedEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlaybackStartedLogEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerConfig","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerControlView","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerErrorEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerFactory","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerLoadingLogEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerStartedLogEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayingEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlaylist","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniReadyEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSeekEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSeekedEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSettingPressedEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSettingViewController","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSharePressedEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSheetPresentationController","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSource","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceConfig","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceErrorEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceLoadEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceLoadedEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceUnloadEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceUnloadedEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSpeedChangedLogEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniStallEndedEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniStallStartedEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniStyleConfig","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSubtitleChangedEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSubtitleTrack","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniThumbnailTrack","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTimeChangedEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTimeShiftEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTimeShiftedEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrack","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTweaksConfig","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniUIEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniUIStyleConfig","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniUITableViewController","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniUnmutedEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniVideoAudioTrackChangedLogEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniVideoPlaybackQualityChangedEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniVideoQualityChangedLogEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniVideoSubtitleChangedLogEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/WidevineConfig"],"title":"Classes"},{"title":"Protocols","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManagerListener","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniEvent","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniFullscreenHandler","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniLoggerListener","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewControllerDelegate","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceListener","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrackProtocol","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniUIEventProtocol","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniUserInterfaceListener"]},{"identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastConstant","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastImage","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastOptions","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/PictureInPictureConfig","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/PlayerViewConfig","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/PosterViewConfig","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniCommonProperty","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniControlViewConfig","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniDeficiencyData","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniThumbnail","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniVideoQuality"],"title":"Structures"},{"title":"Variables","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/pLog"]},{"identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/AnalyticsField","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/KKSPlayerModuleInfo","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/PLLogSeverity","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/PlayerViewStyle","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/RemoteControlType","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/SourceErrorCode","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniEventName","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniFeature","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerErrorCode","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceType","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniUIEventName"],"title":"Enumerations"},{"identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/Foundation","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/Swift","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UIKit"],"title":"Extended Modules"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"content","content":[{"text":"Overview","type":"heading","anchor":"Overview","level":2}]}],"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSettingPressedEvent":{"role":"symbol","url":"\/documentation\/kksplayer\/unisettingpressedevent","navigatorTitle":[{"text":"UniSettingPressedEvent","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSettingPressedEvent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UniSettingPressedEvent","kind":"identifier"}],"title":"UniSettingPressedEvent"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/RemoteControlType":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RemoteControlType","kind":"identifier"}],"abstract":[{"text":"Enumerates the different available remote device types.","type":"text"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/RemoteControlType","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RemoteControlType"}],"type":"topic","title":"RemoteControlType","url":"\/documentation\/kksplayer\/remotecontroltype"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlaybackSpeedChangedEvent":{"kind":"symbol","abstract":[],"title":"UniPlaybackSpeedChangedEvent","url":"\/documentation\/kksplayer\/uniplaybackspeedchangedevent","type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlaybackSpeedChangedEvent","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UniPlaybackSpeedChangedEvent","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"UniPlaybackSpeedChangedEvent"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/PictureInPictureExitEvent":{"role":"symbol","url":"\/documentation\/kksplayer\/pictureinpictureexitevent","navigatorTitle":[{"kind":"identifier","text":"PictureInPictureExitEvent"}],"type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/PictureInPictureExitEvent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PictureInPictureExitEvent","kind":"identifier"}],"title":"PictureInPictureExitEvent"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniInfoPressedEvent":{"navigatorTitle":[{"kind":"identifier","text":"UniInfoPressedEvent"}],"title":"UniInfoPressedEvent","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UniInfoPressedEvent","kind":"identifier"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniInfoPressedEvent","type":"topic","abstract":[],"url":"\/documentation\/kksplayer\/uniinfopressedevent","kind":"symbol","role":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniUnmutedEvent":{"title":"UniUnmutedEvent","type":"topic","url":"\/documentation\/kksplayer\/uniunmutedevent","navigatorTitle":[{"kind":"identifier","text":"UniUnmutedEvent"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniUnmutedEvent"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniUnmutedEvent","abstract":[]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSettingViewController":{"title":"UniSettingViewController","role":"symbol","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSettingViewController","url":"\/documentation\/kksplayer\/unisettingviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniSettingViewController"}],"navigatorTitle":[{"kind":"identifier","text":"UniSettingViewController"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerFactory":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerFactory","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniPlayerFactory"}],"title":"UniPlayerFactory","kind":"symbol","abstract":[],"url":"\/documentation\/kksplayer\/uniplayerfactory","navigatorTitle":[{"text":"UniPlayerFactory","kind":"identifier"}],"type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniControlViewChangedEvent":{"url":"\/documentation\/kksplayer\/unicontrolviewchangedevent","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniControlViewChangedEvent","abstract":[],"kind":"symbol","title":"UniControlViewChangedEvent","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniControlViewChangedEvent"}],"navigatorTitle":[{"kind":"identifier","text":"UniControlViewChangedEvent"}],"type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniUIEventProtocol":{"url":"\/documentation\/kksplayer\/uniuieventprotocol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniUIEventProtocol","abstract":[],"kind":"symbol","title":"UniUIEventProtocol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniUIEventProtocol"}],"navigatorTitle":[{"text":"UniUIEventProtocol","kind":"identifier"}],"type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/PLLogPitch":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/PLLogPitch","title":"PLLogPitch","role":"symbol","url":"\/documentation\/kksplayer\/pllogpitch","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PLLogPitch"}],"kind":"symbol","abstract":[],"navigatorTitle":[{"text":"PLLogPitch","kind":"identifier"}],"type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlaybackPausedLogEvent":{"navigatorTitle":[{"text":"UniPlaybackPausedLogEvent","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniPlaybackPausedLogEvent"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlaybackPausedLogEvent","role":"symbol","title":"UniPlaybackPausedLogEvent","url":"\/documentation\/kksplayer\/uniplaybackpausedlogevent"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSourceType":{"title":"UniSourceType","url":"\/documentation\/kksplayer\/unisourcetype","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"UniSourceType","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"UniSourceType","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceType","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniApiSpeedChangedLogEvent":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniApiSpeedChangedLogEvent","url":"\/documentation\/kksplayer\/uniapispeedchangedlogevent","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"UniApiSpeedChangedLogEvent","kind":"identifier"}],"role":"symbol","title":"UniApiSpeedChangedLogEvent","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniApiSpeedChangedLogEvent"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSubtitleTrack":{"abstract":[],"role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSubtitleTrack","title":"UniSubtitleTrack","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniSubtitleTrack"}],"navigatorTitle":[{"text":"UniSubtitleTrack","kind":"identifier"}],"url":"\/documentation\/kksplayer\/unisubtitletrack","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSourceEvent":{"title":"UniSourceEvent","url":"\/documentation\/kksplayer\/unisourceevent","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UniSourceEvent","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UniSourceEvent"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceEvent","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniEventName":{"role":"symbol","title":"UniEventName","navigatorTitle":[{"text":"UniEventName","kind":"identifier"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniEventName","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UniEventName","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/kksplayer\/unieventname"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPausedEvent":{"title":"UniPausedEvent","type":"topic","url":"\/documentation\/kksplayer\/unipausedevent","navigatorTitle":[{"kind":"identifier","text":"UniPausedEvent"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniPausedEvent"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPausedEvent","abstract":[]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/WidevineConfig":{"navigatorTitle":[{"text":"WidevineConfig","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents a Widevine DRM config."}],"url":"\/documentation\/kksplayer\/widevineconfig","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/WidevineConfig","title":"WidevineConfig","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"WidevineConfig","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/PLLogSeverity":{"navigatorTitle":[{"kind":"identifier","text":"PLLogSeverity"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PLLogSeverity"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/PLLogSeverity","abstract":[],"role":"symbol","title":"PLLogSeverity","url":"\/documentation\/kksplayer\/pllogseverity"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSpeedChangedLogEvent":{"url":"\/documentation\/kksplayer\/unispeedchangedlogevent","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSpeedChangedLogEvent","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UniSpeedChangedLogEvent"}],"role":"symbol","type":"topic","title":"UniSpeedChangedLogEvent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniSpeedChangedLogEvent"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/AnalyticsField":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AnalyticsField","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/AnalyticsField","abstract":[{"type":"text","text":"An enumeration representing the analytics fields used in the application."}],"title":"AnalyticsField","url":"\/documentation\/kksplayer\/analyticsfield","navigatorTitle":[{"kind":"identifier","text":"AnalyticsField"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniUIEventName":{"title":"UniUIEventName","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UniUIEventName","kind":"identifier"}],"url":"\/documentation\/kksplayer\/uniuieventname","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"UniUIEventName","kind":"identifier"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniUIEventName"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/RemoteControlConfig":{"url":"\/documentation\/kksplayer\/remotecontrolconfig","navigatorTitle":[{"text":"RemoteControlConfig","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/RemoteControlConfig","kind":"symbol","title":"RemoteControlConfig","abstract":[{"text":"Contains config values which can be used to alter the behaviour of the player when it comes to remote playback.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RemoteControlConfig"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniEvent":{"abstract":[],"title":"UniEvent","url":"\/documentation\/kksplayer\/unievent","role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniEvent","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniEvent"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UniEvent"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniAudioVolumeChangedEvent":{"abstract":[],"url":"\/documentation\/kksplayer\/uniaudiovolumechangedevent","title":"UniAudioVolumeChangedEvent","navigatorTitle":[{"kind":"identifier","text":"UniAudioVolumeChangedEvent"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniAudioVolumeChangedEvent"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniAudioVolumeChangedEvent","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniFairPlayConfig":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniFairPlayConfig","title":"UniFairPlayConfig","role":"symbol","url":"\/documentation\/kksplayer\/unifairplayconfig","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UniFairPlayConfig","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Represents a FairPlay Streaming DRM config.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"UniFairPlayConfig"}],"type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniAudioTrack":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniAudioTrack"}],"title":"UniAudioTrack","url":"\/documentation\/kksplayer\/uniaudiotrack","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniAudioTrack","abstract":[],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UniAudioTrack"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSeekEvent":{"kind":"symbol","url":"\/documentation\/kksplayer\/uniseekevent","title":"UniSeekEvent","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UniSeekEvent","kind":"identifier"}],"navigatorTitle":[{"text":"UniSeekEvent","kind":"identifier"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSeekEvent","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniApiAudioTrackChangedLogEvent":{"title":"UniApiAudioTrackChangedLogEvent","role":"symbol","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniApiAudioTrackChangedLogEvent","url":"\/documentation\/kksplayer\/uniapiaudiotrackchangedlogevent","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UniApiAudioTrackChangedLogEvent","kind":"identifier"}],"navigatorTitle":[{"text":"UniApiAudioTrackChangedLogEvent","kind":"identifier"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniUserInterfaceListener":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniUserInterfaceListener","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"UniUserInterfaceListener","kind":"identifier"}],"abstract":[{"type":"text","text":"Defines listener methods for all events available for the PlayerView."}],"title":"UniUserInterfaceListener","type":"topic","url":"\/documentation\/kksplayer\/uniuserinterfacelistener","role":"symbol","navigatorTitle":[{"text":"UniUserInterfaceListener","kind":"identifier"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniUIStyleConfig":{"role":"symbol","navigatorTitle":[{"text":"UniUIStyleConfig","kind":"identifier"}],"title":"UniUIStyleConfig","kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniUIStyleConfig","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UniUIStyleConfig","kind":"identifier"}],"url":"\/documentation\/kksplayer\/uniuistyleconfig","abstract":[],"type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniTrack":{"navigatorTitle":[{"kind":"identifier","text":"UniTrack"}],"url":"\/documentation\/kksplayer\/unitrack","type":"topic","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrack","kind":"symbol","title":"UniTrack","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniTrack"}],"role":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSourceUnloadedEvent":{"title":"UniSourceUnloadedEvent","abstract":[],"role":"symbol","url":"\/documentation\/kksplayer\/unisourceunloadedevent","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceUnloadedEvent","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UniSourceUnloadedEvent","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UniSourceUnloadedEvent"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniVideoQualityChangedLogEvent":{"title":"UniVideoQualityChangedLogEvent","navigatorTitle":[{"kind":"identifier","text":"UniVideoQualityChangedLogEvent"}],"url":"\/documentation\/kksplayer\/univideoqualitychangedlogevent","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniVideoQualityChangedLogEvent"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniVideoQualityChangedLogEvent","abstract":[]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniFeature":{"role":"symbol","title":"UniFeature","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"UniFeature","kind":"identifier"}],"url":"\/documentation\/kksplayer\/unifeature","navigatorTitle":[{"text":"UniFeature","kind":"identifier"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniFeature","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerConfig":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerConfig","title":"UniPlayerConfig","role":"symbol","url":"\/documentation\/kksplayer\/uniplayerconfig","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniPlayerConfig"}],"kind":"symbol","abstract":[{"type":"text","text":"Configures a new Player instance. Must not be modified after it was used to create a Player instance."}],"navigatorTitle":[{"kind":"identifier","text":"UniPlayerConfig"}],"type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/PlayerViewStyle":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/PlayerViewStyle","role":"symbol","title":"PlayerViewStyle","type":"topic","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PlayerViewStyle","kind":"identifier"}],"navigatorTitle":[{"text":"PlayerViewStyle","kind":"identifier"}],"url":"\/documentation\/kksplayer\/playerviewstyle"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniLogger":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniLogger"}],"url":"\/documentation\/kksplayer\/unilogger","title":"UniLogger","navigatorTitle":[{"kind":"identifier","text":"UniLogger"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniLogger","abstract":[]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniAudioChangedEvent":{"kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniAudioChangedEvent","type":"topic","role":"symbol","title":"UniAudioChangedEvent","abstract":[],"navigatorTitle":[{"text":"UniAudioChangedEvent","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniAudioChangedEvent"}],"url":"\/documentation\/kksplayer\/uniaudiochangedevent"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlaybackSeekEndedLogEvent":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UniPlaybackSeekEndedLogEvent"}],"type":"topic","role":"symbol","url":"\/documentation\/kksplayer\/uniplaybackseekendedlogevent","title":"UniPlaybackSeekEndedLogEvent","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlaybackSeekEndedLogEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"UniPlaybackSeekEndedLogEvent","kind":"identifier"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniControlViewConfig":{"title":"UniControlViewConfig","role":"symbol","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniControlViewConfig","url":"\/documentation\/kksplayer\/unicontrolviewconfig","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniControlViewConfig"}],"navigatorTitle":[{"kind":"identifier","text":"UniControlViewConfig"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/PictureInPictureEnteredEvent":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/PictureInPictureEnteredEvent","role":"symbol","abstract":[],"title":"PictureInPictureEnteredEvent","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PictureInPictureEnteredEvent"}],"kind":"symbol","url":"\/documentation\/kksplayer\/pictureinpictureenteredevent","navigatorTitle":[{"kind":"identifier","text":"PictureInPictureEnteredEvent"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","role":"collection","url":"\/documentation\/kksplayer","kind":"symbol","title":"KKSPlayer","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniAudioMuteChangedLogEvent":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UniAudioMuteChangedLogEvent","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniAudioMuteChangedLogEvent","navigatorTitle":[{"text":"UniAudioMuteChangedLogEvent","kind":"identifier"}],"title":"UniAudioMuteChangedLogEvent","url":"\/documentation\/kksplayer\/uniaudiomutechangedlogevent","abstract":[],"role":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniAdaptationConfig":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UniAdaptationConfig"}],"title":"UniAdaptationConfig","kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniAdaptationConfig","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UniAdaptationConfig","kind":"identifier"}],"url":"\/documentation\/kksplayer\/uniadaptationconfig","abstract":[{"text":"Contains config values regarding the behaviour of the bitrate adaptation.","type":"text"}],"type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerViewControllerDelegate":{"navigatorTitle":[{"kind":"identifier","text":"UniPlayerViewControllerDelegate"}],"abstract":[],"type":"topic","url":"\/documentation\/kksplayer\/uniplayerviewcontrollerdelegate","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewControllerDelegate","title":"UniPlayerViewControllerDelegate","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"UniPlayerViewControllerDelegate","kind":"identifier"}],"role":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniThumbnail":{"title":"UniThumbnail","abstract":[{"text":"Represents a VTT thumbnail.","type":"text"}],"role":"symbol","url":"\/documentation\/kksplayer\/unithumbnail","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniThumbnail","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"UniThumbnail","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UniThumbnail"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniVideoAudioTrackChangedLogEvent":{"navigatorTitle":[{"text":"UniVideoAudioTrackChangedLogEvent","kind":"identifier"}],"url":"\/documentation\/kksplayer\/univideoaudiotrackchangedlogevent","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniVideoAudioTrackChangedLogEvent","kind":"symbol","type":"topic","role":"symbol","abstract":[],"title":"UniVideoAudioTrackChangedLogEvent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniVideoAudioTrackChangedLogEvent"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniVideoQuality":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"UniVideoQuality","kind":"identifier"}],"type":"topic","title":"UniVideoQuality","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UniVideoQuality"}],"url":"\/documentation\/kksplayer\/univideoquality","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniVideoQuality","kind":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSharePressedEvent":{"type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSharePressedEvent","url":"\/documentation\/kksplayer\/unisharepressedevent","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UniSharePressedEvent","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"UniSharePressedEvent","kind":"identifier"}],"title":"UniSharePressedEvent"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/PosterViewConfig":{"role":"symbol","navigatorTitle":[{"text":"PosterViewConfig","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"PosterViewConfig","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"This config is used to configure the poster view"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/PosterViewConfig","url":"\/documentation\/kksplayer\/posterviewconfig","title":"PosterViewConfig"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlaybackConfig":{"role":"symbol","url":"\/documentation\/kksplayer\/uniplaybackconfig","navigatorTitle":[{"kind":"identifier","text":"UniPlaybackConfig"}],"type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlaybackConfig","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UniPlaybackConfig","kind":"identifier"}],"title":"UniPlaybackConfig"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniStyleConfig":{"title":"UniStyleConfig","url":"\/documentation\/kksplayer\/unistyleconfig","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniStyleConfig"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UniStyleConfig"}],"abstract":[{"type":"text","text":"Contains config values which can be used to alter the visual presentation and behavior of the player UI."}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniStyleConfig","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniApiPauseLogEvent":{"navigatorTitle":[{"kind":"identifier","text":"UniApiPauseLogEvent"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniApiPauseLogEvent","abstract":[],"title":"UniApiPauseLogEvent","url":"\/documentation\/kksplayer\/uniapipauselogevent","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniApiPauseLogEvent"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniUIEvent":{"title":"UniUIEvent","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniUIEvent"}],"kind":"symbol","url":"\/documentation\/kksplayer\/uniuievent","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UniUIEvent"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniUIEvent"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/KKSPlayerVersionString":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/KKSPlayerVersionString","role":"symbol","title":"KKSPlayerVersionString","kind":"symbol","abstract":[{"type":"text","text":"Project version string for KKSPlayer."}],"url":"\/documentation\/kksplayer\/kksplayerversionstring","fragments":[{"text":"KKSPlayerVersionString","kind":"identifier"}],"type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniTimeShiftedEvent":{"role":"symbol","title":"UniTimeShiftedEvent","navigatorTitle":[{"text":"UniTimeShiftedEvent","kind":"identifier"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTimeShiftedEvent","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UniTimeShiftedEvent","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/kksplayer\/unitimeshiftedevent"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniBufferMediaTypeConfig":{"navigatorTitle":[{"text":"UniBufferMediaTypeConfig","kind":"identifier"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniBufferMediaTypeConfig","abstract":[],"title":"UniBufferMediaTypeConfig","url":"\/documentation\/kksplayer\/unibuffermediatypeconfig","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UniBufferMediaTypeConfig","kind":"identifier"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/PictureInPictureExitedEvent":{"navigatorTitle":[{"kind":"identifier","text":"PictureInPictureExitedEvent"}],"title":"PictureInPictureExitedEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PictureInPictureExitedEvent","kind":"identifier"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/PictureInPictureExitedEvent","type":"topic","abstract":[],"url":"\/documentation\/kksplayer\/pictureinpictureexitedevent","kind":"symbol","role":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManagerListener":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManagerListener","url":"\/documentation\/kksplayer\/castmanagerlistener","abstract":[{"type":"text","text":"Listener protocol which can be used to listen to events of the CastManager."}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"CastManagerListener","kind":"identifier"}],"role":"symbol","title":"CastManagerListener","navigatorTitle":[{"kind":"identifier","text":"CastManagerListener"}],"kind":"symbol","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniDeficiencyData":{"abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"UniDeficiencyData","kind":"identifier"}],"navigatorTitle":[{"text":"UniDeficiencyData","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniDeficiencyData","title":"UniDeficiencyData","type":"topic","kind":"symbol","url":"\/documentation\/kksplayer\/unideficiencydata"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniControllerPlayerView":{"url":"\/documentation\/kksplayer\/unicontrollerplayerview","abstract":[],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UniControllerPlayerView","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"UniControllerPlayerView","kind":"identifier"}],"title":"UniControllerPlayerView","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniControllerPlayerView"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniUITableViewController":{"kind":"symbol","navigatorTitle":[{"text":"UniUITableViewController","kind":"identifier"}],"role":"symbol","abstract":[],"title":"UniUITableViewController","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniUITableViewController","type":"topic","url":"\/documentation\/kksplayer\/uniuitableviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniUITableViewController"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniApiSubtitleChangedLogEvent":{"title":"UniApiSubtitleChangedLogEvent","role":"symbol","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniApiSubtitleChangedLogEvent","url":"\/documentation\/kksplayer\/uniapisubtitlechangedlogevent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniApiSubtitleChangedLogEvent"}],"navigatorTitle":[{"text":"UniApiSubtitleChangedLogEvent","kind":"identifier"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlaybackFinishedEvent":{"abstract":[],"url":"\/documentation\/kksplayer\/uniplaybackfinishedevent","title":"UniPlaybackFinishedEvent","navigatorTitle":[{"kind":"identifier","text":"UniPlaybackFinishedEvent"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniPlaybackFinishedEvent"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlaybackFinishedEvent","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniAudioVolumeChangedLogEvent":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniAudioVolumeChangedLogEvent","title":"UniAudioVolumeChangedLogEvent","navigatorTitle":[{"kind":"identifier","text":"UniAudioVolumeChangedLogEvent"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniAudioVolumeChangedLogEvent"}],"url":"\/documentation\/kksplayer\/uniaudiovolumechangedlogevent","abstract":[],"type":"topic","kind":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/SeekPosition":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/SeekPosition","title":"SeekPosition","navigatorTitle":[{"text":"SeekPosition","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SeekPosition","kind":"identifier"}],"url":"\/documentation\/kksplayer\/seekposition","abstract":[],"type":"topic","kind":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlaybackBufferBeganLogEvent":{"navigatorTitle":[{"text":"UniPlaybackBufferBeganLogEvent","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/kksplayer\/uniplaybackbufferbeganlogevent","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlaybackBufferBeganLogEvent","kind":"symbol","abstract":[],"title":"UniPlaybackBufferBeganLogEvent","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UniPlaybackBufferBeganLogEvent","kind":"identifier"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerStartedLogEvent":{"navigatorTitle":[{"kind":"identifier","text":"UniPlayerStartedLogEvent"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UniPlayerStartedLogEvent","kind":"identifier"}],"type":"topic","url":"\/documentation\/kksplayer\/uniplayerstartedlogevent","abstract":[],"kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerStartedLogEvent","role":"symbol","title":"UniPlayerStartedLogEvent"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManagerOptions":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CastManagerOptions"}],"type":"topic","url":"\/documentation\/kksplayer\/castmanageroptions","navigatorTitle":[{"text":"CastManagerOptions","kind":"identifier"}],"abstract":[{"text":"The options to be used for initializing CastManager","type":"text"}],"title":"CastManagerOptions","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManagerOptions","role":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlaybackEndedLogEvent":{"type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlaybackEndedLogEvent","kind":"symbol","abstract":[],"url":"\/documentation\/kksplayer\/uniplaybackendedlogevent","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UniPlaybackEndedLogEvent","kind":"identifier"}],"navigatorTitle":[{"text":"UniPlaybackEndedLogEvent","kind":"identifier"}],"title":"UniPlaybackEndedLogEvent","role":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/KKSPlayerVersionNumber":{"fragments":[{"text":"KKSPlayerVersionNumber","kind":"identifier"}],"abstract":[{"text":"Project version number for KKSPlayer.","type":"text"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/KKSPlayerVersionNumber","kind":"symbol","role":"symbol","type":"topic","title":"KKSPlayerVersionNumber","url":"\/documentation\/kksplayer\/kksplayerversionnumber"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlaybackBeganLogEvent":{"title":"UniPlaybackBeganLogEvent","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UniPlaybackBeganLogEvent","kind":"identifier"}],"url":"\/documentation\/kksplayer\/uniplaybackbeganlogevent","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UniPlaybackBeganLogEvent"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlaybackBeganLogEvent"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/SourceErrorCode":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/SourceErrorCode","type":"topic","role":"symbol","navigatorTitle":[{"text":"SourceErrorCode","kind":"identifier"}],"url":"\/documentation\/kksplayer\/sourceerrorcode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SourceErrorCode","kind":"identifier"}],"abstract":[],"title":"SourceErrorCode","kind":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniTimeChangedEvent":{"kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTimeChangedEvent","type":"topic","navigatorTitle":[{"text":"UniTimeChangedEvent","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniTimeChangedEvent"}],"url":"\/documentation\/kksplayer\/unitimechangedevent","abstract":[],"role":"symbol","title":"UniTimeChangedEvent"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/PlayerViewConfig":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/PlayerViewConfig","title":"PlayerViewConfig","role":"symbol","url":"\/documentation\/kksplayer\/playerviewconfig","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlayerViewConfig"}],"kind":"symbol","abstract":[],"navigatorTitle":[{"text":"PlayerViewConfig","kind":"identifier"}],"type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlaybackBufferEndedLogEvent":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlaybackBufferEndedLogEvent","abstract":[],"url":"\/documentation\/kksplayer\/uniplaybackbufferendedlogevent","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UniPlaybackBufferEndedLogEvent"}],"type":"topic","title":"UniPlaybackBufferEndedLogEvent","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UniPlaybackBufferEndedLogEvent","kind":"identifier"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniTweaksConfig":{"role":"symbol","navigatorTitle":[{"text":"UniTweaksConfig","kind":"identifier"}],"title":"UniTweaksConfig","kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTweaksConfig","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniTweaksConfig"}],"url":"\/documentation\/kksplayer\/unitweaksconfig","abstract":[],"type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniStallEndedEvent":{"abstract":[],"url":"\/documentation\/kksplayer\/unistallendedevent","title":"UniStallEndedEvent","navigatorTitle":[{"text":"UniStallEndedEvent","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniStallEndedEvent"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniStallEndedEvent","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniVideoPlaybackQualityChangedEvent":{"kind":"symbol","role":"symbol","abstract":[],"title":"UniVideoPlaybackQualityChangedEvent","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniVideoPlaybackQualityChangedEvent"}],"navigatorTitle":[{"kind":"identifier","text":"UniVideoPlaybackQualityChangedEvent"}],"url":"\/documentation\/kksplayer\/univideoplaybackqualitychangedevent","type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniVideoPlaybackQualityChangedEvent"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniApiLoopChangedEvent":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniApiLoopChangedEvent","title":"UniApiLoopChangedEvent","navigatorTitle":[{"text":"UniApiLoopChangedEvent","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UniApiLoopChangedEvent","kind":"identifier"}],"url":"\/documentation\/kksplayer\/uniapiloopchangedevent","abstract":[{"type":"text","text":"Represents an event indicating changes in the loop."}],"type":"topic","kind":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager":{"navigatorTitle":[{"text":"CastManager","kind":"identifier"}],"title":"CastManager","type":"topic","kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager","role":"symbol","url":"\/documentation\/kksplayer\/castmanager","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CastManager"}],"abstract":[{"type":"text","text":"Singleton providing access to GoogleCast related features."},{"text":" ","type":"text"},{"text":"The CastManager needs to be initialized by calling CastManager#initializeCasting in the AppDelegate of the application which should support casting.","type":"text"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSource":{"title":"UniSource","url":"\/documentation\/kksplayer\/unisource","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniSource"}],"role":"symbol","navigatorTitle":[{"text":"UniSource","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSource","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniLoggerListener":{"navigatorTitle":[{"text":"UniLoggerListener","kind":"identifier"}],"url":"\/documentation\/kksplayer\/uniloggerlistener","type":"topic","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniLoggerListener","kind":"symbol","title":"UniLoggerListener","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"UniLoggerListener","kind":"identifier"}],"role":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSeekedEvent":{"abstract":[],"url":"\/documentation\/kksplayer\/uniseekedevent","title":"UniSeekedEvent","navigatorTitle":[{"kind":"identifier","text":"UniSeekedEvent"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniSeekedEvent"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSeekedEvent","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerErrorCode":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerErrorCode","title":"UniPlayerErrorCode","navigatorTitle":[{"kind":"identifier","text":"UniPlayerErrorCode"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniPlayerErrorCode"}],"url":"\/documentation\/kksplayer\/uniplayererrorcode","abstract":[{"type":"text","text":"apiError format: apiErrorCode(20) + httpStatusCode(such as 403) = 20403"}],"type":"topic","kind":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/pLog":{"role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/pLog","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pLog"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9KKSPlayer23PLPrioritizingLogSystemC","text":"PLPrioritizingLogSystem","kind":"typeIdentifier"}],"url":"\/documentation\/kksplayer\/plog","title":"pLog","type":"topic","abstract":[{"type":"text","text":"An instance of "},{"code":"PLPrioritizingLogSystem","type":"codeVoice"},{"type":"text","text":" for print and collect debug log under global scope."}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlaylist":{"role":"symbol","url":"\/documentation\/kksplayer\/uniplaylist","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"UniPlaylist","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"UniPlaylist","kind":"identifier"}],"title":"UniPlaylist","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlaylist","abstract":[],"kind":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerView":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniPlayerView"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UniPlayerView"}],"url":"\/documentation\/kksplayer\/uniplayerview","type":"topic","abstract":[],"title":"UniPlayerView"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/PLPrioritizingLogSystem":{"url":"\/documentation\/kksplayer\/plprioritizinglogsystem","abstract":[],"kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/PLPrioritizingLogSystem","navigatorTitle":[{"kind":"identifier","text":"PLPrioritizingLogSystem"}],"role":"symbol","title":"PLPrioritizingLogSystem","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PLPrioritizingLogSystem","kind":"identifier"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniReadyEvent":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniReadyEvent"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniReadyEvent","navigatorTitle":[{"kind":"identifier","text":"UniReadyEvent"}],"title":"UniReadyEvent","url":"\/documentation\/kksplayer\/unireadyevent"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniTrackProtocol":{"url":"\/documentation\/kksplayer\/unitrackprotocol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrackProtocol","type":"topic","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"UniTrackProtocol","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"UniTrackProtocol"}],"title":"UniTrackProtocol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniTimeShiftEvent":{"kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTimeShiftEvent","type":"topic","role":"symbol","abstract":[],"title":"UniTimeShiftEvent","navigatorTitle":[{"text":"UniTimeShiftEvent","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniTimeShiftEvent"}],"url":"\/documentation\/kksplayer\/unitimeshiftevent"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSubtitleChangedEvent":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSubtitleChangedEvent","role":"symbol","title":"UniSubtitleChangedEvent","kind":"symbol","navigatorTitle":[{"text":"UniSubtitleChangedEvent","kind":"identifier"}],"abstract":[],"url":"\/documentation\/kksplayer\/unisubtitlechangedevent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UniSubtitleChangedEvent","kind":"identifier"}],"type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/Foundation":{"url":"\/documentation\/kksplayer\/foundation","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/Foundation","kind":"symbol","title":"Foundation","role":"collection","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniApiRewindLogEvent":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniApiRewindLogEvent","title":"UniApiRewindLogEvent","navigatorTitle":[{"text":"UniApiRewindLogEvent","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"UniApiRewindLogEvent","kind":"identifier"}],"url":"\/documentation\/kksplayer\/uniapirewindlogevent","abstract":[],"type":"topic","kind":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniLogEvent":{"title":"UniLogEvent","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniLogEvent","url":"\/documentation\/kksplayer\/unilogevent","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UniLogEvent","kind":"identifier"}],"navigatorTitle":[{"text":"UniLogEvent","kind":"identifier"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSourceLoadEvent":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniSourceLoadEvent"}],"navigatorTitle":[{"kind":"identifier","text":"UniSourceLoadEvent"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceLoadEvent","type":"topic","url":"\/documentation\/kksplayer\/unisourceloadevent","title":"UniSourceLoadEvent","kind":"symbol","role":"symbol","abstract":[]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerEvent":{"title":"UniPlayerEvent","url":"\/documentation\/kksplayer\/uniplayerevent","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniPlayerEvent"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UniPlayerEvent"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerEvent","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSheetPresentationController":{"role":"symbol","navigatorTitle":[{"text":"UniSheetPresentationController","kind":"identifier"}],"title":"UniSheetPresentationController","kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSheetPresentationController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UniSheetPresentationController","kind":"identifier"}],"url":"\/documentation\/kksplayer\/unisheetpresentationcontroller","abstract":[],"type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/Analytics":{"title":"Analytics","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Analytics","kind":"identifier"}],"url":"\/documentation\/kksplayer\/analytics","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"Analytics","kind":"identifier"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/Analytics"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniThumbnailTrack":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UniThumbnailTrack"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniThumbnailTrack","url":"\/documentation\/kksplayer\/unithumbnailtrack","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UniThumbnailTrack","kind":"identifier"}],"title":"UniThumbnailTrack","abstract":[]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlaybackErrorLogEvent":{"url":"\/documentation\/kksplayer\/uniplaybackerrorlogevent","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlaybackErrorLogEvent","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UniPlaybackErrorLogEvent"}],"role":"symbol","type":"topic","title":"UniPlaybackErrorLogEvent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniPlaybackErrorLogEvent"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniStallStartedEvent":{"title":"UniStallStartedEvent","type":"topic","url":"\/documentation\/kksplayer\/unistallstartedevent","navigatorTitle":[{"kind":"identifier","text":"UniStallStartedEvent"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniStallStartedEvent"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniStallStartedEvent","abstract":[]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniDrmConfig":{"kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniDrmConfig","type":"topic","role":"symbol","title":"UniDrmConfig","abstract":[],"navigatorTitle":[{"text":"UniDrmConfig","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UniDrmConfig","kind":"identifier"}],"url":"\/documentation\/kksplayer\/unidrmconfig"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/PictureInPictureEnterEvent":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/PictureInPictureEnterEvent","title":"PictureInPictureEnterEvent","navigatorTitle":[{"kind":"identifier","text":"PictureInPictureEnterEvent"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PictureInPictureEnterEvent"}],"url":"\/documentation\/kksplayer\/pictureinpictureenterevent","abstract":[],"type":"topic","kind":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniCommonProperty":{"title":"UniCommonProperty","role":"symbol","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniCommonProperty","url":"\/documentation\/kksplayer\/unicommonproperty","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UniCommonProperty","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"UniCommonProperty"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlaybackSeekBeganLogEvent":{"type":"topic","url":"\/documentation\/kksplayer\/uniplaybackseekbeganlogevent","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlaybackSeekBeganLogEvent","title":"UniPlaybackSeekBeganLogEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniPlaybackSeekBeganLogEvent"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"UniPlaybackSeekBeganLogEvent","kind":"identifier"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniApiAudioMuteChangedLogEvent":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniApiAudioMuteChangedLogEvent","abstract":[],"url":"\/documentation\/kksplayer\/uniapiaudiomutechangedlogevent","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UniApiAudioMuteChangedLogEvent"}],"type":"topic","title":"UniApiAudioMuteChangedLogEvent","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UniApiAudioMuteChangedLogEvent","kind":"identifier"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniMutedEvent":{"role":"symbol","navigatorTitle":[{"text":"UniMutedEvent","kind":"identifier"}],"abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UniMutedEvent","kind":"identifier"}],"title":"UniMutedEvent","url":"\/documentation\/kksplayer\/unimutedevent","type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniMutedEvent"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayingEvent":{"title":"UniPlayingEvent","type":"topic","url":"\/documentation\/kksplayer\/uniplayingevent","navigatorTitle":[{"text":"UniPlayingEvent","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"UniPlayingEvent","kind":"identifier"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayingEvent","abstract":[]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSourceListener":{"url":"\/documentation\/kksplayer\/unisourcelistener","abstract":[],"kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UniSourceListener","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UniSourceListener"}],"title":"UniSourceListener","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceListener"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniLoadedTimeRangeChangedEvent":{"url":"\/documentation\/kksplayer\/uniloadedtimerangechangedevent","kind":"symbol","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniLoadedTimeRangeChangedEvent","navigatorTitle":[{"text":"UniLoadedTimeRangeChangedEvent","kind":"identifier"}],"role":"symbol","title":"UniLoadedTimeRangeChangedEvent","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UniLoadedTimeRangeChangedEvent","kind":"identifier"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlaybackStartedLogEvent":{"role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlaybackStartedLogEvent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UniPlaybackStartedLogEvent","kind":"identifier"}],"navigatorTitle":[{"text":"UniPlaybackStartedLogEvent","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/kksplayer\/uniplaybackstartedlogevent","title":"UniPlaybackStartedLogEvent","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/KKSPlayerModuleInfo":{"url":"\/documentation\/kksplayer\/kksplayermoduleinfo","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/KKSPlayerModuleInfo","abstract":[],"kind":"symbol","title":"KKSPlayerModuleInfo","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"KKSPlayerModuleInfo"}],"navigatorTitle":[{"kind":"identifier","text":"KKSPlayerModuleInfo"}],"type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UIKit":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UIKit","title":"UIKit","role":"collection","url":"\/documentation\/kksplayer\/uikit","abstract":[],"type":"topic","kind":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniLoopChangedLogEvent":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniLoopChangedLogEvent","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniLoopChangedLogEvent"}],"title":"UniLoopChangedLogEvent","kind":"symbol","abstract":[],"url":"\/documentation\/kksplayer\/uniloopchangedlogevent","navigatorTitle":[{"text":"UniLoopChangedLogEvent","kind":"identifier"}],"type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniLoopChangedEvent":{"title":"UniLoopChangedEvent","url":"\/documentation\/kksplayer\/uniloopchangedevent","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniLoopChangedEvent"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UniLoopChangedEvent"}],"abstract":[{"type":"text","text":"Represents an event indicating a change in the loop state of a player."}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniLoopChangedEvent","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/Swift":{"type":"topic","url":"\/documentation\/kksplayer\/swift","abstract":[],"kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/Swift","role":"collection","title":"Swift"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniVideoSubtitleChangedLogEvent":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniVideoSubtitleChangedLogEvent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UniVideoSubtitleChangedLogEvent","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"UniVideoSubtitleChangedLogEvent"}],"kind":"symbol","role":"symbol","type":"topic","title":"UniVideoSubtitleChangedLogEvent","url":"\/documentation\/kksplayer\/univideosubtitlechangedlogevent","abstract":[]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSourceUnloadEvent":{"title":"UniSourceUnloadEvent","kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceUnloadEvent","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UniSourceUnloadEvent","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"UniSourceUnloadEvent","kind":"identifier"}],"url":"\/documentation\/kksplayer\/unisourceunloadevent"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniFullscreenHandler":{"navigatorTitle":[{"text":"UniFullscreenHandler","kind":"identifier"}],"abstract":[],"url":"\/documentation\/kksplayer\/unifullscreenhandler","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniFullscreenHandler","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"UniFullscreenHandler","kind":"identifier"}],"title":"UniFullscreenHandler","type":"topic","kind":"symbol","role":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSourceErrorEvent":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceErrorEvent","type":"topic","title":"UniSourceErrorEvent","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniSourceErrorEvent"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"UniSourceErrorEvent"}],"url":"\/documentation\/kksplayer\/unisourceerrorevent","kind":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastOptions":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastOptions","title":"CastOptions","role":"symbol","url":"\/documentation\/kksplayer\/castoptions","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CastOptions"}],"kind":"symbol","abstract":[{"type":"text","text":"Used for configuring casting options."}],"navigatorTitle":[{"kind":"identifier","text":"CastOptions"}],"type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerControlView":{"url":"\/documentation\/kksplayer\/uniplayercontrolview","abstract":[],"kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerControlView","navigatorTitle":[{"text":"UniPlayerControlView","kind":"identifier"}],"role":"symbol","title":"UniPlayerControlView","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniPlayerControlView"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniApiForwardLogEvent":{"abstract":[],"title":"UniApiForwardLogEvent","type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniApiForwardLogEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"UniApiForwardLogEvent","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"UniApiForwardLogEvent","kind":"identifier"}],"role":"symbol","url":"\/documentation\/kksplayer\/uniapiforwardlogevent"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastConstant":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastConstant","role":"symbol","title":"CastConstant","kind":"symbol","navigatorTitle":[{"text":"CastConstant","kind":"identifier"}],"url":"\/documentation\/kksplayer\/castconstant","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"CastConstant","kind":"identifier"}],"type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniApiVideoQualityChangedLogEvent":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniApiVideoQualityChangedLogEvent"}],"title":"UniApiVideoQualityChangedLogEvent","type":"topic","url":"\/documentation\/kksplayer\/uniapivideoqualitychangedlogevent","kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniApiVideoQualityChangedLogEvent","abstract":[],"role":"symbol","navigatorTitle":[{"text":"UniApiVideoQualityChangedLogEvent","kind":"identifier"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniBufferConfig":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniBufferConfig","title":"UniBufferConfig","role":"symbol","url":"\/documentation\/kksplayer\/unibufferconfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"UniBufferConfig","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Player buffer config object to configure buffering behavior."}],"navigatorTitle":[{"text":"UniBufferConfig","kind":"identifier"}],"type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniApiPlayLogEvent":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniApiPlayLogEvent","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"UniApiPlayLogEvent"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniApiPlayLogEvent"}],"title":"UniApiPlayLogEvent","url":"\/documentation\/kksplayer\/uniapiplaylogevent","role":"symbol","kind":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerErrorEvent":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerErrorEvent","role":"symbol","abstract":[],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UniPlayerErrorEvent"}],"url":"\/documentation\/kksplayer\/uniplayererrorevent","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UniPlayerErrorEvent","kind":"identifier"}],"title":"UniPlayerErrorEvent"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/PictureInPictureConfig":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/PictureInPictureConfig","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PictureInPictureConfig"}],"type":"topic","title":"PictureInPictureConfig","abstract":[{"type":"text","text":"Provides options to configure Picture in Picture playback."}],"url":"\/documentation\/kksplayer\/pictureinpictureconfig","navigatorTitle":[{"text":"PictureInPictureConfig","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniApiSeekLogEvent":{"title":"UniApiSeekLogEvent","navigatorTitle":[{"text":"UniApiSeekLogEvent","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UniApiSeekLogEvent","kind":"identifier"}],"abstract":[],"url":"\/documentation\/kksplayer\/uniapiseeklogevent","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniApiSeekLogEvent","role":"symbol","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerLoadingLogEvent":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniPlayerLoadingLogEvent"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerLoadingLogEvent","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"UniPlayerLoadingLogEvent","kind":"identifier"}],"type":"topic","title":"UniPlayerLoadingLogEvent","url":"\/documentation\/kksplayer\/uniplayerloadinglogevent"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerViewController":{"title":"UniPlayerViewController","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"UniPlayerViewController","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UniPlayerViewController"}],"url":"\/documentation\/kksplayer\/uniplayerviewcontroller","type":"topic","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniApiAudioVolumeChangedLogEvent":{"role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniApiAudioVolumeChangedLogEvent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UniApiAudioVolumeChangedLogEvent","kind":"identifier"}],"navigatorTitle":[{"text":"UniApiAudioVolumeChangedLogEvent","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/kksplayer\/uniapiaudiovolumechangedlogevent","type":"topic","title":"UniApiAudioVolumeChangedLogEvent"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSourceConfig":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceConfig","title":"UniSourceConfig","role":"symbol","url":"\/documentation\/kksplayer\/unisourceconfig","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UniSourceConfig","kind":"identifier"}],"kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"UniSourceConfig"}],"type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSourceLoadedEvent":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceLoadedEvent","url":"\/documentation\/kksplayer\/unisourceloadedevent","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"UniSourceLoadedEvent","kind":"identifier"}],"role":"symbol","title":"UniSourceLoadedEvent","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"UniSourceLoadedEvent","kind":"identifier"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastImage":{"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"CastImage","kind":"identifier"}],"navigatorTitle":[{"text":"CastImage","kind":"identifier"}],"url":"\/documentation\/kksplayer\/castimage","title":"CastImage","type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastImage"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayerListener":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"UniPlayerListener","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"UniPlayerListener"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerListener","type":"topic","url":"\/documentation\/kksplayer\/uniplayerlistener","title":"UniPlayerListener","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Defines listener methods for all events available for the Player"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UniPlayer","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"UniPlayer"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer","type":"topic","url":"\/documentation\/kksplayer\/uniplayer","title":"UniPlayer","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"An object that provides the interface to control the players transport behavior."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Classes","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/Analytics","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManagerOptions","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniAudioTrack","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniControllerPlayerView","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniLogger","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerControlView","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerView","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayerViewController","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSettingViewController","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSheetPresentationController","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSource","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSubtitleTrack","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniThumbnailTrack","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniTrack","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniUITableViewController"]},{"title":"Variables","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/KKSPlayerVersionNumber","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/KKSPlayerVersionString"]}]},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSettingViewController\/title","value":"UniSettingViewController","op":"replace"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSettingViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"UniSettingViewController"}]},{"value":"UniSubtitleTrack","op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSubtitleTrack\/title"},{"value":[{"kind":"identifier","text":"UniSubtitleTrack"}],"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSubtitleTrack\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniAudioTrack\/title","value":"UniAudioTrack"},{"value":[{"text":"UniAudioTrack","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniAudioTrack\/fragments"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniTrack\/title","value":"UniTrack","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniTrack\/fragments","value":[{"kind":"identifier","text":"UniTrack"}]},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniLogger\/title","op":"replace","value":"UniLogger"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniLogger\/fragments","value":[{"text":"UniLogger","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniControllerPlayerView\/title","value":"UniControllerPlayerView"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniControllerPlayerView\/fragments","value":[{"text":"UniControllerPlayerView","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"UniUITableViewController","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniUITableViewController\/title"},{"value":[{"text":"UniUITableViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniUITableViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManagerOptions\/title","value":"CastManagerOptions"},{"value":[{"text":"CastManagerOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManagerOptions\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager\/title","value":"CastManager"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager\/fragments","value":[{"kind":"identifier","text":"CastManager"}]},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSource\/title","value":"UniSource"},{"value":[{"text":"UniSource","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSource\/fragments"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerView\/title","op":"replace","value":"UniPlayerView"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerView\/fragments","value":[{"kind":"identifier","text":"UniPlayerView"}],"op":"replace"},{"value":"UniSheetPresentationController","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSheetPresentationController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSheetPresentationController\/fragments","value":[{"text":"UniSheetPresentationController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1Analytics\/title","value":"Analytics"},{"value":[{"text":"Analytics","kind":"identifier"}],"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1Analytics\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniThumbnailTrack\/title","op":"replace","value":"UniThumbnailTrack"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniThumbnailTrack\/fragments","op":"replace","value":[{"text":"UniThumbnailTrack","kind":"identifier"}]},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerControlView\/title","op":"replace","value":"UniPlayerControlView"},{"value":[{"text":"UniPlayerControlView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerControlView\/fragments"},{"op":"replace","value":"UniPlayerViewController","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerViewController\/title"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayerViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"UniPlayerViewController"}]},{"value":"UniPlayer","op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/title"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/fragments","value":[{"kind":"identifier","text":"UniPlayer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}