{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/request(_:didAbortWith:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/request(_:didFailWithError:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/requestDidComplete(_:)"]}],"variants":[{"paths":["\/documentation\/kksplayer\/castmanager\/gckrequestdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/kksplayer\/castmanager\/gckrequestdelegate-implementations"]}],"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager"]]},"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/GCKRequestDelegate-Implementations","interfaceLanguage":"swift"},"kind":"article","metadata":{"modules":[{"name":"BVPlayer"}],"role":"collectionGroup","title":"GCKRequestDelegate Implementations"},"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/request(_:didAbortWith:)":{"navigatorTitle":[{"text":"request:didAbortWithReason:","kind":"identifier"}],"title":"request(_:didAbortWith:)","type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/request(_:didAbortWith:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"request"},{"kind":"text","text":"("},{"text":"GCKRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKRequest"},{"text":", ","kind":"text"},{"text":"didAbortWith","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@GCKRequestAbortReason","kind":"typeIdentifier","text":"GCKRequestAbortReason"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/kksplayer\/castmanager\/request(_:didabortwith:)"},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","abstract":[{"text":"BlendVision One iOS Player SDK","type":"text"}],"title":"BVPlayer","url":"\/documentation\/kksplayer","kind":"symbol","role":"collection"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager":{"type":"topic","url":"\/documentation\/kksplayer\/castmanager","abstract":[{"text":"Singleton providing access to GoogleCast related features.","type":"text"},{"text":" ","type":"text"},{"text":"The CastManager needs to be initialized by calling CastManager#initializeCasting in the AppDelegate of the application which should support casting.","type":"text"}],"title":"CastManager","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CastManager","kind":"identifier"}],"navigatorTitle":[{"text":"CastManager","kind":"identifier"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/request(_:didFailWithError:)":{"role":"symbol","title":"request(_:didFailWithError:)","abstract":[],"url":"\/documentation\/kksplayer\/castmanager\/request(_:didfailwitherror:)","type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/request(_:didFailWithError:)","navigatorTitle":[{"text":"request:didFailWithError:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"request","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GCKRequest","text":"GCKRequest","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFailWithError","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GCKError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKError"},{"text":")","kind":"text"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/requestDidComplete(_:)":{"navigatorTitle":[{"kind":"identifier","text":"requestDidComplete:"}],"title":"requestDidComplete(_:)","type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/requestDidComplete(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"requestDidComplete","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GCKRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKRequest"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/kksplayer\/castmanager\/requestdidcomplete(_:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/request(_:didAbortWith:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/request(_:didFailWithError:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/requestDidComplete(_:)"],"title":"Instance Methods","generated":true}],"path":"\/topicSections","op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1request(_:didAbortWith:)\/title","value":"request:didAbortWithReason:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"request:didAbortWithReason:"}],"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1request(_:didAbortWith:)\/fragments"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager\/title","value":"CastManager","op":"replace"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager\/fragments","op":"replace","value":[{"text":"CastManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1request(_:didFailWithError:)\/title","value":"request:didFailWithError:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"request:didFailWithError:"}],"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1request(_:didFailWithError:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1requestDidComplete(_:)\/title","op":"replace","value":"requestDidComplete:"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1requestDidComplete(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestDidComplete:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}