{"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager"]]},"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/GCKRemoteMediaClientListener-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/remoteMediaClient(_:didUpdate:)-3n277","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/remoteMediaClient(_:didUpdate:)-8yj2f"],"generated":true,"title":"Instance Methods"}],"metadata":{"modules":[{"name":"KKSPlayer"}],"title":"GCKRemoteMediaClientListener Implementations","role":"collectionGroup"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kksplayer\/castmanager\/gckremotemediaclientlistener-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/kksplayer\/castmanager\/gckremotemediaclientlistener-implementations"]}],"kind":"article","sections":[],"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager":{"navigatorTitle":[{"text":"CastManager","kind":"identifier"}],"title":"CastManager","type":"topic","kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager","role":"symbol","url":"\/documentation\/kksplayer\/castmanager","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CastManager"}],"abstract":[{"type":"text","text":"Singleton providing access to GoogleCast related features."},{"text":" ","type":"text"},{"text":"The CastManager needs to be initialized by calling CastManager#initializeCasting in the AppDelegate of the application which should support casting.","type":"text"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","role":"collection","url":"\/documentation\/kksplayer","kind":"symbol","title":"KKSPlayer","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/remoteMediaClient(_:didUpdate:)-3n277":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/remoteMediaClient(_:didUpdate:)-3n277","title":"remoteMediaClient(_:didUpdate:)","navigatorTitle":[{"kind":"identifier","text":"remoteMediaClient:didUpdateMediaMetadata:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"remoteMediaClient","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GCKRemoteMediaClient","preciseIdentifier":"c:objc(cs)GCKRemoteMediaClient","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdate"},{"kind":"text","text":": "},{"text":"GCKMediaMetadata","preciseIdentifier":"c:objc(cs)GCKMediaMetadata","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"url":"\/documentation\/kksplayer\/castmanager\/remotemediaclient(_:didupdate:)-3n277","abstract":[],"type":"topic","kind":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/remoteMediaClient(_:didUpdate:)-8yj2f":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/remoteMediaClient(_:didUpdate:)-8yj2f","title":"remoteMediaClient(_:didUpdate:)","navigatorTitle":[{"kind":"identifier","text":"remoteMediaClient:didUpdateMediaStatus:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"remoteMediaClient"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GCKRemoteMediaClient","preciseIdentifier":"c:objc(cs)GCKRemoteMediaClient"},{"text":", ","kind":"text"},{"text":"didUpdate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GCKMediaStatus","text":"GCKMediaStatus","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"url":"\/documentation\/kksplayer\/castmanager\/remotemediaclient(_:didupdate:)-8yj2f","abstract":[],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/remoteMediaClient(_:didUpdate:)-3n277","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/remoteMediaClient(_:didUpdate:)-8yj2f"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":"CastManager","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager\/title"},{"op":"replace","value":[{"kind":"identifier","text":"CastManager"}],"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager\/fragments"},{"value":"remoteMediaClient:didUpdateMediaMetadata:","op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1remoteMediaClient(_:didUpdate:)-3n277\/title"},{"value":[{"kind":"text","text":"- "},{"text":"remoteMediaClient:didUpdateMediaMetadata:","kind":"identifier"}],"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1remoteMediaClient(_:didUpdate:)-3n277\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1remoteMediaClient(_:didUpdate:)-8yj2f\/title","value":"remoteMediaClient:didUpdateMediaStatus:"},{"value":[{"kind":"text","text":"- "},{"text":"remoteMediaClient:didUpdateMediaStatus:","kind":"identifier"}],"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1remoteMediaClient(_:didUpdate:)-8yj2f\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}