{"variants":[{"paths":["\/documentation\/kksplayer\/castmanager\/gcksessionmanagerlistener-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/kksplayer\/castmanager\/gcksessionmanagerlistener-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/GCKSessionManagerListener-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/sessionManager(_:didEnd:withError:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/sessionManager(_:didFailToStart:withError:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/sessionManager(_:didResumeCastSession:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/sessionManager(_:didStart:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/sessionManager(_:didSuspend:with:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/sessionManager(_:willResumeCastSession:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/sessionManager(_:willStart:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"KKSPlayer"}],"role":"collectionGroup","title":"GCKSessionManagerListener Implementations"},"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager"]]},"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/sessionManager(_:didStart:)":{"role":"symbol","title":"sessionManager(_:didStart:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GCKSessionManager","preciseIdentifier":"c:objc(cs)GCKSessionManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStart"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GCKCastSession","preciseIdentifier":"c:objc(cs)GCKCastSession"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/sessionManager(_:didStart:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sessionManager:didStartCastSession:"}],"url":"\/documentation\/kksplayer\/castmanager\/sessionmanager(_:didstart:)"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager":{"role":"symbol","title":"CastManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CastManager"}],"abstract":[{"type":"text","text":"Singleton providing access to GoogleCast related features."},{"type":"text","text":" "},{"type":"text","text":"The CastManager needs to be initialized by calling CastManager#initializeCasting in the AppDelegate of the application which should support casting."}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CastManager"}],"url":"\/documentation\/kksplayer\/castmanager"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/sessionManager(_:willResumeCastSession:)":{"role":"symbol","title":"sessionManager(_:willResumeCastSession:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GCKSessionManager","preciseIdentifier":"c:objc(cs)GCKSessionManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willResumeCastSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GCKCastSession","preciseIdentifier":"c:objc(cs)GCKCastSession"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/sessionManager(_:willResumeCastSession:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sessionManager:willResumeCastSession:"}],"url":"\/documentation\/kksplayer\/castmanager\/sessionmanager(_:willresumecastsession:)"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/sessionManager(_:didEnd:withError:)":{"role":"symbol","title":"sessionManager(_:didEnd:withError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GCKSessionManager","preciseIdentifier":"c:objc(cs)GCKSessionManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didEnd"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GCKCastSession","preciseIdentifier":"c:objc(cs)GCKCastSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/sessionManager(_:didEnd:withError:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sessionManager:didEndCastSession:withError:"}],"url":"\/documentation\/kksplayer\/castmanager\/sessionmanager(_:didend:witherror:)"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/sessionManager(_:willStart:)":{"role":"symbol","title":"sessionManager(_:willStart:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GCKSessionManager","preciseIdentifier":"c:objc(cs)GCKSessionManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willStart"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GCKCastSession","preciseIdentifier":"c:objc(cs)GCKCastSession"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/sessionManager(_:willStart:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sessionManager:willStartCastSession:"}],"url":"\/documentation\/kksplayer\/castmanager\/sessionmanager(_:willstart:)"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/sessionManager(_:didSuspend:with:)":{"role":"symbol","title":"sessionManager(_:didSuspend:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GCKSessionManager","preciseIdentifier":"c:objc(cs)GCKSessionManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSuspend"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GCKCastSession","preciseIdentifier":"c:objc(cs)GCKCastSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GCKConnectionSuspendReason","preciseIdentifier":"c:@E@GCKConnectionSuspendReason"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/sessionManager(_:didSuspend:with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sessionManager:didSuspendCastSession:withReason:"}],"url":"\/documentation\/kksplayer\/castmanager\/sessionmanager(_:didsuspend:with:)"},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"role":"collection","title":"KKSPlayer","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","kind":"symbol","type":"topic","url":"\/documentation\/kksplayer"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/sessionManager(_:didFailToStart:withError:)":{"role":"symbol","title":"sessionManager(_:didFailToStart:withError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GCKSessionManager","preciseIdentifier":"c:objc(cs)GCKSessionManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailToStart"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GCKCastSession","preciseIdentifier":"c:objc(cs)GCKCastSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/sessionManager(_:didFailToStart:withError:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sessionManager:didFailToStartCastSession:withError:"}],"url":"\/documentation\/kksplayer\/castmanager\/sessionmanager(_:didfailtostart:witherror:)"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/sessionManager(_:didResumeCastSession:)":{"role":"symbol","title":"sessionManager(_:didResumeCastSession:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GCKSessionManager","preciseIdentifier":"c:objc(cs)GCKSessionManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didResumeCastSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GCKCastSession","preciseIdentifier":"c:objc(cs)GCKCastSession"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/sessionManager(_:didResumeCastSession:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sessionManager:didResumeCastSession:"}],"url":"\/documentation\/kksplayer\/castmanager\/sessionmanager(_:didresumecastsession:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/sessionManager(_:didEnd:withError:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/sessionManager(_:didFailToStart:withError:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/sessionManager(_:didResumeCastSession:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/sessionManager(_:didStart:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/sessionManager(_:didSuspend:with:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/sessionManager(_:willResumeCastSession:)","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/sessionManager(_:willStart:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1sessionManager(_:didStart:)\/title","value":"sessionManager:didStartCastSession:"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1sessionManager(_:didStart:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sessionManager:didStartCastSession:"}]},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager\/title","value":"CastManager"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager\/fragments","value":[{"kind":"identifier","text":"CastManager"}]},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1sessionManager(_:willResumeCastSession:)\/title","value":"sessionManager:willResumeCastSession:"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1sessionManager(_:willResumeCastSession:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sessionManager:willResumeCastSession:"}]},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1sessionManager(_:didEnd:withError:)\/title","value":"sessionManager:didEndCastSession:withError:"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1sessionManager(_:didEnd:withError:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sessionManager:didEndCastSession:withError:"}]},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1sessionManager(_:willStart:)\/title","value":"sessionManager:willStartCastSession:"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1sessionManager(_:willStart:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sessionManager:willStartCastSession:"}]},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1sessionManager(_:didSuspend:with:)\/title","value":"sessionManager:didSuspendCastSession:withReason:"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1sessionManager(_:didSuspend:with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sessionManager:didSuspendCastSession:withReason:"}]},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1sessionManager(_:didFailToStart:withError:)\/title","value":"sessionManager:didFailToStartCastSession:withError:"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1sessionManager(_:didFailToStart:withError:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sessionManager:didFailToStartCastSession:withError:"}]},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1sessionManager(_:didResumeCastSession:)\/title","value":"sessionManager:didResumeCastSession:"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1sessionManager(_:didResumeCastSession:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sessionManager:didResumeCastSession:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}