{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializeCasting"},{"kind":"text","text":"("},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManagerOptions","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)CastManagerOptions","text":"CastManagerOptions"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/kksplayer\/castmanager\/initializecasting(options:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/initializeCasting(options:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initialize CastManager based on the provided CastManagerOptions."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializeCasting"},{"kind":"text","text":"("},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CastManagerOptions","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)CastManagerOptions"},{"kind":"text","text":")"}],"title":"initializeCasting(options:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"s:9KKSPlayer11CastManagerC17initializeCasting7optionsyAA0bC7OptionsC_tFZ","modules":[{"name":"KKSPlayer"}]},"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager"]]},"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"role":"collection","title":"KKSPlayer","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","kind":"symbol","type":"topic","url":"\/documentation\/kksplayer"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager":{"role":"symbol","title":"CastManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CastManager"}],"abstract":[{"type":"text","text":"Singleton providing access to GoogleCast related features."},{"type":"text","text":" "},{"type":"text","text":"The CastManager needs to be initialized by calling CastManager#initializeCasting in the AppDelegate of the application which should support casting."}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CastManager"}],"url":"\/documentation\/kksplayer\/castmanager"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManagerOptions":{"role":"symbol","title":"CastManagerOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CastManagerOptions"}],"abstract":[{"type":"text","text":"The options to be used for initializing CastManager"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManagerOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CastManagerOptions"}],"url":"\/documentation\/kksplayer\/castmanageroptions"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/initializeCasting(options:)":{"role":"symbol","title":"initializeCasting(options:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializeCasting"},{"kind":"text","text":"("},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CastManagerOptions","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)CastManagerOptions"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initialize CastManager based on the provided CastManagerOptions."}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/initializeCasting(options:)","kind":"symbol","type":"topic","url":"\/documentation\/kksplayer\/castmanager\/initializecasting(options:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager\/title","value":"CastManager"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager\/fragments","value":[{"kind":"identifier","text":"CastManager"}]},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManagerOptions\/title","value":"CastManagerOptions"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManagerOptions\/fragments","value":[{"kind":"identifier","text":"CastManagerOptions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}