{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"GCKRemoteMediaClientListener.remoteMediaClient(_:didUpdate:)"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kksplayer\/castmanager\/remotemediaclient(_:didupdate:)-8yj2f"]},{"paths":["\/documentation\/kksplayer\/castmanager\/remotemediaclient(_:didupdate:)-8yj2f"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/remoteMediaClient(_:didUpdate:)-8yj2f"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remoteMediaClient","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"client"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GCKRemoteMediaClient","preciseIdentifier":"c:objc(cs)GCKRemoteMediaClient"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didUpdate"},{"text":" ","kind":"text"},{"text":"mediaStatus","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GCKMediaStatus","preciseIdentifier":"c:objc(cs)GCKMediaStatus"},{"kind":"text","text":"?)"}],"languages":["swift"]}]}],"kind":"symbol","metadata":{"symbolKind":"method","modules":[{"name":"KKSPlayer"}],"role":"symbol","title":"remoteMediaClient(_:didUpdate:)","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"remoteMediaClient:didUpdateMediaStatus:"}],"externalID":"c:@CM@KKSPlayer@objc(cs)CastManager(im)remoteMediaClient:didUpdateMediaStatus:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteMediaClient"},{"kind":"text","text":"("},{"text":"GCKRemoteMediaClient","preciseIdentifier":"c:objc(cs)GCKRemoteMediaClient","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didUpdate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKMediaStatus","text":"GCKMediaStatus"},{"kind":"text","text":"?)"}]},"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/GCKRemoteMediaClientListener-Implementations"]]},"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/GCKRemoteMediaClientListener-Implementations":{"title":"GCKRemoteMediaClientListener Implementations","type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/GCKRemoteMediaClientListener-Implementations","url":"\/documentation\/kksplayer\/castmanager\/gckremotemediaclientlistener-implementations","abstract":[],"kind":"article","role":"collectionGroup"},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","role":"collection","url":"\/documentation\/kksplayer","kind":"symbol","title":"KKSPlayer","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager":{"navigatorTitle":[{"text":"CastManager","kind":"identifier"}],"title":"CastManager","type":"topic","kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager","role":"symbol","url":"\/documentation\/kksplayer\/castmanager","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CastManager"}],"abstract":[{"type":"text","text":"Singleton providing access to GoogleCast related features."},{"text":" ","type":"text"},{"text":"The CastManager needs to be initialized by calling CastManager#initializeCasting in the AppDelegate of the application which should support casting.","type":"text"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/remoteMediaClient(_:didUpdate:)-8yj2f":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/remoteMediaClient(_:didUpdate:)-8yj2f","title":"remoteMediaClient(_:didUpdate:)","navigatorTitle":[{"kind":"identifier","text":"remoteMediaClient:didUpdateMediaStatus:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"remoteMediaClient"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GCKRemoteMediaClient","preciseIdentifier":"c:objc(cs)GCKRemoteMediaClient"},{"text":", ","kind":"text"},{"text":"didUpdate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GCKMediaStatus","text":"GCKMediaStatus","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"url":"\/documentation\/kksplayer\/castmanager\/remotemediaclient(_:didupdate:)-8yj2f","abstract":[],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"remoteMediaClient:didUpdateMediaStatus:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"remoteMediaClient:didUpdateMediaStatus:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"remoteMediaClient:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GCKRemoteMediaClient","text":"GCKRemoteMediaClient","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"client","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didUpdateMediaStatus:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKMediaStatus","text":"GCKMediaStatus"},{"kind":"text","text":" *) "},{"text":"mediaStatus","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"CastManager","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager\/title"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager\/fragments","value":[{"text":"CastManager","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1remoteMediaClient(_:didUpdate:)-8yj2f\/title","value":"remoteMediaClient:didUpdateMediaStatus:","op":"replace"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1remoteMediaClient(_:didUpdate:)-8yj2f\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"remoteMediaClient:didUpdateMediaStatus:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}