{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/remoteMediaClient(_:didUpdate:)-3n277"},"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/GCKRemoteMediaClientListener-Implementations"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"remoteMediaClient"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"client"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GCKRemoteMediaClient","preciseIdentifier":"c:objc(cs)GCKRemoteMediaClient"},{"kind":"text","text":", "},{"text":"didUpdate","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"mediaMetadata","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKMediaMetadata","text":"GCKMediaMetadata"},{"text":"?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"modules":[{"name":"KKSPlayer"}],"extendedModule":"KKSPlayer","symbolKind":"method","navigatorTitle":[{"text":"remoteMediaClient:didUpdateMediaMetadata:","kind":"identifier"}],"title":"remoteMediaClient(_:didUpdate:)","role":"symbol","externalID":"c:@CM@KKSPlayer@objc(cs)CastManager(im)remoteMediaClient:didUpdateMediaMetadata:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteMediaClient"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GCKRemoteMediaClient","text":"GCKRemoteMediaClient","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didUpdate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GCKMediaMetadata","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKMediaMetadata"},{"text":"?)","kind":"text"}],"roleHeading":"Instance Method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kksplayer\/castmanager\/remotemediaclient(_:didupdate:)-3n277"]},{"paths":["\/documentation\/kksplayer\/castmanager\/remotemediaclient(_:didupdate:)-3n277"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"GCKRemoteMediaClientListener.remoteMediaClient(_:didUpdate:)"},{"text":".","type":"text"}],"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","role":"collection","url":"\/documentation\/kksplayer","kind":"symbol","title":"KKSPlayer","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager":{"navigatorTitle":[{"text":"CastManager","kind":"identifier"}],"title":"CastManager","type":"topic","kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager","role":"symbol","url":"\/documentation\/kksplayer\/castmanager","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CastManager"}],"abstract":[{"type":"text","text":"Singleton providing access to GoogleCast related features."},{"text":" ","type":"text"},{"text":"The CastManager needs to be initialized by calling CastManager#initializeCasting in the AppDelegate of the application which should support casting.","type":"text"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/remoteMediaClient(_:didUpdate:)-3n277":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/remoteMediaClient(_:didUpdate:)-3n277","title":"remoteMediaClient(_:didUpdate:)","navigatorTitle":[{"kind":"identifier","text":"remoteMediaClient:didUpdateMediaMetadata:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"remoteMediaClient","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GCKRemoteMediaClient","preciseIdentifier":"c:objc(cs)GCKRemoteMediaClient","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdate"},{"kind":"text","text":": "},{"text":"GCKMediaMetadata","preciseIdentifier":"c:objc(cs)GCKMediaMetadata","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"url":"\/documentation\/kksplayer\/castmanager\/remotemediaclient(_:didupdate:)-3n277","abstract":[],"type":"topic","kind":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/GCKRemoteMediaClientListener-Implementations":{"title":"GCKRemoteMediaClientListener Implementations","type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/GCKRemoteMediaClientListener-Implementations","url":"\/documentation\/kksplayer\/castmanager\/gckremotemediaclientlistener-implementations","abstract":[],"kind":"article","role":"collectionGroup"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"remoteMediaClient:didUpdateMediaMetadata:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"remoteMediaClient:didUpdateMediaMetadata:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"remoteMediaClient:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GCKRemoteMediaClient","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKRemoteMediaClient"},{"text":" *) ","kind":"text"},{"text":"client","kind":"internalParam"},{"kind":"text","text":" "},{"text":"didUpdateMediaMetadata:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GCKMediaMetadata","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKMediaMetadata"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"mediaMetadata"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"CastManager","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager\/title","op":"replace"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager\/fragments","value":[{"kind":"identifier","text":"CastManager"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1remoteMediaClient(_:didUpdate:)-3n277\/title","value":"remoteMediaClient:didUpdateMediaMetadata:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"remoteMediaClient:didUpdateMediaMetadata:"}],"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1remoteMediaClient(_:didUpdate:)-3n277\/fragments","op":"replace"}]}]}