{"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"request","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"request"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKRequest","text":"GCKRequest"},{"text":", ","kind":"text"},{"text":"didAbortWith","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"abortReason","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@GCKRequestAbortReason","text":"GCKRequestAbortReason"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/GCKRequestDelegate-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"GCKRequestDelegate.request(_:didAbortWith:)"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/request(_:didAbortWith:)"},"variants":[{"paths":["\/documentation\/kksplayer\/castmanager\/request(_:didabortwith:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/kksplayer\/castmanager\/request(_:didabortwith:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"request(_:didAbortWith:)","navigatorTitle":[{"text":"request:didAbortWithReason:","kind":"identifier"}],"modules":[{"name":"KKSPlayer"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"request","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKRequest","text":"GCKRequest"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didAbortWith"},{"text":": ","kind":"text"},{"text":"GCKRequestAbortReason","kind":"typeIdentifier","preciseIdentifier":"c:@E@GCKRequestAbortReason"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","role":"symbol","externalID":"c:@CM@KKSPlayer@objc(cs)CastManager(im)request:didAbortWithReason:","symbolKind":"method","extendedModule":"KKSPlayer"},"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/request(_:didAbortWith:)":{"abstract":[],"title":"request(_:didAbortWith:)","url":"\/documentation\/kksplayer\/castmanager\/request(_:didabortwith:)","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/request(_:didAbortWith:)","navigatorTitle":[{"text":"request:didAbortWithReason:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"request","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GCKRequest","text":"GCKRequest","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didAbortWith"},{"text":": ","kind":"text"},{"text":"GCKRequestAbortReason","kind":"typeIdentifier","preciseIdentifier":"c:@E@GCKRequestAbortReason"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager":{"navigatorTitle":[{"text":"CastManager","kind":"identifier"}],"title":"CastManager","type":"topic","kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager","role":"symbol","url":"\/documentation\/kksplayer\/castmanager","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CastManager"}],"abstract":[{"type":"text","text":"Singleton providing access to GoogleCast related features."},{"text":" ","type":"text"},{"text":"The CastManager needs to be initialized by calling CastManager#initializeCasting in the AppDelegate of the application which should support casting.","type":"text"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/GCKRequestDelegate-Implementations":{"title":"GCKRequestDelegate Implementations","type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/GCKRequestDelegate-Implementations","url":"\/documentation\/kksplayer\/castmanager\/gckrequestdelegate-implementations","abstract":[],"kind":"article","role":"collectionGroup"},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","role":"collection","url":"\/documentation\/kksplayer","kind":"symbol","title":"KKSPlayer","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"request:didAbortWithReason:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"request:didAbortWithReason:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"request:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKRequest","text":"GCKRequest"},{"text":" *) ","kind":"text"},{"text":"request","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"didAbortWithReason:"},{"kind":"text","text":"("},{"text":"GCKRequestAbortReason","kind":"typeIdentifier","preciseIdentifier":"c:@E@GCKRequestAbortReason"},{"text":") ","kind":"text"},{"text":"abortReason","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1request(_:didAbortWith:)\/title","value":"request:didAbortWithReason:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"request:didAbortWithReason:"}],"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1request(_:didAbortWith:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager\/title","value":"CastManager"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager\/fragments","value":[{"text":"CastManager","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}