{"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/GCKRequestDelegate-Implementations"]]},"metadata":{"modules":[{"name":"KKSPlayer"}],"title":"request(_:didFailWithError:)","externalID":"c:@CM@KKSPlayer@objc(cs)CastManager(im)request:didFailWithError:","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"request:didFailWithError:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"request"},{"text":"(","kind":"text"},{"text":"GCKRequest","preciseIdentifier":"c:objc(cs)GCKRequest","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFailWithError","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKError","text":"GCKError"},{"text":")","kind":"text"}],"symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kksplayer\/castmanager\/request(_:didfailwitherror:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/kksplayer\/castmanager\/request(_:didfailwitherror:)"]}],"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"GCKRequestDelegate.request(_:didFailWithError:)"},{"text":".","type":"text"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/request(_:didFailWithError:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"request"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"request","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"GCKRequest","preciseIdentifier":"c:objc(cs)GCKRequest","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFailWithError","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GCKError","kind":"typeIdentifier","text":"GCKError"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","role":"collection","url":"\/documentation\/kksplayer","kind":"symbol","title":"KKSPlayer","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/GCKRequestDelegate-Implementations":{"title":"GCKRequestDelegate Implementations","type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/GCKRequestDelegate-Implementations","url":"\/documentation\/kksplayer\/castmanager\/gckrequestdelegate-implementations","abstract":[],"kind":"article","role":"collectionGroup"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/request(_:didFailWithError:)":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/request(_:didFailWithError:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"request"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKRequest","text":"GCKRequest"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailWithError"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GCKError","text":"GCKError","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/kksplayer\/castmanager\/request(_:didfailwitherror:)","navigatorTitle":[{"kind":"identifier","text":"request:didFailWithError:"}],"type":"topic","title":"request(_:didFailWithError:)","kind":"symbol","abstract":[]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager":{"navigatorTitle":[{"text":"CastManager","kind":"identifier"}],"title":"CastManager","type":"topic","kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager","role":"symbol","url":"\/documentation\/kksplayer\/castmanager","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CastManager"}],"abstract":[{"type":"text","text":"Singleton providing access to GoogleCast related features."},{"text":" ","type":"text"},{"text":"The CastManager needs to be initialized by calling CastManager#initializeCasting in the AppDelegate of the application which should support casting.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"request:didFailWithError:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"request:didFailWithError:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"request:"},{"text":"(","kind":"text"},{"text":"GCKRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKRequest"},{"text":" *) ","kind":"text"},{"text":"request","kind":"internalParam"},{"kind":"text","text":" "},{"text":"didFailWithError:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GCKError","text":"GCKError","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"request:didFailWithError:","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1request(_:didFailWithError:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1request(_:didFailWithError:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"request:didFailWithError:"}]},{"value":"CastManager","op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager\/title"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager\/fragments","op":"replace","value":[{"text":"CastManager","kind":"identifier"}]}]}]}