{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@CM@KKSPlayer@objc(cs)CastManager(im)requestDidComplete:","navigatorTitle":[{"text":"requestDidComplete:","kind":"identifier"}],"modules":[{"relatedModules":["KKSPlayer"],"name":"BVPlayer"}],"symbolKind":"method","extendedModule":"KKSPlayer","role":"symbol","title":"requestDidComplete(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"requestDidComplete","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKRequest","text":"GCKRequest"},{"kind":"text","text":")"}],"roleHeading":"Instance Method"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestDidComplete"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"request","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GCKRequest","text":"GCKRequest","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/requestDidComplete(_:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/GCKRequestDelegate-Implementations"]]},"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"GCKRequestDelegate.requestDidComplete(_:)"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kksplayer\/castmanager\/requestdidcomplete(_:)"]},{"paths":["\/documentation\/kksplayer\/castmanager\/requestdidcomplete(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/GCKRequestDelegate-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/GCKRequestDelegate-Implementations","kind":"article","title":"GCKRequestDelegate Implementations","type":"topic","abstract":[],"url":"\/documentation\/kksplayer\/castmanager\/gckrequestdelegate-implementations"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager":{"type":"topic","url":"\/documentation\/kksplayer\/castmanager","abstract":[{"text":"Singleton providing access to GoogleCast related features.","type":"text"},{"text":" ","type":"text"},{"text":"The CastManager needs to be initialized by calling CastManager#initializeCasting in the AppDelegate of the application which should support casting.","type":"text"}],"title":"CastManager","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CastManager","kind":"identifier"}],"navigatorTitle":[{"text":"CastManager","kind":"identifier"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/requestDidComplete(_:)":{"navigatorTitle":[{"kind":"identifier","text":"requestDidComplete:"}],"title":"requestDidComplete(_:)","type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/requestDidComplete(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"requestDidComplete","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GCKRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKRequest"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/kksplayer\/castmanager\/requestdidcomplete(_:)"},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","abstract":[{"text":"BlendVision One iOS Player SDK","type":"text"}],"title":"BVPlayer","url":"\/documentation\/kksplayer","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"requestDidComplete:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"requestDidComplete:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"requestDidComplete:"},{"kind":"text","text":"("},{"text":"GCKRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKRequest"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"request"},{"kind":"text","text":";"}]}]}},{"value":"CastManager","op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager\/title"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager\/fragments","value":[{"text":"CastManager","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"requestDidComplete:","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1requestDidComplete(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1requestDidComplete(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestDidComplete:"}]}]}]}