{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/sessionManager(_:didStart:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/GCKSessionManagerListener-Implementations"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kksplayer\/castmanager\/sessionmanager(_:didstart:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/kksplayer\/castmanager\/sessionmanager(_:didstart:)"]}],"metadata":{"externalID":"c:@CM@KKSPlayer@objc(cs)CastManager(im)sessionManager:didStartCastSession:","navigatorTitle":[{"text":"sessionManager:didStartCastSession:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"BVPlayer"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"sessionManager","kind":"identifier"},{"kind":"text","text":"("},{"text":"GCKSessionManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKSessionManager"},{"text":", ","kind":"text"},{"text":"didStart","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GCKCastSession","preciseIdentifier":"c:objc(cs)GCKCastSession","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"sessionManager(_:didStart:)","roleHeading":"Instance Method"},"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"GCKSessionManagerListener.sessionManager(_:didStart:)"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sessionManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sessionManager","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"GCKSessionManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKSessionManager"},{"kind":"text","text":", "},{"text":"didStart","kind":"externalParam"},{"kind":"text","text":" "},{"text":"session","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"GCKCastSession","preciseIdentifier":"c:objc(cs)GCKCastSession","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","abstract":[{"text":"BlendVision One iOS Player SDK","type":"text"}],"title":"BVPlayer","url":"\/documentation\/kksplayer","kind":"symbol","role":"collection"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/GCKSessionManagerListener-Implementations":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/GCKSessionManagerListener-Implementations","type":"topic","abstract":[],"title":"GCKSessionManagerListener Implementations","role":"collectionGroup","kind":"article","url":"\/documentation\/kksplayer\/castmanager\/gcksessionmanagerlistener-implementations"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/sessionManager(_:didStart:)":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/sessionManager(_:didStart:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionManager"},{"text":"(","kind":"text"},{"text":"GCKSessionManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKSessionManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStart"},{"kind":"text","text":": "},{"text":"GCKCastSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKCastSession"},{"kind":"text","text":")"}],"role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"sessionManager:didStartCastSession:","kind":"identifier"}],"title":"sessionManager(_:didStart:)","url":"\/documentation\/kksplayer\/castmanager\/sessionmanager(_:didstart:)"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager":{"type":"topic","url":"\/documentation\/kksplayer\/castmanager","abstract":[{"text":"Singleton providing access to GoogleCast related features.","type":"text"},{"text":" ","type":"text"},{"text":"The CastManager needs to be initialized by calling CastManager#initializeCasting in the AppDelegate of the application which should support casting.","type":"text"}],"title":"CastManager","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CastManager","kind":"identifier"}],"navigatorTitle":[{"text":"CastManager","kind":"identifier"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"sessionManager:didStartCastSession:","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"sessionManager:didStartCastSession:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"sessionManager:"},{"text":"(","kind":"text"},{"text":"GCKSessionManager","preciseIdentifier":"c:objc(cs)GCKSessionManager","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sessionManager"},{"kind":"text","text":" "},{"text":"didStartCastSession:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"GCKCastSession","preciseIdentifier":"c:objc(cs)GCKCastSession"},{"kind":"text","text":" *) "},{"text":"session","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1sessionManager(_:didStart:)\/title","op":"replace","value":"sessionManager:didStartCastSession:"},{"value":[{"text":"- ","kind":"text"},{"text":"sessionManager:didStartCastSession:","kind":"identifier"}],"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1sessionManager(_:didStart:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager\/title","value":"CastManager","op":"replace"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager\/fragments","value":[{"kind":"identifier","text":"CastManager"}],"op":"replace"}]}]}