{"metadata":{"role":"symbol","externalID":"c:@CM@KKSPlayer@objc(cs)CastManager(im)sessionManager:didResumeCastSession:","title":"sessionManager(_:didResumeCastSession:)","modules":[{"name":"BVPlayer"}],"roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"text":"sessionManager:didResumeCastSession:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sessionManager"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GCKSessionManager","text":"GCKSessionManager","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didResumeCastSession","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKCastSession","text":"GCKCastSession"},{"text":")","kind":"text"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sessionManager"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"sessionManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKSessionManager","text":"GCKSessionManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didResumeCastSession"},{"kind":"text","text":" "},{"text":"session","kind":"internalParam"},{"kind":"text","text":": "},{"text":"GCKCastSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKCastSession"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"GCKSessionManagerListener.sessionManager(_:didResumeCastSession:)"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kksplayer\/castmanager\/sessionmanager(_:didresumecastsession:)"]},{"paths":["\/documentation\/kksplayer\/castmanager\/sessionmanager(_:didresumecastsession:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/GCKSessionManagerListener-Implementations"]]},"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/sessionManager(_:didResumeCastSession:)","interfaceLanguage":"swift"},"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager":{"type":"topic","url":"\/documentation\/kksplayer\/castmanager","abstract":[{"text":"Singleton providing access to GoogleCast related features.","type":"text"},{"text":" ","type":"text"},{"text":"The CastManager needs to be initialized by calling CastManager#initializeCasting in the AppDelegate of the application which should support casting.","type":"text"}],"title":"CastManager","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CastManager","kind":"identifier"}],"navigatorTitle":[{"text":"CastManager","kind":"identifier"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/GCKSessionManagerListener-Implementations":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/GCKSessionManagerListener-Implementations","type":"topic","abstract":[],"title":"GCKSessionManagerListener Implementations","role":"collectionGroup","kind":"article","url":"\/documentation\/kksplayer\/castmanager\/gcksessionmanagerlistener-implementations"},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","abstract":[{"text":"BlendVision One iOS Player SDK","type":"text"}],"title":"BVPlayer","url":"\/documentation\/kksplayer","kind":"symbol","role":"collection"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/sessionManager(_:didResumeCastSession:)":{"url":"\/documentation\/kksplayer\/castmanager\/sessionmanager(_:didresumecastsession:)","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/sessionManager(_:didResumeCastSession:)","abstract":[],"title":"sessionManager(_:didResumeCastSession:)","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sessionManager"},{"text":"(","kind":"text"},{"text":"GCKSessionManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKSessionManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didResumeCastSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GCKCastSession","preciseIdentifier":"c:objc(cs)GCKCastSession"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"sessionManager:didResumeCastSession:","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"sessionManager:didResumeCastSession:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"sessionManager:didResumeCastSession:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"sessionManager:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"GCKSessionManager","preciseIdentifier":"c:objc(cs)GCKSessionManager"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sessionManager"},{"kind":"text","text":" "},{"kind":"identifier","text":"didResumeCastSession:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKCastSession","text":"GCKCastSession"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"session"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager\/title","value":"CastManager","op":"replace"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager\/fragments","op":"replace","value":[{"text":"CastManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1sessionManager(_:didResumeCastSession:)\/title","value":"sessionManager:didResumeCastSession:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"sessionManager:didResumeCastSession:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1sessionManager(_:didResumeCastSession:)\/fragments"}]}]}