{"variants":[{"paths":["\/documentation\/kksplayer\/castmanager\/sessionmanager(_:didsuspend:with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/kksplayer\/castmanager\/sessionmanager(_:didsuspend:with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"GCKSessionManagerListener.sessionManager(_:didSuspend:with:)"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"sessionManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sessionManager","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKSessionManager","text":"GCKSessionManager"},{"text":", ","kind":"text"},{"text":"didSuspend","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"session"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GCKCastSession","text":"GCKCastSession","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"reason"},{"text":": ","kind":"text"},{"text":"GCKConnectionSuspendReason","kind":"typeIdentifier","preciseIdentifier":"c:@E@GCKConnectionSuspendReason"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"sections":[],"metadata":{"externalID":"c:@CM@KKSPlayer@objc(cs)CastManager(im)sessionManager:didSuspendCastSession:withReason:","navigatorTitle":[{"kind":"identifier","text":"sessionManager:didSuspendCastSession:withReason:"}],"symbolKind":"method","modules":[{"name":"BVPlayer"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sessionManager"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKSessionManager","text":"GCKSessionManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didSuspend"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GCKCastSession","preciseIdentifier":"c:objc(cs)GCKCastSession"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GCKConnectionSuspendReason","preciseIdentifier":"c:@E@GCKConnectionSuspendReason","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"sessionManager(_:didSuspend:with:)","roleHeading":"Instance Method"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/GCKSessionManagerListener-Implementations"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/sessionManager(_:didSuspend:with:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","abstract":[{"text":"BlendVision One iOS Player SDK","type":"text"}],"title":"BVPlayer","url":"\/documentation\/kksplayer","kind":"symbol","role":"collection"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager":{"type":"topic","url":"\/documentation\/kksplayer\/castmanager","abstract":[{"text":"Singleton providing access to GoogleCast related features.","type":"text"},{"text":" ","type":"text"},{"text":"The CastManager needs to be initialized by calling CastManager#initializeCasting in the AppDelegate of the application which should support casting.","type":"text"}],"title":"CastManager","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CastManager","kind":"identifier"}],"navigatorTitle":[{"text":"CastManager","kind":"identifier"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/sessionManager(_:didSuspend:with:)":{"type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/sessionManager(_:didSuspend:with:)","url":"\/documentation\/kksplayer\/castmanager\/sessionmanager(_:didsuspend:with:)","navigatorTitle":[{"kind":"identifier","text":"sessionManager:didSuspendCastSession:withReason:"}],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionManager"},{"text":"(","kind":"text"},{"text":"GCKSessionManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKSessionManager"},{"text":", ","kind":"text"},{"text":"didSuspend","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GCKCastSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKCastSession"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"text":"GCKConnectionSuspendReason","kind":"typeIdentifier","preciseIdentifier":"c:@E@GCKConnectionSuspendReason"},{"text":")","kind":"text"}],"abstract":[],"title":"sessionManager(_:didSuspend:with:)"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/GCKSessionManagerListener-Implementations":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/GCKSessionManagerListener-Implementations","type":"topic","abstract":[],"title":"GCKSessionManagerListener Implementations","role":"collectionGroup","kind":"article","url":"\/documentation\/kksplayer\/castmanager\/gcksessionmanagerlistener-implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"sessionManager:didSuspendCastSession:withReason:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"sessionManager:didSuspendCastSession:withReason:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"sessionManager:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GCKSessionManager","text":"GCKSessionManager","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"sessionManager"},{"kind":"text","text":" "},{"text":"didSuspendCastSession:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKCastSession","text":"GCKCastSession"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"session"},{"kind":"text","text":" "},{"text":"withReason:","kind":"identifier"},{"kind":"text","text":"("},{"text":"GCKConnectionSuspendReason","preciseIdentifier":"c:@E@GCKConnectionSuspendReason","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"reason","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager\/title","op":"replace","value":"CastManager"},{"value":[{"kind":"identifier","text":"CastManager"}],"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1sessionManager(_:didSuspend:with:)\/title","value":"sessionManager:didSuspendCastSession:withReason:","op":"replace"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1sessionManager(_:didSuspend:with:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"sessionManager:didSuspendCastSession:withReason:","kind":"identifier"}],"op":"replace"}]}]}