{"sections":[],"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/GCKSessionManagerListener-Implementations"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kksplayer\/castmanager\/sessionmanager(_:didfailtostart:witherror:)"]},{"paths":["\/documentation\/kksplayer\/castmanager\/sessionmanager(_:didfailtostart:witherror:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/sessionManager(_:didFailToStart:withError:)","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"sessionManager:didFailToStartCastSession:withError:","kind":"identifier"}],"modules":[{"name":"KKSPlayer"}],"title":"sessionManager(_:didFailToStart:withError:)","symbolKind":"method","extendedModule":"KKSPlayer","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sessionManager"},{"text":"(","kind":"text"},{"text":"GCKSessionManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKSessionManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailToStart"},{"kind":"text","text":": "},{"text":"GCKCastSession","preciseIdentifier":"c:objc(cs)GCKCastSession","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withError"},{"kind":"text","text":": "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":")"}],"externalID":"c:@CM@KKSPlayer@objc(cs)CastManager(im)sessionManager:didFailToStartCastSession:withError:","roleHeading":"Instance Method","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"sessionManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"sessionManager","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"GCKSessionManager","preciseIdentifier":"c:objc(cs)GCKSessionManager","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didFailToStart","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"session","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"GCKCastSession","preciseIdentifier":"c:objc(cs)GCKCastSession","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"withError"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"GCKSessionManagerListener.sessionManager(_:didFailToStart:withError:)"},{"type":"text","text":"."}],"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/sessionManager(_:didFailToStart:withError:)":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/sessionManager(_:didFailToStart:withError:)","url":"\/documentation\/kksplayer\/castmanager\/sessionmanager(_:didfailtostart:witherror:)","title":"sessionManager(_:didFailToStart:withError:)","type":"topic","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sessionManager"},{"text":"(","kind":"text"},{"text":"GCKSessionManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKSessionManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFailToStart"},{"kind":"text","text":": "},{"text":"GCKCastSession","preciseIdentifier":"c:objc(cs)GCKCastSession","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withError"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"sessionManager:didFailToStartCastSession:withError:","kind":"identifier"}],"role":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","role":"collection","url":"\/documentation\/kksplayer","kind":"symbol","title":"KKSPlayer","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/GCKSessionManagerListener-Implementations":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/GCKSessionManagerListener-Implementations","url":"\/documentation\/kksplayer\/castmanager\/gcksessionmanagerlistener-implementations","abstract":[],"kind":"article","role":"collectionGroup","title":"GCKSessionManagerListener Implementations","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager":{"navigatorTitle":[{"text":"CastManager","kind":"identifier"}],"title":"CastManager","type":"topic","kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager","role":"symbol","url":"\/documentation\/kksplayer\/castmanager","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CastManager"}],"abstract":[{"type":"text","text":"Singleton providing access to GoogleCast related features."},{"text":" ","type":"text"},{"text":"The CastManager needs to be initialized by calling CastManager#initializeCasting in the AppDelegate of the application which should support casting.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"sessionManager:didFailToStartCastSession:withError:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sessionManager:didFailToStartCastSession:withError:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"sessionManager:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GCKSessionManager","text":"GCKSessionManager","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"sessionManager"},{"text":" ","kind":"text"},{"text":"didFailToStartCastSession:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"GCKCastSession","preciseIdentifier":"c:objc(cs)GCKCastSession"},{"text":" *) ","kind":"text"},{"text":"session","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withError:"},{"text":"(","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"sessionManager:didFailToStartCastSession:withError:","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1sessionManager(_:didFailToStart:withError:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"sessionManager:didFailToStartCastSession:withError:","kind":"identifier"}],"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1sessionManager(_:didFailToStart:withError:)\/fragments"},{"op":"replace","value":"CastManager","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager\/title"},{"value":[{"text":"CastManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager\/fragments"}]}]}