{"variants":[{"paths":["\/documentation\/kksplayer\/castmanager\/sessionmanager(_:willstart:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/kksplayer\/castmanager\/sessionmanager(_:willstart:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/sessionManager(_:willStart:)"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"GCKSessionManagerListener.sessionManager(_:willStart:)","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","metadata":{"extendedModule":"KKSPlayer","title":"sessionManager(_:willStart:)","externalID":"c:@CM@KKSPlayer@objc(cs)CastManager(im)sessionManager:willStartCastSession:","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"sessionManager:willStartCastSession:","kind":"identifier"}],"modules":[{"name":"KKSPlayer"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sessionManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GCKSessionManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKSessionManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willStart"},{"kind":"text","text":": "},{"text":"GCKCastSession","preciseIdentifier":"c:objc(cs)GCKCastSession","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"sessionManager","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"sessionManager"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GCKSessionManager","kind":"typeIdentifier","text":"GCKSessionManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willStart"},{"text":" ","kind":"text"},{"text":"session","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GCKCastSession","text":"GCKCastSession","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/GCKSessionManagerListener-Implementations"]]},"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/GCKSessionManagerListener-Implementations":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/GCKSessionManagerListener-Implementations","url":"\/documentation\/kksplayer\/castmanager\/gcksessionmanagerlistener-implementations","abstract":[],"kind":"article","role":"collectionGroup","title":"GCKSessionManagerListener Implementations","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/sessionManager(_:willStart:)":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/sessionManager(_:willStart:)","abstract":[],"url":"\/documentation\/kksplayer\/castmanager\/sessionmanager(_:willstart:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"sessionManager:willStartCastSession:"}],"type":"topic","title":"sessionManager(_:willStart:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sessionManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GCKSessionManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKSessionManager"},{"text":", ","kind":"text"},{"text":"willStart","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GCKCastSession","preciseIdentifier":"c:objc(cs)GCKCastSession"},{"kind":"text","text":")"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","role":"collection","url":"\/documentation\/kksplayer","kind":"symbol","title":"KKSPlayer","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager":{"navigatorTitle":[{"text":"CastManager","kind":"identifier"}],"title":"CastManager","type":"topic","kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager","role":"symbol","url":"\/documentation\/kksplayer\/castmanager","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CastManager"}],"abstract":[{"type":"text","text":"Singleton providing access to GoogleCast related features."},{"text":" ","type":"text"},{"text":"The CastManager needs to be initialized by calling CastManager#initializeCasting in the AppDelegate of the application which should support casting.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"sessionManager:willStartCastSession:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"sessionManager:willStartCastSession:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"sessionManager:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKSessionManager","text":"GCKSessionManager"},{"text":" *) ","kind":"text"},{"text":"sessionManager","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"willStartCastSession:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKCastSession","text":"GCKCastSession"},{"kind":"text","text":" *) "},{"text":"session","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1sessionManager(_:willStart:)\/title","value":"sessionManager:willStartCastSession:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sessionManager:willStartCastSession:"}],"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1sessionManager(_:willStart:)\/fragments"},{"value":"CastManager","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager\/fragments","value":[{"kind":"identifier","text":"CastManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}