{"kind":"symbol","identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/sessionManager(_:didEnd:withError:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/GCKSessionManagerListener-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"GCKSessionManagerListener.sessionManager(_:didEnd:withError:)"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sessionManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sessionManager","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)GCKSessionManager","kind":"typeIdentifier","text":"GCKSessionManager"},{"text":", ","kind":"text"},{"text":"didEnd","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"session"},{"text":": ","kind":"text"},{"text":"GCKCastSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKCastSession"},{"kind":"text","text":", "},{"text":"withError","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"metadata":{"externalID":"c:@CM@KKSPlayer@objc(cs)CastManager(im)sessionManager:didEndCastSession:withError:","role":"symbol","navigatorTitle":[{"text":"sessionManager:didEndCastSession:withError:","kind":"identifier"}],"extendedModule":"KKSPlayer","roleHeading":"Instance Method","modules":[{"name":"KKSPlayer"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionManager"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GCKSessionManager","text":"GCKSessionManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didEnd","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GCKCastSession","text":"GCKCastSession","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"withError"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?)","kind":"text"}],"title":"sessionManager(_:didEnd:withError:)","symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kksplayer\/castmanager\/sessionmanager(_:didend:witherror:)"]},{"paths":["\/documentation\/kksplayer\/castmanager\/sessionmanager(_:didend:witherror:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/sessionManager(_:didEnd:withError:)":{"role":"symbol","url":"\/documentation\/kksplayer\/castmanager\/sessionmanager(_:didend:witherror:)","navigatorTitle":[{"kind":"identifier","text":"sessionManager:didEndCastSession:withError:"}],"type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/sessionManager(_:didEnd:withError:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sessionManager","kind":"identifier"},{"kind":"text","text":"("},{"text":"GCKSessionManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKSessionManager"},{"text":", ","kind":"text"},{"text":"didEnd","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GCKCastSession","preciseIdentifier":"c:objc(cs)GCKCastSession"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"withError"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"title":"sessionManager(_:didEnd:withError:)"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/GCKSessionManagerListener-Implementations":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/GCKSessionManagerListener-Implementations","url":"\/documentation\/kksplayer\/castmanager\/gcksessionmanagerlistener-implementations","abstract":[],"kind":"article","role":"collectionGroup","title":"GCKSessionManagerListener Implementations","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager":{"navigatorTitle":[{"text":"CastManager","kind":"identifier"}],"title":"CastManager","type":"topic","kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager","role":"symbol","url":"\/documentation\/kksplayer\/castmanager","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CastManager"}],"abstract":[{"type":"text","text":"Singleton providing access to GoogleCast related features."},{"text":" ","type":"text"},{"text":"The CastManager needs to be initialized by calling CastManager#initializeCasting in the AppDelegate of the application which should support casting.","type":"text"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","role":"collection","url":"\/documentation\/kksplayer","kind":"symbol","title":"KKSPlayer","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"sessionManager:didEndCastSession:withError:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sessionManager:didEndCastSession:withError:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"sessionManager:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)GCKSessionManager","text":"GCKSessionManager","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"sessionManager"},{"kind":"text","text":" "},{"text":"didEndCastSession:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GCKCastSession","kind":"typeIdentifier","text":"GCKCastSession"},{"text":" *) ","kind":"text"},{"text":"session","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"withError:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1sessionManager(_:didEnd:withError:)\/title","op":"replace","value":"sessionManager:didEndCastSession:withError:"},{"value":[{"text":"- ","kind":"text"},{"text":"sessionManager:didEndCastSession:withError:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1sessionManager(_:didEnd:withError:)\/fragments"},{"op":"replace","value":"CastManager","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager\/title"},{"value":[{"kind":"identifier","text":"CastManager"}],"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager\/fragments"}]}]}