{"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/sessionManager(_:willResumeCastSession:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"code":"GCKSessionManagerListener.sessionManager(_:willResumeCastSession:)","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/GCKSessionManagerListener-Implementations"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"sessionManager","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"sessionManager","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKSessionManager","text":"GCKSessionManager"},{"text":", ","kind":"text"},{"text":"willResumeCastSession","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"session"},{"text":": ","kind":"text"},{"text":"GCKCastSession","preciseIdentifier":"c:objc(cs)GCKCastSession","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]}],"metadata":{"symbolKind":"method","role":"symbol","extendedModule":"KKSPlayer","modules":[{"name":"KKSPlayer"}],"roleHeading":"Instance Method","title":"sessionManager(_:willResumeCastSession:)","externalID":"c:@CM@KKSPlayer@objc(cs)CastManager(im)sessionManager:willResumeCastSession:","navigatorTitle":[{"text":"sessionManager:willResumeCastSession:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionManager"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"GCKSessionManager","preciseIdentifier":"c:objc(cs)GCKSessionManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"willResumeCastSession"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)GCKCastSession","text":"GCKCastSession","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kksplayer\/castmanager\/sessionmanager(_:willresumecastsession:)"]},{"paths":["\/documentation\/kksplayer\/castmanager\/sessionmanager(_:willresumecastsession:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","role":"collection","url":"\/documentation\/kksplayer","kind":"symbol","title":"KKSPlayer","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/GCKSessionManagerListener-Implementations":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/GCKSessionManagerListener-Implementations","url":"\/documentation\/kksplayer\/castmanager\/gcksessionmanagerlistener-implementations","abstract":[],"kind":"article","role":"collectionGroup","title":"GCKSessionManagerListener Implementations","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager/sessionManager(_:willResumeCastSession:)":{"url":"\/documentation\/kksplayer\/castmanager\/sessionmanager(_:willresumecastsession:)","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager\/sessionManager(_:willResumeCastSession:)","type":"topic","title":"sessionManager(_:willResumeCastSession:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sessionManager","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)GCKSessionManager","text":"GCKSessionManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"willResumeCastSession"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GCKCastSession","preciseIdentifier":"c:objc(cs)GCKCastSession"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"sessionManager:willResumeCastSession:"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/CastManager":{"navigatorTitle":[{"text":"CastManager","kind":"identifier"}],"title":"CastManager","type":"topic","kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/CastManager","role":"symbol","url":"\/documentation\/kksplayer\/castmanager","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CastManager"}],"abstract":[{"type":"text","text":"Singleton providing access to GoogleCast related features."},{"text":" ","type":"text"},{"text":"The CastManager needs to be initialized by calling CastManager#initializeCasting in the AppDelegate of the application which should support casting.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"sessionManager:willResumeCastSession:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"sessionManager:willResumeCastSession:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"sessionManager:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKSessionManager","text":"GCKSessionManager"},{"text":" *) ","kind":"text"},{"text":"sessionManager","kind":"internalParam"},{"kind":"text","text":" "},{"text":"willResumeCastSession:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GCKCastSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)GCKCastSession"},{"kind":"text","text":" *) "},{"text":"session","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"sessionManager:willResumeCastSession:","op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1sessionManager(_:willResumeCastSession:)\/title"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager~1sessionManager(_:willResumeCastSession:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sessionManager:willResumeCastSession:"}]},{"value":"CastManager","op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager\/title"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1CastManager\/fragments","value":[{"text":"CastManager","kind":"identifier"}]}]}]}