{"sections":[],"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"audio","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniAudioTrack","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniAudioTrack","text":"UniAudioTrack","kind":"typeIdentifier"},{"kind":"text","text":"? { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/audio","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns the currently used audio track."},{"text":" ","type":"text"},{"type":"text","text":"Before the Source finished loading this property will always return nil."}],"metadata":{"symbolKind":"property","role":"symbol","modules":[{"name":"KKSPlayer"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"audio","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UniAudioTrack","kind":"typeIdentifier","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniAudioTrack"},{"text":"?","kind":"text"}],"title":"audio","externalID":"s:9KKSPlayer9UniPlayerC5audioAA0B10AudioTrackCSgvp"},"kind":"symbol","variants":[{"paths":["\/documentation\/kksplayer\/uniplayer\/audio"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UniPlayer","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"UniPlayer"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer","type":"topic","url":"\/documentation\/kksplayer\/uniplayer","title":"UniPlayer","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"An object that provides the interface to control the player’s transport behavior."}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/audio":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/audio","url":"\/documentation\/kksplayer\/uniplayer\/audio","abstract":[{"type":"text","text":"Returns the currently used audio track."},{"text":" ","type":"text"},{"type":"text","text":"Before the Source finished loading this property will always return nil."}],"kind":"symbol","role":"symbol","title":"audio","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"audio","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UniAudioTrack","kind":"typeIdentifier","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniAudioTrack"},{"kind":"text","text":"?"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniAudioTrack":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniAudioTrack"}],"title":"UniAudioTrack","url":"\/documentation\/kksplayer\/uniaudiotrack","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniAudioTrack","abstract":[],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UniAudioTrack"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","role":"collection","url":"\/documentation\/kksplayer","kind":"symbol","title":"KKSPlayer","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/title","value":"UniPlayer"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/fragments","value":[{"text":"UniPlayer","kind":"identifier"}]},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniAudioTrack\/title","value":"UniAudioTrack","op":"replace"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniAudioTrack\/fragments","op":"replace","value":[{"text":"UniAudioTrack","kind":"identifier"}]}]}]}