{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"availableSubtitles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSubtitleTrack","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniSubtitleTrack","text":"UniSubtitleTrack"},{"kind":"text","text":"] { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/kksplayer\/uniplayer\/availablesubtitles"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/availableSubtitles","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns an array containing SubtitleTrack objects for all available subtitle tracks."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"availableSubtitles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UniSubtitleTrack","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniSubtitleTrack"},{"kind":"text","text":"]"}],"title":"availableSubtitles","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:9KKSPlayer9UniPlayerC18availableSubtitlesSayAA0B13SubtitleTrackCGvp","modules":[{"name":"KKSPlayer"}]},"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer"]]},"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer":{"role":"symbol","title":"UniPlayer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniPlayer"}],"abstract":[{"type":"text","text":"An object that provides the interface to control the player’s transport behavior."}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UniPlayer"}],"url":"\/documentation\/kksplayer\/uniplayer"},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"role":"collection","title":"KKSPlayer","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","kind":"symbol","type":"topic","url":"\/documentation\/kksplayer"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/availableSubtitles":{"role":"symbol","title":"availableSubtitles","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"availableSubtitles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UniSubtitleTrack","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniSubtitleTrack"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Returns an array containing SubtitleTrack objects for all available subtitle tracks."}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/availableSubtitles","kind":"symbol","type":"topic","url":"\/documentation\/kksplayer\/uniplayer\/availablesubtitles"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSubtitleTrack":{"role":"symbol","title":"UniSubtitleTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniSubtitleTrack"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSubtitleTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UniSubtitleTrack"}],"url":"\/documentation\/kksplayer\/unisubtitletrack"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/title","value":"UniPlayer"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/fragments","value":[{"kind":"identifier","text":"UniPlayer"}]},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSubtitleTrack\/title","value":"UniSubtitleTrack"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSubtitleTrack\/fragments","value":[{"kind":"identifier","text":"UniSubtitleTrack"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}