{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"availableAudio"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniAudioTrack","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniAudioTrack","text":"UniAudioTrack"},{"kind":"text","text":"] { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/kksplayer\/uniplayer\/availableaudio"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/availableAudio","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns an array containing all available audio tracks."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"availableAudio"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UniAudioTrack","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniAudioTrack"},{"kind":"text","text":"]"}],"title":"availableAudio","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:9KKSPlayer9UniPlayerC14availableAudioSayAA0bE5TrackCGvp","modules":[{"name":"KKSPlayer"}]},"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer"]]},"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer":{"role":"symbol","title":"UniPlayer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniPlayer"}],"abstract":[{"type":"text","text":"Loads, controls and renders audio and video content represented through Sources."},{"type":"text","text":" "},{"type":"text","text":"A player instance can be created via the UniPlayerFactory.create function and will idle until one or more Sources are loaded."},{"type":"text","text":" "},{"type":"text","text":"Once load is called, the player becomes active and initiates necessary downloads to start playback of the loaded source(s)."}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UniPlayer"}],"url":"\/documentation\/kksplayer\/uniplayer"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/availableAudio":{"role":"symbol","title":"availableAudio","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"availableAudio"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UniAudioTrack","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniAudioTrack"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Returns an array containing all available audio tracks."}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/availableAudio","kind":"symbol","type":"topic","url":"\/documentation\/kksplayer\/uniplayer\/availableaudio"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniAudioTrack":{"role":"symbol","title":"UniAudioTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniAudioTrack"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniAudioTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UniAudioTrack"}],"url":"\/documentation\/kksplayer\/uniaudiotrack"},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"role":"collection","title":"KKSPlayer","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","kind":"symbol","type":"topic","url":"\/documentation\/kksplayer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/title","value":"UniPlayer"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/fragments","value":[{"kind":"identifier","text":"UniPlayer"}]},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniAudioTrack\/title","value":"UniAudioTrack"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniAudioTrack\/fragments","value":[{"kind":"identifier","text":"UniAudioTrack"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}