{"variants":[{"paths":["\/documentation\/kksplayer\/uniplayer\/avassetresourceloaderdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/kksplayer\/uniplayer\/avassetresourceloaderdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/AVAssetResourceLoaderDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/resourceLoader(_:shouldWaitForLoadingOfRequestedResource:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"KKSPlayer"}],"role":"collectionGroup","title":"AVAssetResourceLoaderDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer"]]},"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"role":"collection","title":"KKSPlayer","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","kind":"symbol","type":"topic","url":"\/documentation\/kksplayer"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/resourceLoader(_:shouldWaitForLoadingOfRequestedResource:)":{"role":"symbol","title":"resourceLoader(_:shouldWaitForLoadingOfRequestedResource:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resourceLoader"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVAssetResourceLoader","preciseIdentifier":"c:objc(cs)AVAssetResourceLoader"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldWaitForLoadingOfRequestedResource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVAssetResourceLoadingRequest","preciseIdentifier":"c:objc(cs)AVAssetResourceLoadingRequest"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/resourceLoader(_:shouldWaitForLoadingOfRequestedResource:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"resourceLoader:shouldWaitForLoadingOfRequestedResource:"}],"url":"\/documentation\/kksplayer\/uniplayer\/resourceloader(_:shouldwaitforloadingofrequestedresource:)"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer":{"role":"symbol","title":"UniPlayer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniPlayer"}],"abstract":[{"type":"text","text":"Loads, controls and renders audio and video content represented through Sources."},{"type":"text","text":" "},{"type":"text","text":"A player instance can be created via the UniPlayerFactory.create function and will idle until one or more Sources are loaded."},{"type":"text","text":" "},{"type":"text","text":"Once load is called, the player becomes active and initiates necessary downloads to start playback of the loaded source(s)."}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UniPlayer"}],"url":"\/documentation\/kksplayer\/uniplayer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/resourceLoader(_:shouldWaitForLoadingOfRequestedResource:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer~1resourceLoader(_:shouldWaitForLoadingOfRequestedResource:)\/title","value":"resourceLoader:shouldWaitForLoadingOfRequestedResource:"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer~1resourceLoader(_:shouldWaitForLoadingOfRequestedResource:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resourceLoader:shouldWaitForLoadingOfRequestedResource:"}]},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/title","value":"UniPlayer"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/fragments","value":[{"kind":"identifier","text":"UniPlayer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}