{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kksplayer\/uniplayer\/load(source:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/load(source:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"load"},{"text":"(","kind":"text"},{"text":"source","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UniSource","kind":"typeIdentifier","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSource","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniSource"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"title":"load(source:)","role":"symbol","roleHeading":"Instance Method","extendedModule":"KKSPlayer","externalID":"s:9KKSPlayer9UniPlayerC4load6sourceyAA0B6SourceC_tF","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"load","kind":"identifier"},{"text":"(","kind":"text"},{"text":"source","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UniSource","kind":"typeIdentifier","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniSource"},{"text":")","kind":"text"}],"symbolKind":"method","modules":[{"name":"KKSPlayer"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Loads a new Source into the player.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer"]]},"kind":"symbol","references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSource":{"title":"UniSource","url":"\/documentation\/kksplayer\/unisource","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UniSource"}],"role":"symbol","navigatorTitle":[{"text":"UniSource","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSource","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","role":"collection","url":"\/documentation\/kksplayer","kind":"symbol","title":"KKSPlayer","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UniPlayer","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"UniPlayer"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer","type":"topic","url":"\/documentation\/kksplayer\/uniplayer","title":"UniPlayer","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"An object that provides the interface to control the player’s transport behavior."}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/load(source:)":{"url":"\/documentation\/kksplayer\/uniplayer\/load(source:)","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/load(source:)","abstract":[{"type":"text","text":"Loads a new Source into the player."}],"kind":"symbol","title":"load(source:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"load","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UniSource","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniSource"},{"text":")","kind":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSource\/title","value":"UniSource"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSource\/fragments","value":[{"text":"UniSource","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/title","op":"replace","value":"UniPlayer"},{"value":[{"text":"UniPlayer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/fragments"}]}]}