{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/resourceLoader(_:shouldWaitForLoadingOfRequestedResource:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/AVAssetResourceLoaderDelegate-Implementations"]]},"variants":[{"paths":["\/documentation\/kksplayer\/uniplayer\/resourceloader(_:shouldwaitforloadingofrequestedresource:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/kksplayer\/uniplayer\/resourceloader(_:shouldwaitforloadingofrequestedresource:)"]}],"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"AVAssetResourceLoaderDelegate.resourceLoader(_:shouldWaitForLoadingOfRequestedResource:)"},{"type":"text","text":"."}],"metadata":{"externalID":"c:@CM@KKSPlayer@objc(cs)UniPlayer(im)resourceLoader:shouldWaitForLoadingOfRequestedResource:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"resourceLoader:shouldWaitForLoadingOfRequestedResource:"}],"extendedModule":"KKSPlayer","roleHeading":"Instance Method","modules":[{"name":"KKSPlayer"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"resourceLoader","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AVAssetResourceLoader","preciseIdentifier":"c:objc(cs)AVAssetResourceLoader","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"shouldWaitForLoadingOfRequestedResource","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AVAssetResourceLoadingRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAssetResourceLoadingRequest"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"resourceLoader(_:shouldWaitForLoadingOfRequestedResource:)","symbolKind":"method"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"resourceLoader","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"resourceLoader","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"AVAssetResourceLoader","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAssetResourceLoader"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"shouldWaitForLoadingOfRequestedResource"},{"text":" ","kind":"text"},{"text":"loadingRequest","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AVAssetResourceLoadingRequest","preciseIdentifier":"c:objc(cs)AVAssetResourceLoadingRequest"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}],"kind":"declarations"}],"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/resourceLoader(_:shouldWaitForLoadingOfRequestedResource:)":{"url":"\/documentation\/kksplayer\/uniplayer\/resourceloader(_:shouldwaitforloadingofrequestedresource:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/resourceLoader(_:shouldWaitForLoadingOfRequestedResource:)","navigatorTitle":[{"kind":"identifier","text":"resourceLoader:shouldWaitForLoadingOfRequestedResource:"}],"role":"symbol","title":"resourceLoader(_:shouldWaitForLoadingOfRequestedResource:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"resourceLoader","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVAssetResourceLoader","preciseIdentifier":"c:objc(cs)AVAssetResourceLoader"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldWaitForLoadingOfRequestedResource"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AVAssetResourceLoadingRequest","preciseIdentifier":"c:objc(cs)AVAssetResourceLoadingRequest"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","role":"collection","url":"\/documentation\/kksplayer","kind":"symbol","title":"KKSPlayer","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/AVAssetResourceLoaderDelegate-Implementations":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/AVAssetResourceLoaderDelegate-Implementations","url":"\/documentation\/kksplayer\/uniplayer\/avassetresourceloaderdelegate-implementations","abstract":[],"kind":"article","role":"collectionGroup","title":"AVAssetResourceLoaderDelegate Implementations","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UniPlayer","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"UniPlayer"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer","type":"topic","url":"\/documentation\/kksplayer\/uniplayer","title":"UniPlayer","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"An object that provides the interface to control the player’s transport behavior."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"resourceLoader:shouldWaitForLoadingOfRequestedResource:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"resourceLoader:shouldWaitForLoadingOfRequestedResource:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"resourceLoader:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVAssetResourceLoader","preciseIdentifier":"c:objc(cs)AVAssetResourceLoader"},{"kind":"text","text":" *) "},{"text":"resourceLoader","kind":"internalParam"},{"kind":"text","text":" "},{"text":"shouldWaitForLoadingOfRequestedResource:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"AVAssetResourceLoadingRequest","preciseIdentifier":"c:objc(cs)AVAssetResourceLoadingRequest"},{"text":" *) ","kind":"text"},{"text":"loadingRequest","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"resourceLoader:shouldWaitForLoadingOfRequestedResource:","op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer~1resourceLoader(_:shouldWaitForLoadingOfRequestedResource:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"resourceLoader:shouldWaitForLoadingOfRequestedResource:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer~1resourceLoader(_:shouldWaitForLoadingOfRequestedResource:)\/fragments"},{"value":"UniPlayer","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/title","op":"replace"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/fragments","op":"replace","value":[{"kind":"identifier","text":"UniPlayer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}