{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSource","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniSource","text":"UniSource"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/kksplayer\/uniplayer\/source"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/source","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns the currently active source or null if no source is active."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UniSource","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniSource"},{"kind":"text","text":"?"}],"title":"source","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:9KKSPlayer9UniPlayerC6sourceAA0B6SourceCSgvp","modules":[{"name":"KKSPlayer"}]},"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer"]]},"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer":{"role":"symbol","title":"UniPlayer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniPlayer"}],"abstract":[{"type":"text","text":"Loads, controls and renders audio and video content represented through Sources."},{"type":"text","text":" "},{"type":"text","text":"A player instance can be created via the UniPlayerFactory.create function and will idle until one or more Sources are loaded."},{"type":"text","text":" "},{"type":"text","text":"Once load is called, the player becomes active and initiates necessary downloads to start playback of the loaded source(s)."}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UniPlayer"}],"url":"\/documentation\/kksplayer\/uniplayer"},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"role":"collection","title":"KKSPlayer","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","kind":"symbol","type":"topic","url":"\/documentation\/kksplayer"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/source":{"role":"symbol","title":"source","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UniSource","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniSource"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Returns the currently active source or null if no source is active."}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/source","kind":"symbol","type":"topic","url":"\/documentation\/kksplayer\/uniplayer\/source"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSource":{"role":"symbol","title":"UniSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniSource"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UniSource"}],"url":"\/documentation\/kksplayer\/unisource"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/title","value":"UniPlayer"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/fragments","value":[{"kind":"identifier","text":"UniPlayer"}]},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSource\/title","value":"UniSource"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSource\/fragments","value":[{"kind":"identifier","text":"UniSource"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}