{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"source"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSource","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniSource","text":"UniSource"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveSourceErrorEvent"},{"kind":"text","text":" "},{"kind":"internalParam","text":"event"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceErrorEvent","preciseIdentifier":"s:9KKSPlayer19UniSourceErrorEventC","text":"UniSourceErrorEvent"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/kksplayer\/uniplayer\/source(_:didreceivesourceerrorevent:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/source(_:didReceiveSourceErrorEvent:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UniSourceListener.source(_:didReceiveSourceErrorEvent:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"source(_:didReceiveSourceErrorEvent:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"source"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UniSource","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniSource"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveSourceErrorEvent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UniSourceErrorEvent","preciseIdentifier":"s:9KKSPlayer19UniSourceErrorEventC"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:9KKSPlayer9UniPlayerC6source_26didReceiveSourceErrorEventyAA0bG0C_AA0bghI0CtF","extendedModule":"KKSPlayer","modules":[{"name":"KKSPlayer"}]},"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/UniSourceListener-Implementations"]]},"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/source(_:didReceiveSourceErrorEvent:)":{"role":"symbol","title":"source(_:didReceiveSourceErrorEvent:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"source"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UniSource","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniSource"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveSourceErrorEvent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UniSourceErrorEvent","preciseIdentifier":"s:9KKSPlayer19UniSourceErrorEventC"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/source(_:didReceiveSourceErrorEvent:)","kind":"symbol","type":"topic","url":"\/documentation\/kksplayer\/uniplayer\/source(_:didreceivesourceerrorevent:)"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer":{"role":"symbol","title":"UniPlayer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniPlayer"}],"abstract":[{"type":"text","text":"Loads, controls and renders audio and video content represented through Sources."},{"type":"text","text":" "},{"type":"text","text":"A player instance can be created via the UniPlayerFactory.create function and will idle until one or more Sources are loaded."},{"type":"text","text":" "},{"type":"text","text":"Once load is called, the player becomes active and initiates necessary downloads to start playback of the loaded source(s)."}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UniPlayer"}],"url":"\/documentation\/kksplayer\/uniplayer"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSource":{"role":"symbol","title":"UniSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniSource"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UniSource"}],"url":"\/documentation\/kksplayer\/unisource"},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"role":"collection","title":"KKSPlayer","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","kind":"symbol","type":"topic","url":"\/documentation\/kksplayer"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSourceErrorEvent":{"role":"symbol","title":"UniSourceErrorEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniSourceErrorEvent"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSourceErrorEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UniSourceErrorEvent"}],"url":"\/documentation\/kksplayer\/unisourceerrorevent"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/UniSourceListener-Implementations":{"role":"collectionGroup","title":"UniSourceListener Implementations","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/UniSourceListener-Implementations","kind":"article","type":"topic","url":"\/documentation\/kksplayer\/uniplayer\/unisourcelistener-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/title","value":"UniPlayer"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/fragments","value":[{"kind":"identifier","text":"UniPlayer"}]},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSource\/title","value":"UniSource"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSource\/fragments","value":[{"kind":"identifier","text":"UniSource"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}