{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSubtitleTrack","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniSubtitleTrack","text":"UniSubtitleTrack"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/kksplayer\/uniplayer\/subtitle"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/subtitle","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns the currently used SubtitleTrack."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UniSubtitleTrack","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniSubtitleTrack"}],"title":"subtitle","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:9KKSPlayer9UniPlayerC8subtitleAA0B13SubtitleTrackCvp","modules":[{"name":"KKSPlayer"}]},"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer"]]},"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer/subtitle":{"role":"symbol","title":"subtitle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UniSubtitleTrack","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniSubtitleTrack"}],"abstract":[{"type":"text","text":"Returns the currently used SubtitleTrack."}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer\/subtitle","kind":"symbol","type":"topic","url":"\/documentation\/kksplayer\/uniplayer\/subtitle"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer":{"role":"symbol","title":"UniPlayer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniPlayer"}],"abstract":[{"type":"text","text":"Loads, controls and renders audio and video content represented through Sources."},{"type":"text","text":" "},{"type":"text","text":"A player instance can be created via the UniPlayerFactory.create function and will idle until one or more Sources are loaded."},{"type":"text","text":" "},{"type":"text","text":"Once load is called, the player becomes active and initiates necessary downloads to start playback of the loaded source(s)."}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UniPlayer"}],"url":"\/documentation\/kksplayer\/uniplayer"},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"role":"collection","title":"KKSPlayer","abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","kind":"symbol","type":"topic","url":"\/documentation\/kksplayer"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniSubtitleTrack":{"role":"symbol","title":"UniSubtitleTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UniSubtitleTrack"}],"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniSubtitleTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UniSubtitleTrack"}],"url":"\/documentation\/kksplayer\/unisubtitletrack"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/title","value":"UniPlayer"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/fragments","value":[{"kind":"identifier","text":"UniPlayer"}]},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSubtitleTrack\/title","value":"UniSubtitleTrack"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniSubtitleTrack\/fragments","value":[{"kind":"identifier","text":"UniSubtitleTrack"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}