{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniControllerPlayerView\/init(player:frame:)"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"player","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UniPlayer","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"text":")","kind":"text"}],"title":"init(player:frame:)","modules":[{"name":"KKSPlayer"}],"role":"symbol","symbolKind":"init","roleHeading":"Initializer","externalID":"s:9KKSPlayer23UniControllerPlayerViewC6player5frameAcA0bD0C_So6CGRectVtcfc"},"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniControllerPlayerView"]]},"abstract":[{"text":"Creates a new instance of the PlayerView.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kksplayer\/unicontrollerplayerview\/init(player:frame:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"player","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer","text":"UniPlayer","kind":"typeIdentifier","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"frame"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"abstract":[],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","role":"collection","url":"\/documentation\/kksplayer","kind":"symbol","title":"KKSPlayer","type":"topic"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UniPlayer","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"UniPlayer"}],"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer","type":"topic","url":"\/documentation\/kksplayer\/uniplayer","title":"UniPlayer","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"An object that provides the interface to control the player’s transport behavior."}]},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniControllerPlayerView":{"url":"\/documentation\/kksplayer\/unicontrollerplayerview","abstract":[],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UniControllerPlayerView","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"UniControllerPlayerView","kind":"identifier"}],"title":"UniControllerPlayerView","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniControllerPlayerView"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniControllerPlayerView/init(player:frame:)":{"url":"\/documentation\/kksplayer\/unicontrollerplayerview\/init(player:frame:)","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniControllerPlayerView\/init(player:frame:)","kind":"symbol","abstract":[{"type":"text","text":"Creates a new instance of the PlayerView."}],"type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"player"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","text":"UniPlayer"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":")","kind":"text"}],"title":"init(player:frame:)"}},"variantOverrides":[{"patch":[{"value":"UniPlayer","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"UniPlayer"}],"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniControllerPlayerView\/title","value":"UniControllerPlayerView"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniControllerPlayerView\/fragments","op":"replace","value":[{"kind":"identifier","text":"UniControllerPlayerView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}