{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"player"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"player"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","text":"UniPlayer","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didReceiveOnReadyEvent","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"event","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UniEvent","kind":"typeIdentifier","preciseIdentifier":"s:9KKSPlayer8UniEventP","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniEvent"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniControllerPlayerView"]]},"metadata":{"modules":[{"name":"BVPlayer"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"player","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","kind":"typeIdentifier","text":"UniPlayer"},{"kind":"text","text":", "},{"text":"didReceiveOnReadyEvent","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:9KKSPlayer8UniEventP","text":"UniEvent","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"s:9KKSPlayer23UniControllerPlayerViewC6player_22didReceiveOnReadyEventyAA0bD0C_AA0bK0_ptF","symbolKind":"method","title":"player(_:didReceiveOnReadyEvent:)","roleHeading":"Instance Method","role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniControllerPlayerView\/player(_:didReceiveOnReadyEvent:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kksplayer\/unicontrollerplayerview\/player(_:didreceiveonreadyevent:)"]}],"kind":"symbol","references":{"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniPlayer":{"url":"\/documentation\/kksplayer\/uniplayer","title":"UniPlayer","abstract":[{"text":"An object that provides the interface to control the player’s transport behavior.","type":"text"}],"role":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniPlayer","navigatorTitle":[{"kind":"identifier","text":"UniPlayer"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UniPlayer","kind":"identifier"}],"kind":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniControllerPlayerView":{"url":"\/documentation\/kksplayer\/unicontrollerplayerview","title":"UniControllerPlayerView","type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UniControllerPlayerView","kind":"identifier"}],"navigatorTitle":[{"text":"UniControllerPlayerView","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniControllerPlayerView"},"doc://KKS.KKSPlayer/documentation/KKSPlayer":{"type":"topic","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer","abstract":[{"text":"BlendVision One iOS Player SDK","type":"text"}],"title":"BVPlayer","url":"\/documentation\/kksplayer","kind":"symbol","role":"collection"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniControllerPlayerView/player(_:didReceiveOnReadyEvent:)":{"title":"player(_:didReceiveOnReadyEvent:)","abstract":[],"type":"topic","url":"\/documentation\/kksplayer\/unicontrollerplayerview\/player(_:didreceiveonreadyevent:)","identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniControllerPlayerView\/player(_:didReceiveOnReadyEvent:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"player","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@KKSPlayer@objc(cs)UniPlayer","text":"UniPlayer"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceiveOnReadyEvent"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UniEvent","preciseIdentifier":"s:9KKSPlayer8UniEventP"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol"},"doc://KKS.KKSPlayer/documentation/KKSPlayer/UniEvent":{"identifier":"doc:\/\/KKS.KKSPlayer\/documentation\/KKSPlayer\/UniEvent","navigatorTitle":[{"text":"UniEvent","kind":"identifier"}],"title":"UniEvent","role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/kksplayer\/unievent","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UniEvent","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/title","value":"UniPlayer","op":"replace"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniPlayer\/fragments","op":"replace","value":[{"text":"UniPlayer","kind":"identifier"}]},{"value":"UniControllerPlayerView","op":"replace","path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniControllerPlayerView\/title"},{"path":"\/references\/doc:~1~1KKS.KKSPlayer~1documentation~1KKSPlayer~1UniControllerPlayerView\/fragments","op":"replace","value":[{"kind":"identifier","text":"UniControllerPlayerView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}